(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function loadCss(){if($('#compactUiCss'))return;const l=document.createElement('link');l.id='compactUiCss';l.rel='stylesheet';l.href='compact-ui.css';document.head.appendChild(l)}
function section(id,icon,title,desc,node,open=false){const wrap=document.createElement('section');wrap.className='voice-compact-section'+(open?' open':'');wrap.dataset.compact=id;const head=document.createElement('button');head.type='button';head.className='voice-compact-head';head.innerHTML=`<span class="vci">${icon}</span><span class="vct"><b>${title}</b><small>${desc}</small></span><span class="vchev">⌄</span>`;const body=document.createElement('div');body.className='voice-compact-body';const inner=document.createElement('div');inner.className='voice-compact-inner';if(node)inner.appendChild(node);body.appendChild(inner);wrap.append(head,body);head.addEventListener('click',()=>toggle(wrap));return wrap}
function toggle(target){const shell=target.closest('.voice-compact-shell');shell?.querySelectorAll('.voice-compact-section').forEach(s=>{if(s!==target)s.classList.remove('open')});target.classList.toggle('open')}
function openSection(id){const s=document.querySelector(`.voice-compact-section[data-compact="${id}"]`);if(!s)return;s.closest('.voice-compact-shell')?.querySelectorAll('.voice-compact-section').forEach(x=>x.classList.toggle('open',x===s));s.classList.add('compact-section-flash');setTimeout(()=>s.classList.remove('compact-section-flash'),750);s.scrollIntoView({behavior:'smooth',block:'start'})}
function buildFab(view){if($('#voiceFab'))return;const menu=document.createElement('div');menu.id='voiceFabMenu';menu.className='voice-fab-menu';menu.innerHTML=`<button class="voice-fab-action" data-vfab="tools"><span>🎙️</span><b>Herramientas</b></button><button class="voice-fab-action" data-vfab="routines"><span>▶️</span><b>Rutinas</b></button><button class="voice-fab-action" data-vfab="training"><span>🎤</span><b>Entrenamiento</b></button>`;const fab=document.createElement('button');fab.id='voiceFab';fab.className='voice-fab';fab.type='button';fab.setAttribute('aria-label','Acciones de Voz');fab.textContent='＋';document.body.append(menu,fab);fab.onclick=()=>{fab.classList.toggle('open');menu.classList.toggle('open')};menu.onclick=e=>{const b=e.target.closest('[data-vfab]');if(!b)return;openSection(b.dataset.vfab);fab.classList.remove('open');menu.classList.remove('open')};const obs=new MutationObserver(()=>{const hidden=view.classList.contains('hidden');fab.style.display=hidden?'none':'block';menu.style.display=hidden?'none':'grid';if(hidden){fab.classList.remove('open');menu.classList.remove('open')}});obs.observe(view,{attributes:true,attributeFilter:['class']});fab.style.display=view.classList.contains('hidden')?'none':'block';menu.style.display=view.classList.contains('hidden')?'none':'grid'}
function transform(){loadCss();const view=$('#voiceView');if(!view||view.dataset.compactReady==='1')return false;const pro=$('#voiceProTools'),routines=view.querySelector('.voice-routines'),grid=view.querySelector('.voice-grid'),panel=$('#voicePanel');if(!routines||!grid)return false;view.dataset.compactReady='1';const shell=document.createElement('div');shell.className='voice-compact-shell';const proWrap=pro||document.createElement('div');if(!pro)proWrap.innerHTML='<p class="muted">Herramientas de voz cargando…</p>';const routinesWrap=document.createElement('div');routinesWrap.appendChild(routines);const trainingWrap=document.createElement('div');trainingWrap.appendChild(grid);if(panel)trainingWrap.appendChild(panel);shell.append(section('routines','▶️','Rutinas guiadas','5, 10 y 20 minutos, paso a paso',routinesWrap,true),section('training','🎤','Entrena por objetivo','Calentamiento, resonancia, rango, dicción y más',trainingWrap),section('tools','🎙️','Herramientas de voz','Micrófono, afinación, rango y modo grupal',proWrap));const hero=view.querySelector('.voice-warning')||view.querySelector('.voice-hero');hero.insertAdjacentElement('afterend',shell);[...view.children].forEach(n=>{if(n===shell||n.matches?.('.back,.voice-hero,.voice-warning'))return;if(n.tagName==='H2'&&(n.textContent.includes('Rutinas')||n.textContent.includes('Entrena')))n.remove()});buildFab(view);return true}
function retry(){let tries=0;const id=setInterval(()=>{tries++;if(transform()||tries>30)clearInterval(id)},160)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',retry);else retry();
})();
