(()=>{
'use strict';
const hymns=[
{
 id:1014,bookNumber:14,title:'¡Dios Está Presente!',artist:'Gerhard Tersteegen · ARNSBERG',type:'himnos',tone:'F',
 content:`[Himno 14]\n\n[Verso 1]\nF                     C7        F\n¡Dios está presente! Vamos a postrarnos\nBb                    F        C7\nante él con reverencia; en silencio estemos\nF                     Bb       F\nfrente a su grandeza, implorando su clemencia.\nDm                 Gm      C7      F\nQuien con él quiera andar, su mirada eleve; votos le renueve.\n\n[Verso 2]\nF                     C7        F\n¡Dios está presente! Y los serafines\nBb                    F        C7\nlo adoran reverentes; «Santo, santo, santo»,\nF                     Bb       F\nen su honor le cantan los ejércitos celestes.\nDm                 Gm      C7      F\n¡Oh buen Dios! nuestra voz, como humilde ofrenda a tu trono ascienda.\n\n[Verso 3]\nF                     C7        F\nComo el sol irradia sobre el tierno lirio,\nBb                    F        C7\nque contento se doblega, Dios omnipresente,\nF                     Bb       F\nilumina mi alma y feliz yo te obedezca;\nDm                 Gm      C7      F\nhaz que así, tú en mí seas reflejado, y tu amor, probado. Amén.`
},
{
 id:1015,bookNumber:15,title:'Nunca, Dios Mío',artist:'Juan B. Cabrera · FLEMMING',type:'himnos',tone:'Ab',
 content:`[Himno 15]\n\n[Verso 1]\nAb          Eb7      Ab      Db      Ab\nNunca, Dios mío, cesará mi labio de bendecirte, de cantar tu gloria,\nC7       Fm           C       Ab      Eb7\nporque conservo de tu amor inmenso grata memoria.\nAb      Bb7      Eb    Bb7   Eb     Db      Ab  Eb  Ab\n\n[Verso 2]\nAb          Eb7      Ab      Db      Ab\nCuando perdido en mundanal sendero no me cercaba sino niebla oscura,\nC7       Fm           C       Ab      Eb7\ntú me miraste, y alumbróme un rayo de tu luz pura.\nAb      Bb7      Eb    Bb7   Eb     Db      Ab  Eb  Ab\n\n[Verso 3]\nAb          Eb7      Ab      Db      Ab\nCuando inclinaba mi abatida frente por el pecado de mi necio yugo,\nC7       Fm           C       Ab      Eb7\ndulce reposo y eficaz alivio darme te plugo.\nAb      Bb7      Eb    Bb7   Eb     Db      Ab  Eb  Ab\n\n[Verso 4]\nAb          Eb7      Ab      Db      Ab\nCuando los dones malgasté a porfía, con que a mi alma pródigo adornaste,\nC7       Fm           C       Ab      Eb7\n«Padre, he pecado», con dolor te dije, y me abrazaste.\nAb      Bb7      Eb    Bb7   Eb     Db      Ab  Eb  Ab\n\n[Verso 5]\nAb          Eb7      Ab      Db      Ab\nCuando en sus propios méritos se fiaba, nunca mi pecho con amor latía;\nC7       Fm           C       Ab      Eb7\nhoy de amor late, porque en tus bondades sólo confía.\nAb      Bb7      Eb    Bb7   Eb     Db      Ab  Eb  Ab`
},
{
 id:1016,bookNumber:16,title:'Engrandecido Sea Dios',artist:'Henry S. Turrall · DIADEM',type:'himnos',tone:'Eb',
 content:`[Himno 16]\n\n[Verso 1]\nEb                    Bb7        Eb\nEngrandecido sea Dios en esta reunión, en esta reunión.\nAb                    Eb              Bb7\nAlegres, juntos a una voz, dad gloria, gloria, gloria, gloria,\nEb           Ab      Eb   Bb7   Eb\n¡dad gloria, gloria a nuestro Dios! Amén.\n\n[Verso 2]\nEb                    Bb7        Eb\nDurante el día que pasó la mano del Señor, la mano del Señor,\nAb                    Eb              Bb7\nde muchos males nos salvó; ¡dad gloria, gloria, gloria, gloria,\nEb           Ab      Eb   Bb7   Eb\n¡dad gloria, gloria a nuestro Dios!\n\n[Verso 3]\nEb                    Bb7        Eb\nPues hasta aquí nos ayudó, y siempre proveerá, y siempre proveerá.\nAb                    Eb              Bb7\nCon gratitud, placer y amor, dad gloria, gloria, gloria, gloria,\nEb           Ab      Eb   Bb7   Eb\n¡dad gloria, gloria a nuestro Dios!\n\n[Verso 4]\nEb                    Bb7        Eb\nA otras almas ¡salva, oh Dios! Despiértalas, Señor, despiértalas, Señor.\nAb                    Eb              Bb7\nEscucha nuestra petición; dad gloria, gloria, gloria, gloria,\nEb           Ab      Eb   Bb7   Eb\n¡dad gloria, gloria a nuestro Dios!`
},
{
 id:1017,bookNumber:17,title:'Todos Juntos Tributemos',artist:'F. M. Fernández · DISMISSAL',type:'himnos',tone:'A',
 content:`[Himno 17]\n\n[Verso 1]\nA              D          A        E7\nTodos juntos tributemos gracias al buen Salvador;\nA              D          A        E7\ngrande ha sido su paciencia y precioso su amor.\nA          D        A      E7      A\n¡Aleluya! ¡Aleluya! Proclamemos su loor.\n\n[Verso 2]\nA              D          A        E7\nNuestro Rey divino, eterno, nos rodea con favor;\nA              D          A        E7\nfortalece a los cansados y perdona al pecador.\nA          D        A      E7      A\n¡Aleluya! ¡Aleluya! Proclamemos su loor.\n\n[Verso 3]\nA              D          A        E7\nEn él pongamos la confianza, en el santo Redentor;\nA              D          A        E7\ny en la gloria, redimidos, cantaremos su amor.\nA          D        A      E7      A\n¡Aleluya! ¡Aleluya! Proclamemos su loor.`
},
{
 id:1018,bookNumber:18,title:'Corazones Te Ofrecemos',artist:'Maurilio López · HOLY MANNA',type:'himnos',tone:'G',
 content:`[Himno 18]\n\n[Verso 1]\nG                    D        G\nCorazones te ofrecemos, Dios de vida y plenitud;\nG                    D        G\nal Señor hoy honraremos con lealtad y gratitud.\nG                    D        G\ntú perdonas rebeliones al que escoges para bien;\nG                    D        G\n¡tú, tan fuerte, nos recibes para darles tu sostén!\n\n[Verso 2]\nG                    D        G\nTú respondes en justicia con tremendas cosas santas;\nG                    D        G\ntierra y mar los habitamos con tu poder; tú las levantas.\nG                    D        G\nen la tierra tú afirmas las montañas con poder;\nG                    D        G\ny el rugir de mares callas y la gente en su correr.\n\n[Verso 3]\nG                    D        G\nLas mañanas y las tardes, a las tardes das favor;\nG                    D        G\nmaravillas son tus obras, que producen gran pavor.\nG                    D        G\ntú visitas a la tierra con tus lluvias, oh Señor;\nG                    D        G\ny la riegas por doquiera, la enriqueces con valor.\n\n[Verso 4]\nG                    D        G\nCon las aguas, los desiertos de renuevos vestirás;\nG                    D        G\ny los valles con sus frutos con gran fuerza llenarás.\nG                    D        G\ngracias hoy, Señor, te damos porque aceptas la oración,\nG                    D        G\ny los votos te pagamos con placer y devoción.`
},
{
 id:1019,bookNumber:19,title:'Salmo 100',artist:'Tomás J. González Carvajal · OLD 100TH',type:'himnos',tone:'G',
 content:`[Himno 19]\n\n[Verso 1]\nG              D7        G\nCantad alegres al Señor, mortales todos por doquier;\nC              G         D7\nservidle siempre con fervor, obedecedle con placer.\nG      C     G   D7   G\n\n[Verso 2]\nG              D7        G\nCon gratitud y con canción, al Hacedor venid a él;\nC              G         D7\npues somos, según él nos dio, y Dios excelso es nuestro ser.\nG      C     G   D7   G\n\n[Verso 3]\nG              D7        G\nSu pueblo somos, salvación buscamos al Señor;\nC              G         D7\ny él nos ampara, siempre fiel, y nunca él nos olvidó.\nG      C     G   D7   G\n\n[Verso 4]\nG              D7        G\nSiempre en sus atrios alabad, su santo nombre bendecid;\nC              G         D7\neternamente es su bondad, la buena nueva difundid.\nG      C     G   D7   G\n\n[Verso 5]\nG              D7        G\nMisericordia sin igual nos muestra por la eternidad,\nC              G         D7\ny por la eterna salvación su verdad permanece. Amén.\nG      C     G   D7   G`
},
{
 id:1020,bookNumber:20,title:'¡Cuán Grande Es Él!',artist:'Stuart K. Hine',type:'himnos',tone:'Bb',
 content:`[Himno 20]\n\n[Verso 1]\nBb                    Eb\nSeñor, mi Dios, al contemplar los cielos,\nBb                    F7       Bb\nel firmamento y las estrellas mil;\nEb                    Bb\nal oír tu voz en los potentes truenos\nF7                                  Bb\ny ver brillar el sol en su cenit:\n\n[Coro]\nBb                 Eb                Bb\nMi corazón entona la canción: ¡Cuán grande es él! ¡Cuán grande es él!\nF7                                Bb\nMi corazón entona la canción: ¡Cuán grande es él! ¡Cuán grande es él!\n\n[Verso 2]\nBb                    Eb\nAl recorrer los montes y los valles\nBb                    F7       Bb\ny ver las bellas flores al pasar;\nEb                    Bb\nal escuchar el canto de las aves\nF7                                  Bb\ny el murmurar del claro manantial:\n\n[Verso 3]\nBb                    Eb\nCuando recuerdo del amor divino\nBb                    F7       Bb\nque desde el cielo al Salvador envió;\nEb                    Bb\naquel Jesús que por salvarme vino\nF7                                  Bb\ny en una cruz sufrió por mí y murió:\n\n[Verso 4]\nBb                    Eb\nCuando el Señor me llame a su presencia,\nBb                    F7       Bb\nal dulce hogar, al cielo de esplendor,\nEb                    Bb\nle adoraré cantando la grandeza\nF7                                  Bb\nde su poder y su infinito amor.`
},
{
 id:1021,bookNumber:21,title:'Alabad al Señor',artist:'Salmo 136 · ALABAD A JEHOVÁ',type:'himnos',tone:'Em',
 content:`[Himno 21]\n\n[Verso 1]\nEm                         B7\nAlabad al Señor porque él es bueno,\nEm                         B7\nalabad al Señor porque él es bueno,\nEm              Am         Em\nalabad al Señor porque él es bueno,\nB7                         Em\nporque para siempre es su misericordia.\n\n[Verso 2]\nEm                         B7\nAlabad al Dios soberano,\nEm                         B7\nalabad al Dios soberano,\nEm              Am         Em\nalabad al Dios soberano,\nB7                         Em\nporque para siempre es su misericordia.\n\n[Verso 3]\nEm                         B7\nAlabad al Señor de los señores,\nEm                         B7\nalabad al Señor de los señores,\nEm              Am         Em\nalabad al Señor de los señores,\nB7                         Em\nporque para siempre es su misericordia.`
},
{
 id:1022,bookNumber:22,title:'A Dios Demos Gloria',artist:'Fanny J. Crosby · TO GOD BE THE GLORY',type:'himnos',tone:'Eb',
 content:`[Himno 22]\n\n[Verso 1]\nEb                  Ab         Eb\nA Dios demos gloria, pues grande es él;\nBb7                 Eb\nsu amor es inmenso y a su Hijo nos dio:\nAb                   Eb\nquien fue a la cruz do sufrió muerte cruel,\nBb7                                   Eb\ny así de los cielos las puertas abrió.\n\n[Coro]\nEb               Ab          Eb\nDad loor al Señor, oiga el mundo su voz;\nBb7                           Eb\ndad loor al Señor, nos gozamos en Dios.\nAb                  Eb\nVenid al Padre y a su Hijo Jesús,\nBb7                                   Eb\ny démosle gloria por su gran poder. Amén.\n\n[Verso 2]\nEb                  Ab         Eb\nPor darnos la vida su sangre vertió;\nBb7                 Eb\nJesús al creyente es promesa de Dios;\nAb                   Eb\nel vil pecador que de veras creyó\nBb7                                   Eb\nen ese momento perdón recibió.\n\n[Verso 3]\nEb                  Ab         Eb\nDios es el Maestro, potente Hacedor,\nBb7                 Eb\ny grande es el gozo que Cristo nos da;\nAb                   Eb\nmas nuestro asombro será aún mayor\nBb7                                   Eb\nal ver a Jesús que en su gloria vendrá.`
}
];
const target=window.LAGREY_SONGS||(window.LAGREY_SONGS=[]);
for(const h of hymns){if(!target.some(s=>s.id===h.id))target.push(h)}
window.LAGREY_HYMNS=[...(window.LAGREY_HYMNS||[]),...hymns.filter(h=>!(window.LAGREY_HYMNS||[]).some(x=>x.id===h.id))];
})();