(()=>{
'use strict';
const hymns=[
{id:1311,bookNumber:311,title:"Oh Dios, Mi Soberano Rey",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 311]\n\n[Verso 1]\nOh Dios, mi Soberano Rey, A ti dare loor; Tu nombre yo en sal zare, Santisimo Se nor.\n\n[Verso 2]\nTus obras evi dencias son De in finito amor; Y cantan con a le gre voz Las glorias de! Se nor.\n\n[Verso 3]\nAquel que busca salvaci6n, En Cristo la haIlara; A su ferviente pe tici6n, El pronto atendera.`},
{id:1312,bookNumber:312,title:"Ten Compasión de Mí",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 312]\n\n312 Ten Compasi6n de Mi\nLavame mas y mas de mi maldad, y limpiame de mi pecado. Sal. 51 :2\nHaz mani\nFue\nfies\ntu hondad,\nque nacl,\nY lavame de\nY por herencia\nMostrandome tu\ny no me\nDis puesto a\nE ternas\ny coraz6n,\nmi maldad; Mi alma digna\nrecibi Un obstinado\nsalvaci6n; Entonces alza\ndejes mas pecar.\ntoda transgresion.\nglorias a mi Dios.\nte lim-\ncora-\nra mi\nAmen.`},
{id:1313,bookNumber:313,title:"Los Que Esperan en Jehová",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 313]\n\nLos que esperan en Jehová tendrán nuevas fuerzas.\nLos que esperan en Jehová nuevas fuerzas poseerán.\nEn los brazos de mi Jesús hay lugar de consuelo y luz.\nFuertes alas para volar, los que esperan en Jehová.`},
{id:1314,bookNumber:314,title:"Dios, Yo Quiero Ser Cristiano",artist:'Himnario Bautista 1976',type:'himnos',tone:"Cm",content:`[Himno 314]\n\n[Verso 1]\nDios, yo quiero ser cristiano de corazón, de corazón.\nDios, yo quiero ser cristiano de corazón.\n\n[Verso 2]\nDios, yo quiero ser más santo de corazón, de corazón.\nDios, yo quiero ser más santo de corazón.\n\n[Verso 3]\nDios, yo quiero ser más limpio de corazón, de corazón.\nDios, yo quiero ser más limpio de corazón.\n\n[Verso 4]\nDios, yo quiero amarte siempre de corazón, de corazón.\nDios, yo quiero amarte siempre de corazón.`},
{id:1315,bookNumber:315,title:"Más de Jesús Quiero Aprender",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 315]\n\nMás de Jesús quiero aprender,\nmás de su amor con que me amó,\nmás de su cruz en que murió.\nMás de sus dones recibir,\nmás con los otros compartir.\nMás de la gloria de su faz,\nmás de su luz, más de su paz.\nMás quiero amarle; más quiero honrarle;\nmás de su salvación gozar,\nmás de su dulce amor gustar.`},
{id:1316,bookNumber:316,title:"Dios de Amor, Te Imploramos",artist:'Himnario Bautista 1976',type:'himnos',tone:"D",content:`[Himno 316]\n\nDios de amor, humildemente te imploramos con tesón.\nLimpia los motivos nuestros; danos purificación.\nConsagrados a ti, Cristo, te queremos hoy servir.\nCuando estemos indecisos y sin luz o dirección,\ndanos tu sabiduría; oye nuestra petición.\nSi bendices las lecciones, premio grato nos será;\npues es nuestro solo anhelo tu gran nombre celebrar.`},
{id:1317,bookNumber:317,title:"A Jesús Pertenecemos",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 317]\n\nA Jesús pertenecemos; nos debemos alegrar.\nQue el gran Dios de cielo y tierra, él nos crió; sabrá guardar.\nA Jesús pertenecemos; por nosotros él murió.\nCon el precio de su sangre de la muerte nos libró.\nA Jesús pertenecemos; confiamos siempre en él.\nY su Espíritu nos lleva por sus sendas, guía fiel.\nA Jesús pertenecemos; redimidos por su amor.\nY a Dios Trino y Uno damos gloria, bendición y honor.`},
{id:1318,bookNumber:318,title:"Quiero Seguir",artist:'Himnario Bautista 1976',type:'himnos',tone:"Bb",content:`[Himno 318]\n\nQuiero seguir de Cristo en pos porque él me guía fiel.\nEl santo amor me inspira a mí al buen Jesús llevar.\nEl llanto oí del mundo cruel; yo tengo que ayudar.\nDoquier, siempre servir.`},
{id:1319,bookNumber:319,title:"Dulce Comunión",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 319]\n\nDulce comunión la que gozo ya en los brazos de mi Salvador.\n¡Qué gran bendición en su paz me da!\nCuán dulce es vivir, cuán dulce es gozar en los brazos de mi Salvador.\nAllí quiero ir y con él morar.\nNo hay que temer, ni que desconfiar, en los brazos de mi Salvador.\nPor su gran poder él me guardará.\nLibre, salvo, en los brazos de mi Salvador.`},
{id:1320,bookNumber:320,title:"La Paz, el Don de Mi Dios",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 320]\n\nTú guardarás en completa paz a aquel cuyo pensamiento en ti persevera.\nLa paz, el don de mi Dios.`}
];
const target=window.LAGREY_SONGS||(window.LAGREY_SONGS=[]);for(const h of hymns){if(!target.some(s=>s.id===h.id))target.push(h)}window.LAGREY_HYMNS=[...(window.LAGREY_HYMNS||[]),...hymns.filter(h=>!(window.LAGREY_HYMNS||[]).some(x=>x.id===h.id))];
})();
