(()=>{
'use strict';
const hymns=[
{
 id:1028,bookNumber:28,title:'Bendice, ¡Oh Alma Mía!',artist:'Enrique Turrall · LEONI',type:'himnos',tone:'D',
 content:`[Himno 28]\n\n[Verso 1]\nD                   A7          D\nBendice, ¡oh alma mía! A Jehová tu Dios,\nG                   D           A7\ny no te olvides de ensalzar su grande amor.\nD                   G           D\nPues él te perdonó tu mucha iniquidad;\nEm                  A7          D\ny al ver tu angustia y contrición, te dio su paz.\n\n[Verso 2]\nD                   A7          D\nTu vida rescató de la condenación;\nG                   D           A7\ny te corona de favor y bendición.\nD                   G           D\nÉl quiere enriquecer tu vida espiritual;\nEm                  A7          D\nen alas de esperanza y fe remontarás.\n\n[Verso 3]\nD                   A7          D\nUn miserable soy, indigno pecador,\nG                   D           A7\nmas por la fe en mi Salvador, mi Padre es Dios.\nD                   G           D\nSu Espíritu obra en mí y no me dejará;\nEm                  A7          D\nal acabar mi vida aquí veré su faz. Amén.`
},
{
 id:1029,bookNumber:29,title:'Venid, Nuestras Voces Alegres Unamos',artist:'Isaac Watts · KREMSER',type:'himnos',tone:'D',
 content:`[Himno 29]\n\n[Verso 1]\nD                     Em7      A       D\nVenid, nuestras voces alegres unamos\nG                     Bm       A7\nal coro celeste del trono en redor;\nD                     Em7      A       D\nsus voces se cuentan por miles de miles,\nG                     A7             D\nmas todos son uno en su gozo y amor.\n\n[Verso 2]\nD                     Em7      A       D\n«Es digno el Cordero que ha muerto», proclaman,\nG                     Bm       A7\n«de ricos dones y de honor»;\nD                     Em7      A       D\n«es digno el Cordero», decimos nosotros,\nG                     A7             D\npues él por su muerte nos ha redimido.\n\n[Verso 3]\nD                     Em7      A       D\nDigno eres, Jesús, de alcanzar en los cielos\nG                     Bm       A7\npoder y riquezas y gloria y honor;\nD                     Em7      A       D\ny las bendiciones que darte podemos\nG                     A7             D\nsean para siempre tu trono, Señor.\n\n[Verso 4]\nD                     Em7      A       D\nQue todos los seres que hicieron tus manos,\nG                     Bm       A7\nque pueblan la tierra, el aire y el mar,\nD                     Em7      A       D\nunidos proclamen tus glorias eternas,\nG                     A7             D\ny a ti, Rey soberano, den honor sin cesar. Amén.`
},
{
 id:1030,bookNumber:30,title:'Gloria Demos al Salvador',artist:'Charles Wesley · BLESSED NAME',type:'himnos',tone:'Ab',
 content:`[Himno 30]\n\n[Verso 1]\nAb                    Db      Ab\n¡Oh quién tuviera lenguas mil! Gloria demos al Salvador.\nDb                    Ab      Eb7\nCon gratitud al Rey decid: Gloria demos al Salvador.\n\n[Verso 2]\nAb                    Db      Ab\nJesús disipa todo mal, Gloria demos al Salvador;\nDb                    Ab      Eb7\nnos da pureza celestial, Gloria demos al Salvador.\n\n[Verso 3]\nAb                    Db      Ab\nAl pecador podrá limpiar, Gloria demos al Salvador;\nDb                    Ab      Eb7\nsu ser él quiere transformar, Gloria demos al Salvador.\n\n[Coro]\nAb          Db      Ab\nGloria al Salvador, gloria al Salvador,\nDb          Ab      Eb7\ngloria demos al Salvador;\nAb          Db      Ab\ngloria al Salvador, gloria al Salvador,\nEb7                         Ab\ngloria demos al Salvador.`
},
{
 id:1031,bookNumber:31,title:'Ved al Cristo, Rey de Gloria',artist:'Thomas Kelley · CROWN HIM',type:'himnos',tone:'F',
 content:`[Himno 31]\n\n[Verso 1]\nF                     C7          F\nVed al Cristo, Rey de gloria, es del mundo el vencedor;\nBb                    F           C7\nde la muerte sale invicto, todos démosle loor.\n\n[Verso 2]\nF                     C7          F\nExaltadle, exaltadle; ricos triunfos da Jesús;\nBb                    F           C7\nen los cielos entronadle, en la refulgente luz.\n\n[Verso 3]\nF                     C7          F\nPecadores se burlaron, coronando al Salvador;\nBb                    F           C7\nángeles y santos danle su riquísimo amor.\n\n[Verso 4]\nF                     C7          F\nEscuchad sus alabanzas que se elevan hacia él;\nBb                    F           C7\nvictorioso reina el Cristo: adorad a Emanuel.\n\n[Coro]\nBb                    F\nCoronadle, santos todos; coronadle Rey de reyes;\nC7                    F\ncoronadle, santos todos; coronad al Salvador.`
},
{
 id:1032,bookNumber:32,title:'Redentor, Te Adoramos',artist:'John Roy Harris · REDENTORE',type:'himnos',tone:'Eb',
 content:`[Himno 32]\n\n[Verso 1]\nEb                    Bb7         Eb\nRedentor, te adoramos, grande es tu merced y amor;\nAb                    Eb          Bb7\nque tu rostro contemplemos, que sintamos tu calor.\nEb                    Ab          Eb\nRedentor, te adoramos, de Dios muestras compasión;\nFm                    Bb7         Eb\nRedentor, te adoramos, reina en nuestro corazón.\n\n[Verso 2]\nEb                    Bb7         Eb\nRedentor, te adoramos, quita dudas y temor;\nAb                    Eb          Bb7\nresplandezca en nuestras vidas de tu rostro el fulgor.\nEb                    Ab          Eb\nRedentor, te adoramos, tu renombre es sin igual;\nFm                    Bb7         Eb\nRedentor, te adoramos, con la hueste angelical.\n\n[Verso 3]\nEb                    Bb7         Eb\nRedentor, te adoramos, perdonaste nuestro mal;\nAb                    Eb          Bb7\nllénanos de tu presencia, danos vida espiritual.\nEb                    Ab          Eb\nRedentor, te adoramos, por tu amor y libertad;\nFm                    Bb7         Eb\nRedentor, te adoramos, llénanos de tu bondad.\n\n[Verso 4]\nEb                    Bb7         Eb\nRedentor, te adoramos, tu hermosura singular\nAb                    Eb          Bb7\nalgún día por tu gracia la podremos contemplar.\nEb                    Ab          Eb\nRedentor, te adoramos, transformónos tu verdad;\nFm                    Bb7         Eb\nRedentor, te adoramos, hoy y por la eternidad. Amén.`
}
];
const target=window.LAGREY_SONGS||(window.LAGREY_SONGS=[]);
for(const h of hymns){if(!target.some(s=>s.id===h.id))target.push(h)}
window.LAGREY_HYMNS=[...(window.LAGREY_HYMNS||[]),...hymns.filter(h=>!(window.LAGREY_HYMNS||[]).some(x=>x.id===h.id))];
})();