(()=>{
'use strict';
const hymns=[
{
 id:1023,bookNumber:23,title:'Cuanto Soy y Cuanto Encierro',artist:'Juan Bautista Cabrera · STUTTGART',type:'himnos',tone:'G',
 content:`[Himno 23]\n\n[Verso 1]\nG                  D7         G\nCuanto soy y cuanto encierro manifiesto es para ti;\nC                  G          D7\npues tu vista escrutadora, oh Señor, penetra en mí.\nG                  C          G  D7  G\n\n[Verso 2]\nG                  D7         G\nSi se agita mi conciencia, tú percibes su emoción;\nC                  G          D7\nrazonar ves a la mente, meditar al corazón.\nG                  C          G  D7  G\n\n[Verso 3]\nG                  D7         G\nVes mis dudas o esperanzas, mi sosiego o mi inquietud,\nC                  G          D7\nmis tristezas o alegrías, mi dolencia o mi salud.\nG                  C          G  D7  G\n\n[Verso 4]\nG                  D7         G\nY hasta el íntimo deseo que en mi pecho se abrigó,\nC                  G          D7\nsin que el labio lo expresara, en tu oído resonó.\nG                  C          G  D7  G\n\n[Verso 5]\nG                  D7         G\n¡Oh gran Dios! si yo contemplo tu infinita perfección,\nC                  G          D7\nel asombro llena mi alma, ¡se confunde mi razón!\nG                  C          G  D7  G`
},
{
 id:1024,bookNumber:24,title:'Honor, Loor y Gloria',artist:'Theodulph de Orleans · ST. THEODULPH',type:'himnos',tone:'Eb',
 content:`[Himno 24]\n\n[Verso 1]\nEb                  Bb7        Eb\nHonor, loor y gloria a ti, buen Salvador,\nAb                  Eb         Bb7\ncual niños que cantaron hosannas al Señor.\nEb                  Ab         Eb\nY hebreos que con palmas te dieron recepción,\nFm                  Bb7        Eb\ntu pueblo te ofrece sincera aclamación.\n\n[Verso 2]\nEb                  Bb7        Eb\nTú, de David el Hijo, de Israel el Rey,\nAb                  Eb         Bb7\na ti te recibimos los miembros de tu grey;\nEb                  Ab         Eb\ncomo antes de tu muerte, honráronte también,\nFm                  Bb7        Eb\nacepta nuestras preces, como en Jerusalén.\n\n[Verso 3]\nEb                  Bb7        Eb\nRecibes la alabanza, y oyes la oración;\nAb                  Eb         Bb7\nlo bueno te deleita, también la adoración.\nEb                  Ab         Eb\nHonor, loor y gloria a ti, Rey, Redentor,\nFm                  Bb7        Eb\nnosotros ensalzamos tu nombre, oh Señor.`
},
{
 id:1025,bookNumber:25,title:'Santo Dios, Te Damos Loor',artist:'Ignaz Franz · GROSSER GOTT',type:'himnos',tone:'Eb',
 content:`[Himno 25]\n\n[Verso 1]\nEb                    Bb7        Eb\nSanto Dios, te damos loor; nos postramos con reverencia;\nAb                    Eb         Bb7\nde la tierra tú eres Señor, en el cielo todos te adoran.\nEb                    Ab         Eb\ninfinito es tu poder y tu reino siempre ha de ser.\nBb7                              Eb\n\n[Verso 2]\nEb                    Bb7        Eb\nSe oye el himno celestial de ángeles que en coro te cantan\nAb                    Eb         Bb7\nen concierto musical. Serafines, querubines\nEb                    Ab         Eb\ncantan notas de adoración: Santo, santo es el Señor.\nBb7                              Eb\n\n[Verso 3]\nEb                    Bb7        Eb\nPadre santo, mi Jesús, y el Consolador, Dios trino,\nAb                    Eb         Bb7\ny en esencia uno sois. Te adoramos, Dios bendito,\nEb                    Ab         Eb\ny te damos nuestro amor: a tu nombre, ¡oh Salvador!\nBb7                              Eb\nAmén.`
},
{
 id:1026,bookNumber:26,title:'Castillo Fuerte Es Nuestro Dios',artist:'Martín Lutero · EIN FESTE BURG',type:'himnos',tone:'C',
 content:`[Himno 26]\n\n[Verso 1]\nC                    G7          C\nCastillo fuerte es nuestro Dios, defensa y buen escudo.\nF                    C           G7\nCon su poder nos librará en todo trance agudo.\nC                    F           C\nCon furia y con afán acósanos Satán:\nDm                   G7\npor armas deja ver astucia y gran poder;\nC                    F      G7   C\ncual él no hay en la tierra.\n\n[Verso 2]\nC                    G7          C\nNuestro valor es nada aquí, con él todo es perdido;\nF                    C           G7\nmas con nosotros luchará de Dios el escogido.\nC                    F           C\nEs nuestro Rey Jesús, el que venció en la cruz,\nDm                   G7\nSeñor y Salvador, y siendo él solo Dios,\nC                    F      G7   C\nél triunfa en la batalla.\n\n[Verso 3]\nC                    G7          C\nY si demonios mil están prontos a devorarnos,\nF                    C           G7\nno temeremos, porque Dios sabrá cómo ampararnos.\nC                    F           C\n¡Que muestre su vigor Satán, y su furor!\nDm                   G7\ndañarnos no podrá, pues condenado es ya\nC                    F      G7   C\npor la Palabra Santa.\n\n[Verso 4]\nC                    G7          C\nEsa palabra del Señor, que el mundo no apetece,\nF                    C           G7\npor el Espíritu de Dios muy firme permanece.\nC                    F           C\nNos pueden despojar de bienes, nombre, hogar,\nDm                   G7\nel cuerpo destruir, mas siempre ha de existir\nC                    F      G7   C\nde Dios el Reino eterno. Amén.`
},
{
 id:1027,bookNumber:27,title:'A Dios, Naciones, Dad Loor',artist:'Isaac Watts · GERMANY',type:'himnos',tone:'Ab',
 content:`[Himno 27]\n\n[Verso 1]\nAb                    Eb7         Ab\nA Dios, naciones, dad loor, porque es el único Señor;\nDb                    Ab          Eb7\na él con gozo alabad, y sus bondades celebrad.\nAb                    Db     Eb7  Ab\n\n[Verso 2]\nAb                    Eb7         Ab\nEs infinito su poder; en él tenemos nuestro ser,\nDb                    Ab          Eb7\npues que del polvo nos formó, y de la muerte nos salvó.\nAb                    Db     Eb7  Ab\n\n[Verso 3]\nAb                    Eb7         Ab\nUniversal es tu bondad; será eterna tu verdad;\nDb                    Ab          Eb7\ninagotable es tu amor; ¡Omnipotente Dios, Señor!\nAb                    Db     Eb7  Ab`
}
];
const target=window.LAGREY_SONGS||(window.LAGREY_SONGS=[]);
for(const h of hymns){if(!target.some(s=>s.id===h.id))target.push(h)}
window.LAGREY_HYMNS=[...(window.LAGREY_HYMNS||[]),...hymns.filter(h=>!(window.LAGREY_HYMNS||[]).some(x=>x.id===h.id))];
})();