(()=>{
'use strict';
const hymns=[
{id:1321,bookNumber:321,title:"Satisfecho Estoy",artist:'Himnario Bautista 1976',type:'himnos',tone:"Eb",content:`[Himno 321]\n\nSatisfecho Estoy 321\nPorque sacia al alma menesterosa, y llena de bien al alma hambrienta. Sal. 107 :9\n1. En mi sed siempre he buscado una fuente do beber; y esperaba que esas aguas me calmaran mi honda sed.\n2. En mi hambre yo comía sin mis fuerzas aumentar; lo mejor siempre quería sin poderlo alcanzar.\n3. Pobre fui, y las riquezas yo buscaba con afán; mas el mundo sus tristezas me ofreció en vez de pan.\n4. Fuente viva de agua pura, pan de vida y todo aquí; y riqueza bien segura: Jesucristo es para mí.\n¡Aleluya! Lo he encontrado, Jesús, quien me ama a mí; satisfecho me ha dejado; por su sangre salvo fui.`},
{id:1322,bookNumber:322,title:"Habladme Más de Cristo",artist:'Himnario Bautista 1976',type:'himnos',tone:"Bb",content:`[Himno 322]\n\n[Verso 1]\nQuiero que habléis de aquel gran amor que Dios nos mostró; quiero que habléis del buen Salvador, que en el Calvario vivió tan sólo por él. ¡Habladme más de Cristo!\n\n[Verso 2]\nCuando me asalte la tentación y tienda a mi pie sus redes, quiero tener protección.\n\n[Verso 3]\nCuando en la lucha falte la fe y el alma sienta desfallecer, quiero saber que ayuda tendré.`},
{id:1323,bookNumber:323,title:"En Jesucristo, el Rey de Paz",artist:'Himnario Bautista 1976',type:'himnos',tone:"D",content:`[Himno 323]\n\nEn Jesucristo, el Rey de paz, en horas negras, en el dolor; en tristes horas de tentación, Cristo nos llena de su vigor.\nGrato consuelo, felicidad.\nEn nuestras luchas, llenos de fe y sin querer desfallecer, Cristo nos dice: “Siempre os daré” y da aliento al corazón.\nCuando de tempestad, hallan las almas dulce solaz; gracia divina, santo poder.`},
{id:1324,bookNumber:324,title:"Un Eterno y Grande Amor",artist:'Himnario Bautista 1976',type:'himnos',tone:"D",content:`[Himno 324]\n\n¡Oh qué sueño arrobador! Siento dulce calma y paz.\nPara siempre es su amor; mío es él, no pido más.\nAves con más dulce voz, plantas bellas del vergel me hablan del amor de Dios: suyo soy, y mío es él.\nOjalá que siempre aquí, fiando en este amigo fiel, yo me acuerde que es así: suyo soy, y mío es él.\nCielo y tierra pasarán, mas veré su dulce faz; gozo y luz se acabarán; suyo soy, no pido más.`},
{id:1325,bookNumber:325,title:"Yo Sé a Quien He Creído",artist:'Himnario Bautista 1976',type:'himnos',tone:"Eb",content:`[Himno 325]\n\n[Verso 1]\nNo sé por qué la gracia del Señor me hizo conocer; sé por qué su salvación me dio y salvo soy por él.\n\n[Verso 2]\nNo sé por qué la gracia del Señor en mí por fe se demostró; sé que si sólo creo en él, la paz encontraré.\n\n[Verso 3]\nNo sé por qué el Espíritu de Dios convence de pecar; sé por qué revela al pecador cuán negra es la maldad.\n\n[Verso 4]\nNo sé la hora en que el Señor vendrá; de día o en oscuridad.\n\n[Coro]\nSé a quién he creído, y es poderoso para guardarme; y en ese día glorioso iré a morar con él.`},
{id:1326,bookNumber:326,title:"Escogido Fui de Dios",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 326]\n\nEscogido fui de Dios en el Amado; en lugares celestiales su bendición me dio. Antes de la creación el plan fue hecho por su santa voluntad.\nTengo un sello que el Espíritu me ha dado cuando mi confianza puse sólo en mi Salvador; prenda que el Señor me dio de vida eterna.\nMe escogió para alabanza de su gloria, y sentome en las alturas con Cristo mi Señor. Grande fue mi admiración al ver su gracia cuando me escogió mi Dios.`},
{id:1327,bookNumber:327,title:"Seguridad",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 327]\n\nAun cuando cruja la tierra en temblores, el gran amor de Dios firme está. Su paz ofrece al que sufre dolores.\nY si la paz se mira turbada y grandes cambios infunden temor, Dios siempre permanece inmóvil.\nPoder nos da en los graves peligros; su ayuda es fiel siempre que hay frustración.\nY tus mandatos, oh Dios, conocemos; ven, pues, ayúdanos con tu poder.`},
{id:1328,bookNumber:328,title:"El Profundo Amor de Cristo",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 328]\n\nEl profundo amor de Cristo, sin igual, cual océano; su corriente fluye, cambia, protege a sus hijos.\nEl profundo amor de Cristo, digno es de loor y prez; cuánto ama, siempre ama.\nGran profundo amor de Cristo, bendición, es refugio de descanso.\nSiempre guiando, impulsando; intercede en el cielo. Me levanta hasta la gloria.`},
{id:1329,bookNumber:329,title:"El Rey de Amor Es Mi Pastor",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 329]\n\n[Verso 1]\nEl Rey de amor es mi pastor, su amor es verdadero.\n\n[Verso 2]\nMe lleva al fresco manantial y a buenos pastos guía; su amparo no me faltará, pues yo soy su cordero.\n\n[Verso 3]\nPerverso y necio me aparté por valles peligrosos; no temeré yo ningún mal si mi pastor me cuida.\n\n[Verso 4]\nEn valle oscuro no tendré temor si Dios me guía; me halló, me trajo a su redil en hombros poderosos.\n\n[Verso 5]\nHa puesto mesa para mí, ungióme con aceite; su vara y su cayado son cual luz al alma mía.\n\n[Verso 6]\nMisericordia, gracia y paz tú das al alma mía; mi copa rebosando está. Su amor es mi deleite.`},
{id:1330,bookNumber:330,title:"Alcancé Salvación",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 330]\n\nDe paz inundada mi senda ya esté, al irse la niebla veloz; desciende Jesús con su gran majestad, gloria demos al buen Salvador.\nYa venga la prueba o me tiente Satán, o cubra un mar de aflicción, mi suerte cualquiera que sea, diré: ¡Aleluya! Estoy bien con mi Dios.\nFeliz yo me siento al saber que Jesús comprende mis luchas, mi afán.\nLa fe tornarase en gran realidad; libróme de yugo opresor; quitó mi pecado, clavólo en la cruz, y su sangre vertió en mi favor.\nAlcancé, alcancé salvación.`}
];
const target=window.LAGREY_SONGS||(window.LAGREY_SONGS=[]);for(const h of hymns){if(!target.some(s=>s.id===h.id))target.push(h)}window.LAGREY_HYMNS=[...(window.LAGREY_HYMNS||[]),...hymns.filter(h=>!(window.LAGREY_HYMNS||[]).some(x=>x.id===h.id))];
})();