(()=>{
'use strict';
const hymns=[
{id:1331,bookNumber:331,title:"Todas las Promesas del Señor",artist:'Himnario Bautista 1976',type:'himnos',tone:"Eb",content:`[Himno 331]\n\nTodas las promesas del Señor Jesús son apoyo poderoso de mi fe. Mientras viva aquí cercado de su luz, las promesas que el Señor Jesús ha dado son grandes, grandes y fieles.\nTodas sus promesas para el hombre fiel el Señor en sus bondades cumplirá; y confiado sé que para siempre en él esas promesas guardaré.\nTodas las promesas del Señor serán gozo y fuerza en nuestra vida terrenal; ellas en la dura lid nos sostendrán.`},
{id:1332,bookNumber:332,title:"Confío Yo en Cristo",artist:'Himnario Bautista 1976',type:'himnos',tone:"A",content:`[Himno 332]\n\nConfío yo en Cristo, que en la cruz murió; y por su muerte listo voy a la gloria yo.\nMe cubre tu justicia de plena perfección; delicias infinitas, mi eterna salvación.\nVenir a ti me invitas a disfrutar, Señor, amor celestial. ¡Mi Salvador, mi Dios!`},
{id:1333,bookNumber:333,title:"Cristo, Fiel Te Quiero Ser",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 333]\n\nCristo, fiel te quiero ser, dame el poder, dame el poder; yo contigo quiero andar sin vacilar, sin vacilar.\nCon Jesús yo quiero hablar, sólo con él, sólo con él; paz y gozo yo tendré al serle fiel, al serle fiel.\nDame ardiente corazón, lleno de amor, lleno de amor; y tu Espíritu, Señor, como Guiador.\nCada día quiero cumplir tu voluntad, tu voluntad; y servirte a ti, Señor, en humildad.`},
{id:1334,bookNumber:334,title:"Paz con Dios Busqué Ganarla",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 334]\n\nPaz con Dios busqué ganarla con febril solicitud; las obras meritorias no me dieron paz.\nLleno estaba yo de dudas y temor de morir; mas la paz vino por medio de su cruz.\nAl final, desesperado, dije: “Ya no puedo yo”; hoy del cielo oí respuesta: “Todo hecho ya quedó”.\nDe mis obras despojado, vi la obra de Jesús; ¡oh qué paz Jesús me da!`},
{id:1335,bookNumber:335,title:"Más Blanco Que la Nieve",artist:'Himnario Bautista 1976',type:'himnos',tone:"Eb7",content:`[Himno 335]\n\nYo quiero ser limpio, bendito Jesús; deseo andar en tu luz. Tan sólo en tu sangre mis manchas tú puedes quitar.\nQue en mi alma no pueda lo impuro quedar. Cristo, me ayudas; mi ofrenda te doy.\nCon fe y humildad esta pureza te pido; por tu gracia fui limpiado por fe.\nMás blanco que la nieve seré.`},
{id:1336,bookNumber:336,title:"Yo Te Seguiré",artist:'Himnario Bautista 1976',type:'himnos',tone:"F",content:`[Himno 336]\n\nPuedo oír la voz de Cristo. Yo lo seguiré gozoso. Hoy me llama con ternura; no demoraré.\nÉl me llama a cada hora. Yo le seguiré gozoso. Y el poder de su presencia siempre sentiré.\nÉl me llama cada día. Yo le seguiré gozoso. Él me guía y el camino nunca perderé.\nSiempre, siempre yo te seguiré, Señor; por tus sendas de amor.`},
{id:1337,bookNumber:337,title:"Desde el Cielo Cristo Llama",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 337]\n\nDesde el cielo Cristo llama con benigna voz de amor; al acongojado invita: “Ven y sigue a tu Señor”.\nEn tristezas y alegrías Cristo llama al corazón; que nosotros desde ahora le sirvamos con amor.\nComo buen pastor nos guía nuestro amante Salvador; nos cuida en su rebaño y nos da su protección.\nCristo llama; por su gracia él nos haga oír su voz, ofreciendo paz, consuelo, gozo eterno y redención.`},
{id:1338,bookNumber:338,title:"¡Oh Amor Que Excede a Todos!",artist:'Himnario Bautista 1976',type:'himnos',tone:"C",content:`[Himno 338]\n\n¡Oh amor que excede a todos, don del Padre celestial! Pon corona a tus mercedes y entre nos ven a morar.\n¡Ven, amor, a cada vida, mueve toda inclinación; guárdanos de mal deseo y de andar en tentación!\n¡Oh amor, no te separes de la iglesia terrenal; únela estrechamente con el lazo fraternal!\nTrae a nuestro corazón tu salvación y sostenga nuestra fe. Amén.`},
{id:1339,bookNumber:339,title:"¡Oh Cristo!, Tu Ayuda Quisiera Tener",artist:'Himnario Bautista 1976',type:'himnos',tone:"F",content:`[Himno 339]\n\n¡Oh Cristo!, tu ayuda quisiera tener; tan sólo tú puedes mi vida cambiar.\nEn todas las luchas que cuento, Señor, sólo tu fuerza me puede sostener.\nEl alma que huye del tentador vuelve anhelante a tu amor.\nEn mis noches, contigo hallo la luz y alivio a mis penas al pie de la cruz.`},
{id:1340,bookNumber:340,title:"Salvador, a Ti Me Entrego",artist:'Himnario Bautista 1976',type:'himnos',tone:"D",content:`[Himno 340]\n\nSalvador, a ti me entrego. Mi guiador, mi fortaleza, todo encuentra mi alma en ti.\nOye, Cristo, mi plegaria; yo suplico tu perdón.\nQue tu Espíritu me llene y de ti sienta el poder.\nYo a tu causa me consagro, y tu amor mi amor será.\nYo me entrego a ti, yo me entrego a ti.`}
];
const target=window.LAGREY_SONGS||(window.LAGREY_SONGS=[]);for(const h of hymns){if(!target.some(s=>s.id===h.id))target.push(h)}window.LAGREY_HYMNS=[...(window.LAGREY_HYMNS||[]),...hymns.filter(h=>!(window.LAGREY_HYMNS||[]).some(x=>x.id===h.id))];
})();