(()=>{
'use strict';
const hymns=[
{
 id:1006,bookNumber:6,title:'Que Todo el Mundo Cante al Señor',artist:'George Herbert · ALL THE WORLD',type:'himnos',tone:'D',
 content:`[Himno 6]\n\n[Verso 1]\nD                 Em      D      A7   D\nQue todo el mundo cante al Señor, mi Dios y Rey.\nF#7   Em                  D                    B7\nLos cielos ecos dan, que a todas partes van. La tierra en derredor\nEm              E7 A7       D       D7 G\nproclama su loor; que todo el mundo cante al Señor,\nEm      Em7       D      Em7 D\nmi Dios y Rey.\n\n[Verso 2]\nD                 Em      D      A7   D\nQue todo el mundo cante al Señor, mi Dios y Rey.\nF#7   Em                  D                    B7\nLa iglesia himnos da y nunca cesará; con todo el corazón\nEm              E7 A7       D       D7 G\nle alaben con tesón; que todo el mundo cante al Señor,\nEm      Em7       D      Em7 D\nmi Dios y Rey. Amén.`
},
{
 id:1007,bookNumber:7,title:'Sólo a Ti, Dios y Señor',artist:'Pedro Castro · EASTER HYMN',type:'himnos',tone:'C',
 content:`[Himno 7]\n\n[Verso 1]\nC                 G7       C\nSólo a ti, Dios y Señor, adoramos, adoramos,\nF                  C              G7\ny la gloria y el honor tributamos, tributamos.\nC                 F             C\nSólo a Cristo, nuestra Luz, acudimos, acudimos;\nDm                 G7            C\npor su muerte en la cruz revivimos, revivimos.\n\n[Verso 2]\nC                 G7       C\nUn Espíritu, no más, nos gobierna, nos gobierna,\nF                  C              G7\ny con él, Señor, nos das paz eterna, paz eterna;\nC                 F             C\nÉl es fuego celestial, cuya llama, cuya llama\nDm                 G7            C\nevangelical nos inflama, nos inflama.\n\n[Verso 3]\nC                 G7       C\nDisfrutamos tu favor solamente, solamente\nF                  C              G7\npor Jesús, fuente de amor permanente, permanente;\nC                 F             C\nsólo él nos libertó de la muerte, de la muerte,\nDm                 G7            C\nsólo él se declaró nuestro Fuerte, nuestro Fuerte.\n\n[Verso 4]\nC                 G7       C\nSólo tú, oh Creador, Dios eterno, Dios eterno,\nF                  C              G7\nnos libraste del furor del infierno, del infierno;\nC                 F             C\ny por esto con placer proclamamos, proclamamos\nDm                 G7            C\nque sólo en tu gran poder esperamos, esperamos. Amén.`
},
{
 id:1008,bookNumber:8,title:'Alabad, Oh los Siervos del Señor',artist:'Eduardo Nelson G. · CARPENTER',type:'himnos',tone:'D',
 content:`[Himno 8]\n\n[Verso 1]\nD                    G          D\nAlabad, oh los siervos del Señor, alabad al Señor;\nG                    D               A7\nbendecid el nombre de Dios, bendecid el nombre de Dios,\nD                    G             D\npor siempre y por siempre jamás.\nA7                    D\n¡Alabad al Señor!\n\n[Verso 2]\nD                    G          D\nAlabad, cantad gracias al Señor, a Dios dadle loor;\nG                    D               A7\nsoberano es el Señor, soberano es el Señor,\nD                    G             D\nsu gloria reina en nuestro ser.\nA7                    D\n¡Alabad al Señor!\n\n[Verso 3]\nD                    G          D\nAlabad, honra y gloria dad a él. ¿Quién es como Jehová?\nG                    D               A7\nGrande y potente es Dios, grande y potente es Dios,\nD                    G             D\nes Rey de reyes, Señor y Dios.\nA7                    D\n¡Alabad al Señor!\n\n[Verso 4]\nD                    G          D\nAlabad, oh los siervos del Señor, dadle sumo loor,\nG                    D               A7\nal excelso y bendito Dios, al excelso y bendito Dios;\nD                    G             D\ncantadle con gratitud y amor.\nA7                    D\n¡Alabad al Señor!`
},
{
 id:1009,bookNumber:9,title:'Señor, ¿Quién Entrará?',artist:'Salmo 15 · ADORACIÓN',type:'himnos',tone:'F',
 content:`[Himno 9]\n\n[Verso 1]\nF                         C7        F\nSeñor, ¿quién entrará en tu santuario a adorar?\nBb                       F             C7\nEl de manos limpias y un corazón puro, y sin vanidades,\nF          Bb          F        C7       F\nque sepa amar; el que sepa amar.\n\n[Verso 2]\nF                         C7        F\nSeñor, yo quiero entrar en tu santuario a adorar.\nBb                       F             C7\nDame manos limpias y un corazón puro, y sin vanidades,\nF          Bb          F        C7       F\nenséñame a amar; enséñame a amar.`
},
{
 id:1010,bookNumber:10,title:'Hoy Canto el Gran Poder de Dios',artist:'Isaac Watts · FOREST GREEN',type:'himnos',tone:'F',
 content:`[Himno 10]\n\n[Verso 1]\nF                         Bb          F\nHoy canto el gran poder de Dios; los montes él creó;\nC7                         F\nhabló a los mares con fuerte voz; los cielos extendió.\nF                          Bb             F\nSu mente sabia cantaré; poder al sol le dio.\nC7                                           F\nLas luces de la noche, sé, que él las decretó.\n\n[Verso 2]\nF                         Bb          F\nDe Dios hoy canto la bondad que bienes proveyó,\nC7                         F\npara uso de la infinidad de todo lo que creó.\nF                          Bb             F\nSus maravillas por doquier ¡cuán numerosas son!\nC7                                           F\nMis ojos bien las pueden ver en toda su creación.\n\n[Verso 3]\nF                         Bb          F\nOh Dios, tu gloria, flores mil demuestran por doquier;\nC7                         F\nlos vientos y el turbión hostil declaran tu poder.\nF                          Bb             F\nEn la natura, buen Señor, la vida a todos das;\nC7                                           F\ndoquier que miro alrededor allí presente estás.`
},
{
 id:1011,bookNumber:11,title:'Bendice, Oh Alma, a Tu Creador',artist:'Vicente Mendoza · O THOU MY SOUL, BLESS GOD THE LORD',type:'himnos',tone:'D',
 content:`[Himno 11]\n\n[Verso 1]\nD             G                 D7 G\nBendice, oh alma, a tu Creador con fervida canción;\nD                                  C\ndespierta, y canta su loor tu ardiente corazón.\nG                 Am        D7      G\nBendice, oh alma, a nuestro Rey y Salvador.\n\n[Verso 2]\nD             G                 D7 G\nNo olvides nunca su bondad mostrando ingratitud,\nD                                  C\npues él perdona tu maldad, te salva y da salud.\nG                 Am        D7      G\nBendice, oh alma, a nuestro Rey y Salvador.\n\n[Verso 3]\nD             G                 D7 G\nDe bien tu boca llena está; y nueva juventud\nD                                  C\na tu alma siempre le dará, calmando tu inquietud.\nG                 Am        D7      G\nBendice, oh alma, a nuestro Rey y Salvador.\n\n[Verso 4]\nD             G                 D7 G\nEn ira es lento nuestro Rey, mas pronto es en su amor;\nD                                  C\nno quiere siempre contender ni dura su furor.\nG                 Am        D7      G\nBendice, oh alma, a nuestro Rey y Salvador.`
},
{
 id:1012,bookNumber:12,title:'Dad a Dios Inmortal Alabanza',artist:'José Mora · PUEBLA',type:'himnos',tone:'D',
 content:`[Himno 12]\n\n[Verso 1]\nD                 G        A        D\nDad a Dios inmortal alabanza, su merced, prodigios fecunda;\nA7                                      D\nsus mercedes, humildes, cantad.\nD                        A7\n¡Al Señor de señores dad gloria, Rey de reyes, poder sin segundo!\nD                                             A7 D\nMorirán los señores del mundo, mas su reino no acaba jamás.\n\n[Verso 2]\nD                 G        A        D\nVio los pueblos en vicios sumidos y sintió su conciencia estar llena;\nA7                                      D\nsus mercedes, humildes, cantad.\nD                        A7\nA su pueblo llevó por la mano a la tierra por él prometida.\nD                                             A7 D\nPor los siglos sin fin le da vida; y el pecado y la muerte caerán.\n\n[Verso 3]\nD                 G        A        D\nA su Hijo envió por salvarnos del pecado que es torrente;\nA7                                      D\nsus mercedes, humildes, cantad.\nD                        A7\nPor el mundo su mano nos lleva, y celeste descanso nos guía;\nD                                             A7 D\nsu bondad vivirá eterno día, cuando el mundo no exista ya más.`
},
{
 id:1013,bookNumber:13,title:'Engrandecido Sea Jehová',artist:'Julio Hidalgo · DOXOLOGÍA',type:'himnos',tone:'F',
 content:`[Himno 13]\n\nF       Fmaj7      Dm       Gm    C7\nEngrandecido sea Jehová, nuestro Dios;\nC7                  F      Bb\npor todas las edades, por siempre.\nF        C7       F\nAmén.`
}
];
const target=window.LAGREY_SONGS||(window.LAGREY_SONGS=[]);
for(const h of hymns){if(!target.some(s=>s.id===h.id))target.push(h)}
window.LAGREY_HYMNS=[...(window.LAGREY_HYMNS||[]),...hymns.filter(h=>!(window.LAGREY_HYMNS||[]).some(x=>x.id===h.id))];
})();