(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function ensureHomeOrder(){const grid=$('#home .home-grid');if(!grid)return;const wanted=['songs','hymns','voice','chords','tuner','calendar','favorites'];const current=[...grid.querySelectorAll('[data-open]')].map(x=>x.dataset.open);if(wanted.some((k,i)=>current[i]!==k)){const cards=new Map([...grid.querySelectorAll('[data-open]')].map(x=>[x.dataset.open,x]));wanted.forEach(k=>{const c=cards.get(k);if(c)grid.appendChild(c)})}if(!$('#lg35HomeLabel')){const l=document.createElement('div');l.id='lg35HomeLabel';l.className='lg35-home-label';l.textContent='Explora La Grey';grid.before(l)}}
function ensureSongDrawer(){if($('#lg35SongToolsTab'))return;const tab=document.createElement('button');tab.id='lg35SongToolsTab';tab.type='button';tab.textContent='Herramientas';tab.setAttribute('aria-label','Abrir herramientas de canción');const drawer=document.createElement('aside');drawer.id='lg35SongToolsDrawer';drawer.innerHTML='<button id="lg35SongToolsClose" type="button" aria-label="Cerrar">×</button><h2>Herramientas</h2><p class="lg35-drawer-note">Ajustes de lectura, tono, desplazamiento y favoritos.</p><div id="lg35SongToolsBody"></div>';document.body.append(tab,drawer);tab.onclick=()=>drawer.classList.toggle('open');$('#lg35SongToolsClose').onclick=()=>drawer.classList.remove('open');document.addEventListener('click',e=>{if(drawer.classList.contains('open')&&!e.target.closest('#lg35SongToolsDrawer,#lg35SongToolsTab'))drawer.classList.remove('open')},true)}
function collectSongTools(){ensureSongDrawer();const body=$('#lg35SongToolsBody'),detail=$('#detail');if(!body||!detail)return;const targets=[detail.querySelector('.head>.actions'),$('#readerTools'),$('#hymnTransposeV2')].filter(Boolean);targets.forEach(n=>{if(n.parentElement!==body)body.appendChild(n)});const has=!detail.classList.contains('hidden');document.body.classList.toggle('lg35-song-open',has);if(!has)$('#lg35SongToolsDrawer')?.classList.remove('open')}
function voiceInline(){const view=$('#voiceView');if(!view)return;const mark=(container,selector,panelSel)=>{if(!container||container.dataset.lg35Bound===selector)return;container.dataset.lg35Bound=selector;container.addEventListener('click',e=>{const b=e.target.closest(selector);if(!b)return;const y=window.scrollY;setTimeout(()=>{const p=$(panelSel);if(!p)return;container.querySelectorAll(selector).forEach(x=>x.classList.toggle('lg35-expanded',x===b));b.insertAdjacentElement('afterend',p);p.classList.add('lg35-inline-panel');requestAnimationFrame(()=>window.scrollTo(0,y))},0)},true)};if(!view.dataset.lg35Voice){view.dataset.lg35Voice='1';mark(view,'.voice-routine','#voicePanel');mark(view,'.voice-card','#voicePanel')}const pro=$('#voiceProTools');if(pro&&!pro.dataset.lg35VoicePro){pro.dataset.lg35VoicePro='1';mark(pro,'.voice-pro-card','#voiceProPanel')}}
function observeVoicePro(){const view=$('#voiceView');if(!view)return;const mo=new MutationObserver(()=>voiceInline());mo.observe(view,{childList:true,subtree:true});voiceInline()}
function tunePolish(){const v=$('#tunerView');if(!v||v.dataset.lg35)return;v.dataset.lg35='1';const card=v.querySelector('.tuner-card');if(card&&!card.querySelector('.lg35-tuner-kicker')){const k=document.createElement('div');k.className='lg35-tuner-kicker';k.textContent='AFINACIÓN EN TIEMPO REAL';k.style.cssText='color:#f3c969;font-size:11px;font-weight:900;letter-spacing:.12em;margin-bottom:10px';card.prepend(k)}}
function updateViews(){const detail=$('#detail');document.body.classList.toggle('lg35-song-open',!!detail&&!detail.classList.contains('hidden'));if(detail?.classList.contains('hidden'))$('#lg35SongToolsDrawer')?.classList.remove('open');collectSongTools()}
function init(){ensureHomeOrder();ensureSongDrawer();observeVoicePro();tunePolish();collectSongTools();const detail=$('#detail');if(detail)new MutationObserver(updateViews).observe(detail,{attributes:true,attributeFilter:['class']});const head=$('#detail .head');if(head)new MutationObserver(()=>collectSongTools()).observe(head,{childList:true,subtree:true});setInterval(()=>{voiceInline();collectSongTools()},1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
