(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STANDARD=['home','listing','detail','chordsView','tunerView','calendarView','setlistView'];
function ensureHomeOrder(){const grid=$('#home .home-grid');if(!grid)return;const wanted=['songs','hymns','voice','chords','tuner','calendar','favorites'];const cards=new Map([...grid.querySelectorAll('[data-open]')].map(x=>[x.dataset.open,x]));const current=[...grid.querySelectorAll('[data-open]')].map(x=>x.dataset.open);if(current.join('|')!==wanted.filter(k=>cards.has(k)).join('|'))wanted.forEach(k=>{const c=cards.get(k);if(c)grid.appendChild(c)});if(!$('#lg35HomeLabel')){const l=document.createElement('div');l.id='lg35HomeLabel';l.className='lg35-home-label';l.textContent='Explora La Grey';grid.before(l)}}
function ensureSongDrawer(){if($('#lg35SongToolsTab'))return;const tab=document.createElement('button');tab.id='lg35SongToolsTab';tab.type='button';tab.textContent='⋮';tab.setAttribute('aria-label','Abrir herramientas de canción');tab.setAttribute('title','Herramientas');const drawer=document.createElement('aside');drawer.id='lg35SongToolsDrawer';drawer.innerHTML='<button id="lg35SongToolsClose" type="button" aria-label="Cerrar">×</button><h2>Herramientas</h2><p class="lg35-drawer-note">Ajustes de lectura, tono, desplazamiento y favoritos.</p><div id="lg35SongToolsBody"></div>';($('#detail')||document.body).appendChild(tab);document.body.appendChild(drawer);tab.onclick=()=>drawer.classList.toggle('open');$('#lg35SongToolsClose').onclick=()=>drawer.classList.remove('open');document.addEventListener('click',e=>{if(drawer.classList.contains('open')&&!e.target.closest('#lg35SongToolsDrawer,#lg35SongToolsTab'))drawer.classList.remove('open')},true)}
function collectSongTools(){ensureSongDrawer();const body=$('#lg35SongToolsBody'),detail=$('#detail');if(!body||!detail)return;const targets=[detail.querySelector('.head>.actions'),$('#readerTools'),$('#hymnTransposeV2')].filter(Boolean);targets.forEach(n=>{if(n.parentElement!==body)body.appendChild(n)});const has=!detail.classList.contains('hidden');document.body.classList.toggle('lg35-song-open',has);if(!has)$('#lg35SongToolsDrawer')?.classList.remove('open')}
function voiceInline(){const view=$('#voiceView');if(!view)return;const mark=(container,selector,panelSel)=>{if(!container||container.dataset.lg35Inline==='1')return;container.dataset.lg35Inline='1';container.addEventListener('click',e=>{const b=e.target.closest(selector);if(!b)return;const y=window.scrollY;setTimeout(()=>{const p=$(panelSel);if(!p)return;container.querySelectorAll(selector).forEach(x=>x.classList.toggle('lg35-expanded',x===b));b.insertAdjacentElement('afterend',p);p.classList.add('lg35-inline-panel');requestAnimationFrame(()=>window.scrollTo(0,y));},0)},true)};mark(view,'.voice-routine','#voicePanel');mark(view,'.voice-card','#voicePanel');const pro=$('#voiceProTools');mark(pro,'.voice-pro-card','#voiceProPanel')}
function observeVoicePro(){const view=$('#voiceView');if(!view)return;new MutationObserver(()=>voiceInline()).observe(view,{childList:true,subtree:true});voiceInline()}
function tunePolish(){const v=$('#tunerView');if(!v||v.dataset.lg35)return;v.dataset.lg35='1';const card=v.querySelector('.tuner-card');if(card&&!card.querySelector('.lg35-tuner-kicker')){const k=document.createElement('div');k.className='lg35-tuner-kicker';k.textContent='AFINACIÓN EN TIEMPO REAL';k.style.cssText='color:#f3c969;font-size:11px;font-weight:900;letter-spacing:.12em;margin-bottom:10px';card.prepend(k)}}
function isolateViews(){const voice=$('#voiceView');const visibleStd=STANDARD.map(id=>$('#'+id)).filter(v=>v&&!v.classList.contains('hidden'));if(visibleStd.length){if(voice&&!voice.classList.contains('hidden'))voice.classList.add('hidden');$$('#voiceFab,#voiceFabMenu').forEach(x=>{x.style.display='none';x.classList.remove('open')})}if(visibleStd.length>1){const keep=visibleStd[visibleStd.length-1];visibleStd.forEach(v=>{if(v!==keep)v.classList.add('hidden')})}}
function navIsolation(){document.addEventListener('click',e=>{const a=e.target.closest('[data-open],[data-nav],[data-home],#songBackBtn,#setlistBack,[data-voice-home]');if(!a)return;const dest=a.dataset.open||a.dataset.nav||'';if(dest!=='voice'){$('#voiceView')?.classList.add('hidden');$$('#voiceFab,#voiceFabMenu').forEach(x=>{x.style.display='none';x.classList.remove('open')})}setTimeout(isolateViews,0)},true)}
function updateViews(){const detail=$('#detail');document.body.classList.toggle('lg35-song-open',!!detail&&!detail.classList.contains('hidden'));if(detail?.classList.contains('hidden'))$('#lg35SongToolsDrawer')?.classList.remove('open');collectSongTools();isolateViews()}
function init(){ensureHomeOrder();ensureSongDrawer();navIsolation();observeVoicePro();tunePolish();collectSongTools();const main=$('main');if(main)new MutationObserver(()=>{isolateViews();voiceInline()}).observe(main,{subtree:true,attributes:true,attributeFilter:['class']});const detail=$('#detail');if(detail)new MutationObserver(updateViews).observe(detail,{attributes:true,attributeFilter:['class']});const head=$('#detail .head');if(head)new MutationObserver(()=>collectSongTools()).observe(head,{childList:true,subtree:true});setInterval(()=>{voiceInline();collectSongTools();isolateViews()},1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
