(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STANDARD=['home','listing','detail','chordsView','tunerView','calendarView','setlistView'];
function ensureHomeOrder(){const grid=$('#home .home-grid');if(!grid)return;const wanted=['songs','hymns','voice','chords','tuner','calendar','favorites'];const cards=new Map([...grid.querySelectorAll('[data-open]')].map(x=>[x.dataset.open,x]));const current=[...grid.querySelectorAll('[data-open]')].map(x=>x.dataset.open);if(current.join('|')!==wanted.filter(k=>cards.has(k)).join('|'))wanted.forEach(k=>{const c=cards.get(k);if(c)grid.appendChild(c)});if(!$('#lg35HomeLabel')){const l=document.createElement('div');l.id='lg35HomeLabel';l.className='lg35-home-label';l.textContent='Explora La Grey';grid.before(l)}}
function proxyButton(id,icon,label,target){const b=document.createElement('button');b.id=id;b.className='lg38-tool';b.type='button';b.textContent=icon;b.title=label;b.setAttribute('aria-label',label);b.onclick=e=>{e.stopPropagation();const t=$(target);if(t)t.click()};return b}
function ensureSongDrawer(){if($('#lg35SongToolsTab'))return;const detail=$('#detail');if(!detail)return;const tab=document.createElement('button');tab.id='lg35SongToolsTab';tab.type='button';tab.textContent='⋮';tab.setAttribute('aria-label','Abrir herramientas de canción');tab.setAttribute('title','Herramientas');const drawer=document.createElement('aside');drawer.id='lg35SongToolsDrawer';drawer.setAttribute('aria-label','Herramientas de canción');const strip=document.createElement('div');strip.id='lg38ToolStrip';strip.className='lg38-tool-strip';strip.append(
 proxyButton('lg38Rotate','↻','Rotar pantalla','#lg38RotateTarget'),
 proxyButton('lg38ToneDown','½−','Bajar medio tono','#hymnDownV2'),
 proxyButton('lg38ToneUp','½+','Subir medio tono','#hymnUpV2'),
 proxyButton('lg38ToneReset','↺','Restablecer tono','#hymnResetV2'),
 proxyButton('lg38ToneSave','★','Guardar tono predeterminado','#hymnSaveV2'),
 proxyButton('lg38Fav','♡','Favorito','#favBtn'),
 proxyButton('lg38FontDown','A−','Reducir letra','#fontDown'),
 proxyButton('lg38FontUp','A+','Aumentar letra','#fontUp')
 );
 const scrollBtn=document.createElement('button');scrollBtn.id='lg38Scroll';scrollBtn.className='lg38-tool';scrollBtn.type='button';scrollBtn.textContent='▶';scrollBtn.title='Auto-scroll';scrollBtn.setAttribute('aria-label','Auto-scroll');scrollBtn.onclick=e=>{e.stopPropagation();toggleScrollPopup()};strip.append(scrollBtn,
 proxyButton('lg38Fit','↔','Ajustar al ancho','#readerFit'),
 proxyButton('lg38Top','⇡','Volver al inicio de la letra','#readerReset')
 );
 const rotateTarget=document.createElement('button');rotateTarget.id='lg38RotateTarget';rotateTarget.type='button';rotateTarget.hidden=true;rotateTarget.onclick=toggleLandscape;
 const popup=document.createElement('div');popup.id='lg40ScrollPopup';popup.innerHTML='<button id="lg40ScrollToggle" type="button" aria-label="Iniciar o pausar auto-scroll">▶</button><input id="lg40ScrollSpeed" type="range" min="1" max="100" step="1" value="32" aria-label="Velocidad de auto-scroll"><span id="lg40ScrollValue">32%</span>';
 drawer.append(strip,rotateTarget,popup);detail.appendChild(tab);detail.appendChild(drawer);
 tab.onclick=e=>{e.stopPropagation();const opening=!drawer.classList.contains('open');drawer.classList.toggle('open',opening);if(!opening)popup.classList.remove('open')};
 wireScrollPopup()}
function wireScrollPopup(){const slider=$('#lg40ScrollSpeed'),value=$('#lg40ScrollValue'),toggle=$('#lg40ScrollToggle');if(!slider||slider.dataset.wired)return;slider.dataset.wired='1';const source=$('#readerSpeed');if(source)slider.value=source.value;value.textContent=slider.value+'%';slider.addEventListener('input',()=>{const r=$('#readerSpeed');if(r){r.value=slider.value;r.dispatchEvent(new Event('input',{bubbles:true}))}value.textContent=slider.value+'%'});toggle.onclick=e=>{e.stopPropagation();$('#readerPlay')?.click();setTimeout(syncSongToolbar,20)}}
function toggleScrollPopup(){const p=$('#lg40ScrollPopup');if(!p)return;const source=$('#readerSpeed');if(source){$('#lg40ScrollSpeed').value=source.value;$('#lg40ScrollValue').textContent=source.value+'%'}p.classList.toggle('open')}
async function toggleLandscape(){const b=$('#lg38Rotate');try{if(screen.orientation?.type?.startsWith('landscape')){screen.orientation.unlock?.();if(document.fullscreenElement)await document.exitFullscreen?.();b?.classList.remove('active');return}if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();if(screen.orientation?.lock){await screen.orientation.lock('landscape');b?.classList.add('active')}}catch(e){b?.classList.toggle('active',screen.orientation?.type?.startsWith('landscape'))}}
function closeSongTools(){const drawer=$('#lg35SongToolsDrawer');drawer?.classList.remove('open');$('#lg40ScrollPopup')?.classList.remove('open')}
function collectSongTools(){ensureSongDrawer();const detail=$('#detail');if(!detail)return;const has=!detail.classList.contains('hidden');document.body.classList.toggle('lg35-song-open',has);if(!has)closeSongTools();syncSongToolbar()}
function syncSongToolbar(){const hymn=!!$('#hymnTransposeV2');['#lg38ToneDown','#lg38ToneUp','#lg38ToneReset','#lg38ToneSave'].forEach(s=>$(s)?.classList.toggle('hidden-tool',!hymn));const fav=$('#favBtn')?.textContent||'';if($('#lg38Fav'))$('#lg38Fav').textContent=fav.includes('★')?'♥':'♡';const play=$('#readerPlay')?.textContent||'';const running=play.includes('Pausar');if($('#lg38Scroll'))$('#lg38Scroll').textContent=running?'⏸':'▶';if($('#lg40ScrollToggle'))$('#lg40ScrollToggle').textContent=running?'⏸':'▶';const rs=$('#readerSpeed');if(rs&&$('#lg40ScrollSpeed')&&document.activeElement!==$('#lg40ScrollSpeed')){$('#lg40ScrollSpeed').value=rs.value;$('#lg40ScrollValue').textContent=rs.value+'%'}}
function voiceInline(){const view=$('#voiceView');if(!view)return;const mark=(container,selector,panelSel)=>{if(!container||container.dataset.lg35Inline==='1')return;container.dataset.lg35Inline='1';container.addEventListener('click',e=>{const b=e.target.closest(selector);if(!b)return;const y=window.scrollY;setTimeout(()=>{const p=$(panelSel);if(!p)return;container.querySelectorAll(selector).forEach(x=>x.classList.toggle('lg35-expanded',x===b));b.insertAdjacentElement('afterend',p);p.classList.add('lg35-inline-panel');requestAnimationFrame(()=>window.scrollTo(0,y));},0)},true)};mark(view,'.voice-routine','#voicePanel');mark(view,'.voice-card','#voicePanel');const pro=$('#voiceProTools');mark(pro,'.voice-pro-card','#voiceProPanel')}
function observeVoicePro(){const view=$('#voiceView');if(!view)return;new MutationObserver(()=>voiceInline()).observe(view,{childList:true,subtree:true});voiceInline()}
function tunePolish(){const v=$('#tunerView');if(!v||v.dataset.lg35)return;v.dataset.lg35='1';const card=v.querySelector('.tuner-card');if(card&&!card.querySelector('.lg35-tuner-kicker')){const k=document.createElement('div');k.className='lg35-tuner-kicker';k.textContent='AFINACIÓN EN TIEMPO REAL';k.style.cssText='color:#f3c969;font-size:11px;font-weight:900;letter-spacing:.12em;margin-bottom:10px';card.prepend(k)}}
function isolateViews(){const voice=$('#voiceView');const visibleStd=STANDARD.map(id=>$('#'+id)).filter(v=>v&&!v.classList.contains('hidden'));if(visibleStd.length){if(voice&&!voice.classList.contains('hidden'))voice.classList.add('hidden');$$('#voiceFab,#voiceFabMenu').forEach(x=>{x.style.display='none';x.classList.remove('open')})}if(visibleStd.length>1){const keep=visibleStd[visibleStd.length-1];visibleStd.forEach(v=>{if(v!==keep)v.classList.add('hidden')})}}
function navIsolation(){document.addEventListener('click',e=>{const a=e.target.closest('[data-open],[data-nav],[data-home],#songBackBtn,#setlistBack,[data-voice-home]');if(!a)return;const dest=a.dataset.open||a.dataset.nav||'';if(dest!=='voice'){$('#voiceView')?.classList.add('hidden');$$('#voiceFab,#voiceFabMenu').forEach(x=>{x.style.display='none';x.classList.remove('open')})}if(!a.closest('#detail')||a.matches('#songBackBtn'))closeSongTools();setTimeout(isolateViews,0)},true)}
function updateViews(){const detail=$('#detail');document.body.classList.toggle('lg35-song-open',!!detail&&!detail.classList.contains('hidden'));if(detail?.classList.contains('hidden'))closeSongTools();collectSongTools();isolateViews()}
function init(){ensureHomeOrder();ensureSongDrawer();navIsolation();observeVoicePro();tunePolish();collectSongTools();const main=$('main');if(main)new MutationObserver(()=>{isolateViews();voiceInline();syncSongToolbar()}).observe(main,{subtree:true,attributes:true,attributeFilter:['class']});const detail=$('#detail');if(detail)new MutationObserver(updateViews).observe(detail,{attributes:true,attributeFilter:['class']});const head=$('#detail .head');if(head)new MutationObserver(()=>{collectSongTools();syncSongToolbar();wireScrollPopup()}).observe(head,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('#favBtn,#readerPlay,#hymnDownV2,#hymnUpV2,#hymnResetV2,#hymnSaveV2'))setTimeout(syncSongToolbar,30)},true);setInterval(()=>{voiceInline();collectSongTools();isolateViews()},1400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
