(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function loadCss(){if($('#lgRedesignCss'))return;const l=document.createElement('link');l.id='lgRedesignCss';l.rel='stylesheet';l.href='redesign.css?v=34';document.head.appendChild(l)}
function makeFold(icon,title,desc){const fold=document.createElement('div');fold.className='lg-fold';fold.innerHTML=`<button type="button"><span class="lg-fold-icon">${icon}</span><span class="lg-fold-copy"><b>${title}</b><small>${desc}</small></span><span class="lg-chevron">›</span></button><div class="lg-fold-body"></div>`;fold.querySelector('button').onclick=()=>{const shell=fold.parentElement;shell?.querySelectorAll(':scope > .lg-fold.open').forEach(x=>{if(x!==fold)x.classList.remove('open')});fold.classList.toggle('open')};return fold}
function homePolish(){const h=$('#home');if(!h||h.dataset.lgCompact)return;h.dataset.lgCompact='1';const grid=h.querySelector('.home-grid');if(!grid)return;
 const hero=document.createElement('div');hero.className='lg-home-hero';hero.innerHTML='<div><span class="lg-kicker">LA GREY</span><h1>Tu centro de alabanza</h1><p>Entra solo a lo que necesitas. Lo demás queda recogido.</p></div>';
 grid.before(hero);
 const primary=document.createElement('div');primary.className='lg-home-primary';
 const secondary=makeFold('✨','Más herramientas','Acordes, afinador y favoritos');secondary.classList.add('lg-home-tools');
 grid.before(primary,secondary);const secBody=secondary.querySelector('.lg-fold-body');
 const move=()=>{const cards=[...grid.querySelectorAll(':scope > .card')];cards.forEach(c=>{const k=c.dataset.open;if(['songs','hymns','voice','calendar'].includes(k))primary.appendChild(c);else secBody.appendChild(c)});if(grid.children.length===0)grid.remove()};
 move();let tries=0;const id=setInterval(()=>{tries++;move();if(primary.querySelector('[data-open="voice"]')||tries>25)clearInterval(id)},160)}
function compactCalendar(){const v=$('#calendarView');if(!v||v.dataset.lgCompact)return;v.dataset.lgCompact='1';const actions=v.querySelector('.calendar-actions'),hint=v.querySelector('.hint');if(actions){const d=document.createElement('details');d.className='lg-secondary-tools';d.innerHTML='<summary>Más opciones del calendario</summary><div class="lg-details-body"></div>';const body=d.querySelector('.lg-details-body');actions.before(d);body.appendChild(actions);if(hint)body.appendChild(hint)}}
function compactTuner(){const v=$('#tunerView');if(!v||v.dataset.lgCompact)return;v.dataset.lgCompact='1';const info=v.querySelector('.info-card');if(info){const d=document.createElement('details');d.className='lg-secondary-tools';d.innerHTML='<summary>Referencia de afinación</summary><div class="lg-details-body"></div>';info.before(d);d.querySelector('.lg-details-body').appendChild(info)}}
function compactChords(){const v=$('#chordsView');if(!v||v.dataset.lgCompact)return;v.dataset.lgCompact='1';const roots=$('#rootFilters');if(roots&&!roots.closest('.lg-fold')){const fold=makeFold('🎛️','Filtros por nota','Abre solo cuando quieras limitar la biblioteca');roots.before(fold);fold.querySelector('.lg-fold-body').appendChild(roots)}}
function enhanceListing(){const v=$('#listing');if(!v||v.dataset.lgCompact)return;v.dataset.lgCompact='1';const title=$('#listTitle');if(title){const bar=document.createElement('div');bar.className='lg-list-head';bar.innerHTML='<p class="muted lg-list-sub">Toca un título para abrirlo.</p>';title.after(bar)}}
function compactDetail(){const v=$('#detail');if(!v||v.dataset.lgCompact)return;v.dataset.lgCompact='1';const actions=v.querySelector('.actions');if(actions&&!actions.closest('.lg-detail-tools')){const wrap=document.createElement('div');wrap.className='lg-detail-tools';const t=document.createElement('button');t.type='button';t.className='lg-detail-toggle';t.innerHTML='<span>⚙️ Controles</span><b>＋</b>';actions.before(wrap);wrap.append(t,actions);t.onclick=()=>wrap.classList.toggle('open')}}
function fab(){if($('#lgGlobalFab'))return;const b=document.createElement('button');b.id='lgGlobalFab';b.className='lg-global-fab';b.type='button';b.setAttribute('aria-label','Acciones rápidas');b.textContent='＋';const m=document.createElement('div');m.id='lgGlobalMenu';m.className='lg-global-menu';m.innerHTML='<button data-lg-act="home"><b>⌂ Inicio</b><br><small>Volver a la portada</small></button><button data-lg-act="top"><b>↑ Arriba</b><br><small>Ir al comienzo</small></button><button data-lg-act="search"><b>🔎 Buscar</b><br><small>Abrir buscador principal</small></button>';document.body.append(m,b);b.onclick=()=>m.classList.toggle('open');m.onclick=e=>{const a=e.target.closest('[data-lg-act]');if(!a)return;m.classList.remove('open');if(a.dataset.lgAct==='top')window.scrollTo({top:0,behavior:'smooth'});if(a.dataset.lgAct==='home'){document.querySelector('[data-nav="home"]')?.click()||document.querySelector('[data-home]')?.click()}if(a.dataset.lgAct==='search'){document.querySelector('[data-nav="home"]')?.click()||document.querySelector('[data-home]')?.click();setTimeout(()=>$('#q')?.focus(),180)}};document.addEventListener('click',e=>{if(!e.target.closest('#lgGlobalFab,#lgGlobalMenu'))m.classList.remove('open')},true);updateFab()}
function updateFab(){const b=$('#lgGlobalFab');if(!b)return;const home=$('#home'),detail=$('#detail'),voice=$('#voiceView');const show=home?.classList.contains('hidden');const voiceOpen=voice&&!voice.classList.contains('hidden');b.classList.toggle('show',!!show&&!voiceOpen&&!detail?.classList.contains('hidden'))}
function run(){loadCss();document.body.classList.add('lg-redesign');homePolish();compactChords();compactTuner();compactCalendar();enhanceListing();compactDetail();fab();updateFab()}
const mo=new MutationObserver(()=>{compactChords();compactTuner();compactCalendar();enhanceListing();compactDetail();updateFab()});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{run();mo.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']})});else{run();mo.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']})}
})();
