(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function loadCss(){if($('#lgRedesignCss'))return;const l=document.createElement('link');l.id='lgRedesignCss';l.rel='stylesheet';l.href='redesign.css';document.head.appendChild(l)}
function compactCalendar(){const v=$('#calendarView');if(!v||v.dataset.lgCompact)return;v.dataset.lgCompact='1';const actions=v.querySelector('.calendar-actions'),hint=v.querySelector('.hint');if(actions){const d=document.createElement('details');d.className='lg-secondary-tools';d.innerHTML='<summary>Más opciones del calendario</summary><div class="lg-details-body"></div>';const body=d.querySelector('.lg-details-body');actions.before(d);body.appendChild(actions);if(hint)body.appendChild(hint)}}
function compactTuner(){const v=$('#tunerView');if(!v||v.dataset.lgCompact)return;v.dataset.lgCompact='1';const info=v.querySelector('.info-card');if(info){const d=document.createElement('details');d.className='lg-secondary-tools';d.innerHTML='<summary>Referencia de afinación</summary><div class="lg-details-body"></div>';info.before(d);d.querySelector('.lg-details-body').appendChild(info)}}
function compactChords(){const v=$('#chordsView');if(!v||v.dataset.lgCompact)return;v.dataset.lgCompact='1';const roots=$('#rootFilters');if(roots){const fold=document.createElement('div');fold.className='lg-fold';fold.innerHTML='<button type="button"><span class="lg-fold-icon">🎛️</span><span class="lg-fold-copy"><b>Filtros por nota</b><small>Abre solo cuando quieras limitar la biblioteca</small></span><span class="lg-chevron">›</span></button><div class="lg-fold-body"></div>';roots.before(fold);fold.querySelector('.lg-fold-body').appendChild(roots);fold.querySelector('button').onclick=()=>fold.classList.toggle('open')}}
function enhanceListing(){const v=$('#listing');if(!v||v.dataset.lgCompact)return;v.dataset.lgCompact='1';const title=$('#listTitle');if(title){const sub=document.createElement('p');sub.className='muted lg-list-sub';sub.textContent='Toca un título para abrirlo. Mantén la pantalla limpia y entra solo a lo que necesitas.';title.after(sub)}}
function fab(){if($('#lgGlobalFab'))return;const b=document.createElement('button');b.id='lgGlobalFab';b.className='lg-global-fab';b.type='button';b.setAttribute('aria-label','Acciones rápidas');b.textContent='＋';const m=document.createElement('div');m.id='lgGlobalMenu';m.className='lg-global-menu';m.innerHTML='<button data-lg-act="home"><b>⌂ Inicio</b><br><small>Volver a la portada</small></button><button data-lg-act="top"><b>↑ Arriba</b><br><small>Ir al comienzo de esta pantalla</small></button><button data-lg-act="search"><b>🔎 Buscar</b><br><small>Volver al buscador principal</small></button>';document.body.append(m,b);b.onclick=()=>m.classList.toggle('open');m.onclick=e=>{const a=e.target.closest('[data-lg-act]');if(!a)return;m.classList.remove('open');if(a.dataset.lgAct==='top')window.scrollTo({top:0,behavior:'smooth'});if(a.dataset.lgAct==='home'){document.querySelector('[data-nav="home"]')?.click()||document.querySelector('[data-home]')?.click()}if(a.dataset.lgAct==='search'){document.querySelector('[data-nav="home"]')?.click()||document.querySelector('[data-home]')?.click();setTimeout(()=>$('#q')?.focus(),180)}};
 document.addEventListener('click',e=>{if(!e.target.closest('#lgGlobalFab,#lgGlobalMenu'))m.classList.remove('open')},true);updateFab()}
function updateFab(){const b=$('#lgGlobalFab');if(!b)return;const home=$('#home'),detail=$('#detail'),voice=$('#voiceView');const show=home?.classList.contains('hidden')&&!detail?.classList.contains('hidden')?false:home?.classList.contains('hidden');const voiceOpen=voice&&!voice.classList.contains('hidden');b.classList.toggle('show',!!show&&!voiceOpen&&!detail?.classList.contains('hidden'))}
function homePolish(){const h=$('#home');if(!h||h.dataset.lgCompact)return;h.dataset.lgCompact='1';const grid=h.querySelector('.home-grid');if(grid){[...grid.children].forEach((c,i)=>c.style.setProperty('--lg-order',i))}}
function run(){loadCss();document.body.classList.add('lg-redesign');homePolish();compactChords();compactTuner();compactCalendar();enhanceListing();fab();updateFab()}
const mo=new MutationObserver(()=>{compactChords();compactTuner();compactCalendar();enhanceListing();updateFab()});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{run();mo.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']})});else{run();mo.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']})}
})();