window.LAGREY_SONGS_V2 = [
  {
    "id": 1,
    "title": "Cuán Grande Es Dios",
    "artist": "En Espíritu y en Verdad",
    "type": "cantos",
    "tone": "G",
    "content": "[Intro] G\n\n[Primeira Parte]\n\n   G                   D/F#\n\nEl esplendor de un Rey\n\n    Em\n\nVestido en majestad\n\n                    C\n\nLa Tierra alegre está\n\n                    D\n\nLa Tierra alegre está\n\n    G                D/F#\n\nCubierto está de luz\n\n     Em\n\nVenció a la oscuridad\n\n                C\n\nY tiembla a su voz\n\n              D\n\nTiembla a su voz\n\n[Refrão]\n\n       G\n\nCuán grande es Dios\n\n      D/F#       Em\n\nCántale, cuán grande es Dios\n\n              C\n\nY todos lo verán\n\n       D         G\n\nCuán grande es Dios\n\n[Primeira Parte]\n\n   G                   D/F#\n\nEl esplendor de un Rey\n\n    Em\n\nVestido en majestad\n\n                    C\n\nLa Tierra alegre está\n\n                    D\n\nLa Tierra alegre está\n\n    G                D/F#\n\nCubierto está de luz\n\n     Em\n\nVenció a la oscuridad\n\n                C\n\nY tiembla a su voz\n\n              D\n\nTiembla a su voz\n\n[Refrão]\n\n       G\n\nCuán grande es Dios\n\n      D/F#       Em\n\nCántale, cuán grande es Dios\n\n              C\n\nY todos lo verán\n\n       D         G\n\nCuán grande es Dios\n\n       G\n\nCuán grande es Dios\n\n      D/F#       Em\n\nCántale, cuán grande es Dios\n\n              C\n\nY todos lo verán\n\n       D         G\n\nCuán grande es Dios\n\n[Segunda Parte]\n\n G                D/F#\n\nDía a día El está\n\n       Em\n\nY el tiempo está en El\n\n                C\n\nPrincipio y el fin\n\n                D\n\nPrincipio y el fin\n\n     G              D/F#\n\nLa Trinidad en Dios\n\n    Em\n\nEl Padre, Hijo, Espíritu\n\n               C\n\nCordero y el León\n\n               D\n\nCordero y el León\n\n[Refrão]\n\n       G\n\nCuán grande es Dios\n\n      D/F#       Em\n\nCántale, cuán grande es Dios\n\n              C\n\nY todos lo verán\n\n       D         G\n\nCuán grande es Dios\n\n       G\n\nCuán grande es Dios\n\n      D/F#       Em\n\nCántale, cuán grande es Dios\n\n              C\n\nY todos lo verán\n\n       D         G\n\nCuán grande es Dios\n\n[Terceira Parte]\n\n              G\n\nTu Nombre sobre todo es\n\nD/F#   Em\n\nEres digno de alabar\n\n      C\n\nY mi ser dirá\n\n       D        G\n\nCuan grande es Dios\n\n              G\n\nTu Nombre sobre todo es\n\nD/F#   Em\n\nEres Digno de alabar\n\n      C\n\nY mi ser dirá\n\n       D        G\n\nCuan grande es Dios\n\n[Refrão]\n\n       G\n\nCuán grande es Dios\n\n      D/F#       Em\n\nCántale, cuán grande es Dios\n\n              C\n\nY todos lo verán\n\n       D         G\n\nCuán grande es Dios\n\n       G\n\nCuán grande es Dios\n\n      D/F#       Em\n\nCántale, cuán grande es Dios\n\n              C\n\nY todos lo verán\n\n       D         G\n\nCuán grande es Dios\n\n       G\n\nCuán grande es Dios\n\n      D/F#       Em\n\nCántale, cuán grande es Dios\n\n              C\n\nY todos lo verán\n\n       D         G\n\nCuán grande es Dios"
  },
  {
    "id": 2,
    "title": "El amor de Cristo",
    "artist": "Adoración La IBI",
    "type": "cantos",
    "tone": "A",
    "content": "Intro: //D - F#m - Esus4 E //\n\n1ºVerso:\n\n                        A      E\n\nProfundo es el Amor de Cristo,    más que el infierno y la\n\n   F#m\n\nmaldad\n\n                    D       F#m                   E\n\nDejó su trono y su gloria       para traernos hacia Él\n\n                         D      F#m                        Bm\n\nMás ancho es el amor de Cristo,     que el foso que nos separó\n\nD                      F#m    E                   A\n\n  Me alcanzó en mis tinieblas,   solo en Él hay Salvación\n\nCoro:\n\nD                    A     F#m                  E\n\nMás profundo que el mar,   más allá del cielo está\n\n     D     F#m     E\n\nTu amor me bastará\n\n2ºVerso:\n\n                          A     E                      F#m\n\nMás fuerte es el amor de Cristo    que mi enemigo más feroz\n\n                     D    F#m                      E\n\nMe sostiene en la tormenta    las aguas no me cubrirán\n\n                     D      F#m                        Bm\n\nMe guiará el amor de Cristo,     en el más hondo valle aquí\n\nD                  F#m     E                A\n\n Me pastoreará por siempre   y me guarda junto a Él\n\nCoro:\n\nD                    A     F#m                  E\n\nMás profundo que el mar,   más allá del cielo está\n\n    D     F#m      E\n\nTu amor me bastará\n\n     D                  A\n\nMás fuerte que la tempestad\n\n    F#m                  E\n\nVenció al pecado y la maldad\n\n     D    F#m      E\n\nTu amor me bastará\n\n\n\nIntro: D - F#m - Esus4 E\n\n\n\n3ºVerso:\n\n                         A     E\n\nMás dulce es el amor de Cristo    mientras más cerca estoy del\n\nF#m\n\n fin\n\n                        D      F#m                 E\n\nDisfrutaré se amor por siempre,    ante su trono estaré\n\n                       D      F#m                    Bm\n\nMe llenará el amor de Cristo,    al su rostro contemplar\n\nD                 F#m      E                A\n\n  Yo le amaré por siempre,    Su alabanza cantaré\n\nAsus               A\n\n ///Su alabanza cantaré ///"
  },
  {
    "id": 3,
    "title": "Nombre sobre todo",
    "artist": "Sovereign Grace Music",
    "type": "cantos",
    "tone": "C",
    "content": "INTRO: D | Dsus | D | Dsus [x2]\n\n\n\nVERSO 1:\n\nC  Csus C           G           Am     F\n\nAlfa, Omega, Él que era, es y quien vendrá\n\n       C Csus  C            G          Am    F\n\nQuien vive  y  reina, y el cielo adora sin cesar\n\n   Am7     Fmaj9     C/E   G/B\n\nTu nombre y gloria es la canción\n\n      Am7    Fmaj9  C       Gsus  G\n\nQue rodea el trono hoy, se escu - cha:\n\n\n\nCORO\n\nC      F      Am      G\n\nSanto, Santo, Todopoderoso\n\nC       F     Am      G\n\nDigno es Él de adoración\n\nC/E  F    Am         G     C/E\n\nAl Cordero que crucificado fue\n\n       F          Am      G         F C/E\n\nSea la gloria, Su nombre sobre todo es\n\nAm  G          F   C | Am G\n\n    Sobre todo es\n\n\n\nVERSO 2:\n\n     C   Csus   C         G             Am      F\n\nSus ojos como fuego y su rostro brilla como el sol\n\n   C     Csus C          G    Am            F\n\nSu voz es poderosa, ruge como las olas del mar\n\n        Am7   Fmaj9 C/E  G/B\n\nY al  mirarte  cae  todo ser\n\n     Am7     Fmaj9 C     Gsus G\n\nAnte tu gran majestad, y can-tan:\n\nCORO: (...)\n\n\n\nVERSO 3:\n\n        C     Csus    C          G              Am    F\n\nCon tu sangre has comprado gente de toda lengua y nación\n\n       C       Csus  C                G\n\nToda rodilla a Ti se doblará, y toda lengua te confesará:\n\nAm      F\n\n“Señor!”\n\n       Am7     Fmaj9    C/E   G/B\n\nHas vencido la muerte y la maldad\n\n        Am7   Fmaj9 C       Gsus  G\n\nY en victoria reinarás por siem - pre"
  },
  {
    "id": 4,
    "title": "Hay Libertad",
    "artist": "Adoración La IBI",
    "type": "cantos",
    "tone": "C",
    "content": "[Intro 2x] C  F  Am  G\n\n[Primera Parte]\n\n       F                 C\n\nLas cadenas de la muerte me quitó\n\n     Am                    G             F  C      Am   G\n\nPara mí ya no hay condenación, hay libertad,  libertad\n\n          F               C\n\nSiendo esclavo del pecado me libró\n\n       Am                   G          F  C      G\n\nEn la cruz compró mi redención, y libertad,  libertad\n\n[Refrão :]\n\n              C                   F\n\nRompió mis cadenas, me dio vida nueva\n\n               Am              G\n\nY al fondo del mar echó mi maldad\n\n            C                   F\n\nLavó mis pecados y  me ha perdonado\n\n           Am           G           C  F Am G\n\nSolo en el nombre de Jesús hay libertad\n\n[Segunda Parte]\n\n        F                         C\n\nYo proclamo al que en la cruz por mí murió\n\n      Am              G            F C      Am G\n\nY cambió mi duro corazón por libertad, libertad\n\n        F        C\n\nEl poder de su evangelio me salvó\n\n      Am           G           F    C      G\n\nY no me avergüenzo del Señor mi libertad,  libertad\n\n[Refrão :]\n\n              C                   F\n\nRompió mis cadenas, me dio vida nueva\n\n               Am              G\n\nY al fondo del mar echó mi maldad\n\n            C                   F\n\nLavó mis pecados y  me ha perdonado\n\n           Am           G           C  F Am G\n\nSolo en el nombre de Jesús hay libertad\n\nPuente\n\n          C           G        Am        F      C   G\n\nAl que el Hijo, hace libre, es libre       en verdad\n\n          C           G        F          C     G\n\nAl que el Hijo, hace libre, es libre en verdad\n\n          C           G        Am     F      C  G\n\nAl que el Hijo, hace libre, es libre   en verdad\n\n          C           G        F           C\n\nAl que el Hijo, hace libre, es libre en verdad\n\n[Refrão :]\n\n              C                   F\n\n/ Rompió mis cadenas, me dio vida nueva\n\n               Am              G\n\nY al fondo del mar echó mi maldad\n\n            C                   F\n\nLavó mis pecados y  me ha perdonado\n\n           Am           G\n\nSolo en el nombre de Jesús/\n\n              C  F Am G\n\n///Hay libertad///"
  },
  {
    "id": 5,
    "title": "Dios Poderoso",
    "artist": "Adoración La IBI",
    "type": "cantos",
    "tone": "Em",
    "content": "[Intro] D#m  Gb  A#m  C#\n\nD#m\n\n¿Quien; sino el Señor\n\n              Gb\n\nLas estrellas creo y su luz limitó?\n\nD#m\n\n¿Quien; sino el Señor\n\n              Gb\n\nSol y luna formó, movimiento les dió?\n\nC#                            G#m\n\n¿Quien,sino el Señor hace la lluvia venir\n\nTruenos rugir?\n\nC#                   G#m\n\nTus obras grandes son!\n\n        B            Gb       C#\n\nDios poderoso! Tu gobiernas la creación\n\n        D#m          B\n\nCon tu palabra, Señor\n\n    Gb    A#m   C#\n\nTe exaltaremos\n\n        B            Gb       C#\n\nDios poderoso! De ti canta la creación\n\n        D#m          B\n\nLlenas todo Tú, Señor\n\n    Gb    A#m        C#                D#m\n\nTe exaltaremos por siempre y siempre o Dios\n\n( Gb  A#m  C# )\n\nD#m\n\n¿Quien, sino el Señor\n\n                Gb\n\nA soñado en el plan para el hombre salvar?\n\nD#m                                     Gb\n\n¿Quien, sino el Señor, limpiará al pecador\n\nCon su sangre y amor?\n\nC#                             G#m\n\nQuien, sino el Señor pode dar vida y salvar\n\nPor una cruz?\n\nC#                    G#m\n\nTus planes grandes son!\n\nB            Gb       C#\n\nDios poderoso! Tu gobiernas la creación\n\n        D#m          B\n\nCon tu palabra, Señor\n\n    Gb    A#m   C#\n\nTe exaltaremos\n\n        B            Gb       C#\n\nDios poderoso! De ti canta la creación\n\n        D#m          B\n\nLlenas todo Tú, Señor\n\n    Gb    A#m        C#                D#m\n\nTe exaltaremos por siempre y siempre o Dios\n\n( B  D#m  Gb  A#m )\n\n( B  D#m  Gb  A#m )\n\nB        D#m      C#     Gb\n\nTodas las cosas vienen de Ti\n\n      B\n\nY por Ti\n\n    D#m       C#\n\nÓh gran yo soy!\n\nB     D#m      C#  Gb\n\nTodo es tuyo y para Ti\n\n    B        D#m       C#\n\nOh Señor, oh gran yo soy\n\nB            Gb       C#\n\nDios poderoso! Tu gobiernas la creación\n\n        D#m          B\n\nCon tu palabra, Señor\n\n    Gb    A#m   C#\n\nTe exaltaremos\n\n        B            Gb       C#\n\nDios poderoso! De ti canta la creación\n\n        D#m          B\n\nLlenas todo Tú, Señor\n\n    Gb    A#m        C#                D#m\n\n//Te exaltaremos por siempre y siempre o Dios//\n\n   C#.              D#m\n\nPor siempre y siempre o Dios"
  },
  {
    "id": 6,
    "title": "Mi Roca",
    "artist": "Hillsong en Español",
    "type": "cantos",
    "tone": "C",
    "content": "[Intro] C   Am   F - G\n\nC\n\nMi esperanza esta en jesus\n\nF                  G\n\nEn su justicia y en la cruz\n\nAm                 Am/G\n\nDe nadie mas dependere\n\nF          G          C\n\nSolo en su nombre confiare\n\n      F\n\nEn jesús\n\nAm       G\n\nFuerte soy\n\nC/E   F\n\nSolo el\n\nAm       G\n\nMi roca es\n\nC/E    F     Am\n\nSobre la tempestad\n\nG     C\n\nEl es rey\n\nC\n\nCuando no puedo ver su faz\n\nF               G\n\nSe que su gracia es siempre igual\n\nAm                Am/G\n\nA la tormenta vencere\n\nF         G            C\n\nMi ancla firme esta en el\n\nF         G            C\n\nMi ancla firme esta en el\n\n[Solo] F  Am  G  C/E\n\nC\n\nUn dia el regresara\n\nF                G\n\nEn su presencia voy a estar\n\nAm                      Am/G\n\nSin mancha ante el vendre\n\nF          G            C\n\nJustificado por la fe"
  },
  {
    "id": 7,
    "title": "A Él Alto y Sublime",
    "artist": "Gadiel Espinoza",
    "type": "cantos",
    "tone": "G",
    "content": "[Intro]\nG - D2/F# - B2/Eb - Em7 - A2/C# - D - G2/B - C2 - Dsus4 - D\n\n[Verso]\n     G2                    C/G\nA EL ALTO Y SUBLIME QUE HABITA EN LA ETERNIDAD\n     Am7                       Dsus4 D\nY SU NOMBRE ES EL SANTA DE ISRAEL.\n         G2                   C/G\nAL QUE HABITA EN LAS ALTURAS Y EN LA SANTIDAD\n         Am7                        Dsus4 D\nY CON EL QUEBRANTADO Y HUMILDE DE ESPÍRITU.\n\nEm7                 C2\nPARA HACER VIVIR EL ESPÍRITU HUMILDE\nEm7      Em/D       C2        Dsus4 D\nY PARA VIVIFICAR EL CORAZÓN QUEBRANTADO.\n\n[Coro]\n       G2       D/G   C/E  C  Dsus4 D\nSEA LA GLORIA, HONOR, ALABANZAS Y PODER\n       G2           D           C2    D     Eb  C#/Eb  Eb\nAL QUE REINA POR LOS SIGLOS Y SU NOMBRE SANTO ES\n\n[Sube medio tono]\n       Ab2        Eb/Ab   C#/F  C#   Ebsus4 Eb\nSEA LA GLORIA, HONOR, ALABANZA Y PODER\n       Ab2            Eb          C#2     Eb    Ab  Fm7 Eb\nAL QUE REINA POR LOS SIGLOS Y SU NOMBRE SANTO ES\n      C#2     Eb    C#/Ab  Eb/Ab Ab2\nY SU NOMBRE SANTO ES"
  },
  {
    "id": 8,
    "title": "Jesús",
    "artist": "Sarai Rivera",
    "type": "cantos",
    "tone": "F",
    "bpm": 61,
    "content": "[Intro]\nF  Bb  F  Gm  F  Bb\n\n[Verso 1]\n  F           C            Dm\n¿Quién puede sanar el corazón?\n  Bb            F           Gm   F   C\n¿Quién responderá cada oración?\n  F               C                Dm\n¿Quién es el que brilla más que el sol?\nF     Bb    C          F\nÉl es mi Señor y Salvador\n\n[Coro]\n   F\nJesús\n                   C\nNo hay nadie como tú\n                   Dm             F\nLos cielos cuentan de tu majestad\n      Bb\nCuán grande es tu bondad\n\n   F\nJesús\n                   C\nNo hay nadie como tú\n                  Dm                F\nLa tierra se estremece al mencionar\n    Bb\nTu nombre sin igual\n      F  Gm  F  Bb\nJesús\n\n[Verso 2]\n  F               C          Dm\n¿Quién es el que sufre por amor?\n  Bb               F            Gm   F  C\n¿Quién perdona al que lo traicionó?\n  F               C        Dm\n¿Quién por mí su vida entregó?\nF     Bb    C         Dm   F\nÉl es mi Señor y Salvador\n      Bb    C          F  Bb  C\nÉl es mi Señor y Salvador\n\n[Coro]\n   F\nJesús\n                   C\nNo hay nadie como tú\n                   Dm             F\nLos cielos cuentan de tu majestad\n      Bb\nCuán grande es tu bondad\n\n   F\nJesús\n                   C\nNo hay nadie como tú\n                  Dm                F\nLa tierra se estremece al mencionar\n    Bb\nTu nombre sin igual\n\n[Puente]\n         F\nPoderoso eres tú\n                    Am\nTu gloria es por la eternidad\n            Gm7\nDigno de adorar\n         Bb\nTú eres santo Dios\n         F\nPoderoso eres tú\n                    Am\nTu gloria es por la eternidad\n            Gm7\nDigno de adorar\n        Bb\nTú eres santo Dios\n\nF  Am  Gm7  Bb\n\n[Coro]\n   F\nJesús\n                   C\nNo hay nadie como tú\n                   Dm             F\nLos cielos cuentan de tu majestad\n      Bb\nCuán grande es tu bondad\n\n   F\nJesús\n                   C\nNo hay nadie como tú\n                  Dm                F\nLa tierra se estremece al mencionar\n    Bb\nTu nombre sin igual\n       F\nJesús"
  }
];