(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const NOTE_NAMES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const LATIN={'C':'Do','C#':'Do#','D':'Re','D#':'Re#','E':'Mi','F':'Fa','F#':'Fa#','G':'Sol','G#':'Sol#','A':'La','A#':'La#','B':'Si'};
const voiceLang=()=>localStorage.getItem('lagrey_language')==='en'?'en':'es',vtx=(es,en)=>voiceLang()==='en'?en:es;
const categories=[
{id:'warm',icon:'🔥',title:'Calentamiento',desc:'Despierta la voz de forma progresiva antes de cantar.'},
{id:'breath',icon:'🌬️',title:'Respiración',desc:'Controla el aire sin tensión y coordina respiración con sonido.'},
{id:'resonance',icon:'🔊',title:'Resonancia',desc:'Activa sensaciones de vibración con sonidos cómodos como MMM y NG.'},
{id:'pitch',icon:'🎯',title:'Afinación',desc:'Escucha, imita y estabiliza notas e intervalos.'},
{id:'range',icon:'↕️',title:'Rango vocal',desc:'Explora graves y agudos de forma gradual, nunca forzada.'},
{id:'agility',icon:'⚡',title:'Agilidad',desc:'Coordina cambios rápidos de nota con precisión y ligereza.'},
{id:'diction',icon:'🗣️',title:'Dicción',desc:'Aclara vocales y consonantes para que el texto se entienda al cantar.'},
{id:'cool',icon:'🧊',title:'Enfriamiento',desc:'Devuelve la voz a una emisión suave después de cantar.'}
];
const shellCategories={
 warm:['Calentamiento','Warm-up','Despierta la voz de forma progresiva antes de cantar.','Wake up the voice gradually before singing.'],
 breath:['Respiración','Breathing','Controla el aire sin tensión y coordina respiración con sonido.','Control the airflow without tension and coordinate breath with sound.'],
 resonance:['Resonancia','Resonance','Activa sensaciones de vibración con sonidos cómodos como MMM y NG.','Activate comfortable vibration sensations with sounds such as MMM and NG.'],
 pitch:['Afinación','Pitch','Escucha, imita y estabiliza notas e intervalos.','Listen, imitate and stabilize notes and intervals.'],
 range:['Rango vocal','Vocal range','Explora graves y agudos de forma gradual, nunca forzada.','Explore low and high notes gradually, never by force.'],
 agility:['Agilidad','Agility','Coordina cambios rápidos de nota con precisión y ligereza.','Coordinate quick note changes with precision and lightness.'],
 diction:['Dicción','Diction','Aclara vocales y consonantes para que el texto se entienda al cantar.','Clarify vowels and consonants so the words are understood while singing.'],
 cool:['Enfriamiento','Cool-down','Devuelve la voz a una emisión suave después de cantar.','Bring the voice back to a gentle production after singing.']
};
const ex=(name,pattern,syllables,tip,why,example,tempo=90)=>({name,pattern,syllables,tip,why,example,tempo});
const exercises={
warm:[
 ex('Trino de labios · 5 notas',[0,2,4,5,7,5,4,2,0],['Brrr','Vvv','Zzz'],'Labios sueltos y poco volumen.','Ayuda a coordinar aire y sonido con poca presión.','Haz “brrr” como un motor suave mientras sigues el piano.',82),
 ex('Sirena suave',[0,4,7,12,7,4,0],['UU','NG','Woo'],'No empujes al subir.','Favorece una transición continua entre zonas de la voz.','Imagina una sirena pequeña, no una alarma fuerte.',72),
 ex('Cinco notas ligeras',[0,2,4,5,7,5,4,2,0],['MI','NU','GI'],'Mantén la mandíbula libre.','Despierta coordinación sin exigir demasiado rango.','Canta una sílaba por nota.',92)
],
breath:[
 {name:'Siseo controlado',timed:true,duration:40,syllables:['SSS'],tip:'Inhala sin levantar hombros y suelta el aire parejo.',why:'Entrena dosificación del aire.',example:'Inhala 4 tiempos y mantén “sss” uniforme.'},
 {name:'Pulsos de aire',timed:true,duration:35,syllables:['SH','TS','F'],tip:'Pulsos pequeños, sin hundir el pecho.',why:'Trabaja coordinación del flujo de aire.',example:'Haz 8 pulsos y descansa una respiración.'},
 {name:'Frase larga en V',timed:true,duration:45,syllables:['VVV'],tip:'Mantén sensación continua y cómoda.',why:'Une respiración y vibración sonora.',example:'Sostén “vvv” estable y termina antes de quedarte sin aire.'}
],
resonance:[
 ex('Humming de 5 notas',[0,2,4,5,7,5,4,2,0],['MMM','NNN','NG'],'Busca vibración cómoda, sin apretar.','Ayuda a encontrar una emisión eficiente.','Sonríe apenas y mantén el sonido pequeño.',86),
 ex('NG → vocal',[0,2,4,2,0],['NG-A','NG-E','NG-O'],'Abre la vocal sin perder facilidad.','Conecta resonancia con vocales de canto.','Haz NG en la primera mitad y abre a la vocal.',78),
 ex('Mum de 5 notas',[0,2,4,5,7,5,4,2,0],['MUM','MOM','MIM'],'No oscurezcas ni empujes.','Trabaja foco y estabilidad del sonido.','Pronuncia claro pero sin morder la consonante.',88)
],
pitch:[
 ex('Eco de 3 notas',[0,2,4,2,0],['MA','NE','LO'],'Escucha primero y luego repite.','Entrena memoria tonal y precisión.','Piano primero; tú imitas después.',76),
 ex('Arpegio mayor',[0,4,7,12,7,4,0],['NO','YA','GO'],'Haz limpios los saltos.','Trabaja intervalos más amplios.','Evita deslizarte entre notas.',82),
 ex('1–2–3–2–1',[0,2,4,2,0],['DI','ME','TU'],'Mantén cada nota centrada.','Refuerza afinación en patrones cortos.','Una sílaba por cada nota.',92)
],
range:[
 ex('Escala de octava',[0,2,4,5,7,9,11,12,11,9,7,5,4,2,0],['NU','NO','GU'],'Detente antes de que aparezca presión.','Amplía el área cómoda de manera gradual.','Sube semitono solo si la repetición anterior fue cómoda.',76),
 ex('Arpegio extendido',[0,4,7,12,16,12,7,4,0],['GUG','NAY','MUM'],'Volumen moderado.','Explora extensión con saltos controlados.','No persigas la nota alta; deja que llegue ligera.',72),
 ex('Descenso hacia graves',[12,9,7,5,4,2,0],['OH','UH','MUM'],'No fabriques una voz artificialmente grave.','Ayuda a explorar el registro bajo con relajación.','Piensa más en soltar que en oscurecer.',74)
],
agility:[
 ex('Cinco notas rápidas',[0,2,4,5,7,5,4,2,0],['DA','GI','NE'],'Empieza lento y acelera solo si sale limpio.','Mejora coordinación y precisión rítmica.','Ataques pequeños; no martilles las consonantes.',112),
 ex('1–3–5–3–1',[0,4,7,4,0],['MI','NO','YA'],'Mantén el pulso exacto.','Entrena saltos rápidos y controlados.','Piensa en notas separadas pero conectadas.',108),
 ex('Escalera 1–2–3–4–5',[0,2,4,5,7,5,4,2,0],['LE-GA-TO','DI-GA-ME','PA-TA-KA'],'No corras por encima del piano.','Une articulación y velocidad.','Hazlo primero muy claro y luego más rápido.',118)
],
diction:[
 ex('Vocales abiertas',[0,2,4,5,7,5,4,2,0],['MA-ME-MI-MO-MU','NA-NE-NI-NO-NU'],'Mandíbula suelta y vocales claras.','Mejora inteligibilidad al cantar.','No cambies volumen al cambiar de vocal.',88),
 ex('Consonantes alternadas',[0,2,4,2,0],['DA-GA','TA-KA','BA-DA'],'Consonante clara, garganta libre.','Entrena precisión del texto.','Haz la consonante breve y deja sonar la vocal.',94),
 ex('Frase rítmica',[0,2,4,5,7,5,4,2,0],['MI-ME-MA-MO-MU','PA-TA-KA-DA-GA'],'No sacrifiques claridad por velocidad.','Prepara frases rápidas de canciones.','Primero habla el patrón, luego cántalo.',100)
],
cool:[
 ex('Humming descendente',[7,5,4,2,0],['MMM','NNN'],'Muy suave.','Ayuda a bajar intensidad después de cantar.','Piensa en una despedida tranquila.',68),
 ex('Descenso en U',[12,9,7,5,4,2,0],['UU','OO'],'Deja caer la voz, no la empujes.','Favorece una vuelta gradual a una emisión cómoda.','Usa menos volumen que durante el calentamiento.',66),
 ex('Suspiro sonoro',[7,4,0],['HAA','HOO'],'Exhala y deja que la voz acompañe.','Relaja la emisión al terminar.','Debe sentirse fácil, casi como bostezar suavemente.',62)
]
};
const exerciseEN={
 warm:[['Lip trill · 5 notes','Relax your lips and keep the volume low.','Helps coordinate airflow and sound with little pressure.','Do a gentle “brrr” like a soft motor while following the piano.'],['Gentle siren','Do not push as you go higher.','Encourages a smooth transition between areas of the voice.','Imagine a small siren, not a loud alarm.'],['Light five-note pattern','Keep your jaw relaxed.','Wakes up coordination without demanding too much range.','Sing one syllable per note.']],
 breath:[['Controlled hiss','Inhale without raising your shoulders and release the air evenly.','Trains airflow management.','Inhale for 4 counts and keep “sss” steady.'],['Air pulses','Use small pulses without collapsing your chest.','Trains airflow coordination.','Do 8 pulses and rest for one breath.'],['Long V phrase','Keep the sensation continuous and comfortable.','Connects breathing and vocal vibration.','Hold “vvv” steadily and stop before you run out of air.']],
 resonance:[['Five-note humming','Find a comfortable vibration without squeezing.','Helps find efficient sound production.','Smile slightly and keep the sound small.'],['NG → vowel','Open the vowel without losing ease.','Connects resonance with sung vowels.','Use NG for the first half and then open to the vowel.'],['Five-note Mum','Do not darken or push the sound.','Works on focus and sound stability.','Pronounce clearly without biting the consonant.']],
 pitch:[['Three-note echo','Listen first and then repeat.','Trains tonal memory and pitch accuracy.','Piano first; you imitate afterward.'],['Major arpeggio','Keep the leaps clean.','Works on wider intervals.','Avoid sliding between notes.'],['1–2–3–2–1','Keep each note centered.','Reinforces pitch accuracy in short patterns.','One syllable for each note.']],
 range:[['Octave scale','Stop before pressure appears.','Gradually expands your comfortable range.','Move up a semitone only if the previous repetition felt comfortable.'],['Extended arpeggio','Use a moderate volume.','Explores range with controlled leaps.','Do not chase the high note; let it arrive lightly.'],['Descending to low notes','Do not manufacture an artificially low voice.','Helps explore the lower register with relaxation.','Think more about releasing than darkening the sound.']],
 agility:[['Fast five-note pattern','Start slowly and speed up only if it stays clean.','Improves coordination and rhythmic accuracy.','Use small attacks; do not hammer the consonants.'],['1–3–5–3–1','Keep the pulse exact.','Trains fast, controlled leaps.','Think of separate notes that still stay connected.'],['1–2–3–4–5 ladder','Do not rush ahead of the piano.','Combines articulation and speed.','Do it very clearly first, then make it faster.']],
 diction:[['Open vowels','Keep your jaw relaxed and vowels clear.','Improves intelligibility while singing.','Do not change volume when you change vowels.'],['Alternating consonants','Use a clear consonant with a free throat.','Trains text precision.','Make the consonant brief and let the vowel ring.'],['Rhythmic phrase','Do not sacrifice clarity for speed.','Prepares fast phrases in songs.','Speak the pattern first, then sing it.']],
 cool:[['Descending humming','Keep it very soft.','Helps reduce intensity after singing.','Think of a calm goodbye.'],['Descending on U','Let the voice fall; do not push it.','Encourages a gradual return to comfortable production.','Use less volume than during the warm-up.'],['Voiced sigh','Exhale and let the voice follow.','Relaxes vocal production at the end.','It should feel easy, almost like a gentle yawn.']]
};
const routines={quick:{title:'⚡ Calentamiento rápido · 5 min',steps:[['breath',0,40],['warm',0,55],['resonance',0,55],['pitch',0,55],['diction',0,55]]},worship:{title:'🎤 Antes del culto · 10 min',steps:[['breath',0,50],['warm',0,70],['resonance',1,75],['pitch',0,75],['range',0,90],['agility',0,80],['diction',0,80]]},full:{title:'🔥 Entrenamiento completo · 20 min',steps:[['breath',0,60],['breath',1,50],['warm',0,80],['warm',1,80],['resonance',0,90],['resonance',1,90],['pitch',0,90],['pitch',1,90],['range',0,110],['range',1,110],['agility',0,100],['agility',1,100],['diction',0,90],['diction',1,90],['cool',0,80],['cool',1,80]]}};
const shellRoutines={quick:['⚡ Calentamiento rápido · 5 min','⚡ Quick warm-up · 5 min'],worship:['🎤 Antes del culto · 10 min','🎤 Before worship · 10 min'],full:['🔥 Entrenamiento completo · 20 min','🔥 Full training · 20 min']};
const academyLessons=[
{id:'voice-advanced-01-mix',icon:'🎚️',title:['Mezcla vocal y transición de registros','Vocal mix and register transitions'],minutes:'20 min',objective:['Cruzar zonas de transición sin convertir cada nota alta en más volumen y presión.','Cross transition zones without turning every high note into more volume and pressure.'],concept:['La meta no es fabricar una voz nueva llamada mezcla. Es coordinar cambios de registro de forma progresiva ajustando intensidad, vocal y peso al subir.','The goal is not to manufacture a new voice called mix. It is to coordinate register changes progressively by adjusting intensity, vowel and weight as you ascend.'],feel:[['Sonido continuo y repetible sin fatiga inmediata.','A continuous sound that can be repeated without immediate fatigue.'],['Cuello y mandíbula sin aumento evidente de tensión.','Neck and jaw stay free from obvious extra tension.'],['Agudos algo más ligeros que los graves.','High notes feel somewhat lighter than low notes.']],avoid:[['Empujar el pecho hacia arriba.','Pushing chest voice upward.'],['Levantar la barbilla para alcanzar la nota.','Lifting the chin to reach the note.'],['Usar más volumen como única estrategia.','Using more volume as the only strategy.']],practice:[['Sirena suave con NG o Woo: 1–3–5–8–5–3–1 a 68–76 BPM.','Gentle NG or Woo siren: 1–3–5–8–5–3–1 at 68–76 BPM.'],['MUM: 1–2–3–4–5–4–3–2–1 a 78–86 BPM.','MUM: 1–2–3–4–5–4–3–2–1 at 78–86 BPM.'],['Pasa el patrón a una vocal de una canción real conservando la facilidad.','Move the pattern to a vowel from a real song while keeping the same ease.']],ministry:['Elige una frase del repertorio que suba hacia el coro. Cántala a volumen medio y luego con letra, sin aumentar presión al llegar arriba.','Choose a repertoire phrase that rises into the chorus. Sing it at medium volume and then with lyrics, without increasing pressure at the top.'],check:[['¿La nota alta salió más fácil al bajar un poco la intensidad?','Did the high note become easier when you reduced intensity slightly?'],['¿Pudiste repetir la frase tres veces sin endurecer cuello o mandíbula?','Could you repeat the phrase three times without tightening neck or jaw?']],target:{type:'category',id:'warm'}},
{id:'voice-advanced-02-passaggio',icon:'↗️',title:['Passaggio sin tensión','Passaggio without tension'],minutes:'18 min',objective:['Reconocer la zona donde la voz quiere reorganizarse y practicar alrededor de ella sin perseguir extremos.','Recognize where the voice wants to reorganize and practice around it without chasing extremes.'],concept:['El passaggio no se trabaja venciendo una nota problemática, sino coordinando varias notas alrededor de la transición hasta que deja de sentirse como una pared.','Passaggio is not trained by defeating one problem note, but by coordinating several notes around the transition until it stops feeling like a wall.'],feel:[['Transición gradual y posibilidad de hacer la nota más pequeña sin perder afinación.','A gradual transition and the ability to make the note smaller without losing pitch.'],['Libertad para volver inmediatamente a una nota media.','Freedom to return immediately to a middle note.']],avoid:[['Repetir muchas veces la nota que falla.','Repeating the failing note over and over.'],['Sostener agudos tensos para fortalecerlos.','Holding tense high notes to strengthen them.'],['Comparar tu rango con el de otro cantante.','Comparing your range with another singer.']],practice:[['NG-A en 1–2–3–2–1.','NG-A on 1–2–3–2–1.'],['NO o MUM en 1–3–5–3–1.','NO or MUM on 1–3–5–3–1.'],['Sube por semitonos solo mientras la repetición anterior siga cómoda.','Move by semitones only while the previous repetition remains comfortable.']],ministry:['Identifica una frase del setlist que cruce de zona media a alta. Practica primero la vocal dominante de la nota alta y luego devuelve la transición a la frase.','Identify a setlist phrase that crosses from middle to upper range. Practice the main vowel of the high note first, then return the transition to the phrase.'],check:[['¿Estoy intentando hacer la nota más grande o más fácil?','Am I trying to make the note bigger or easier?'],['¿Puedo detenerme antes de sentir fatiga?','Can I stop before fatigue appears?']],target:{type:'category',id:'resonance'}},
{id:'voice-advanced-03-dynamics',icon:'📈',title:['Control dinámico y volumen útil','Dynamic control and useful volume'],minutes:'18 min',objective:['Cantar suave, medio y firme sin que fuerte signifique gritar ni suave signifique perder afinación.','Sing softly, moderately and firmly without strong meaning shouting or soft meaning losing pitch.'],concept:['La dinámica crea contraste musical. El micrófono permite que el cantante no tenga que producir todo el volumen acústicamente.','Dynamics create musical contrast. A microphone means the singer does not need to produce all volume acoustically.'],feel:[['Afinación estable al cambiar intensidad.','Stable pitch while changing intensity.'],['Consonantes claras sin golpear.','Clear consonants without hammering.'],['El sonido crece sin endurecerse.','The sound grows without hardening.']],avoid:[['Competir con batería, guitarras o monitores.','Competing with drums, guitars or monitors.'],['Cantar todo al 100%.','Singing everything at 100%.'],['Confundir emoción con presión laríngea.','Confusing emotion with laryngeal pressure.']],practice:[['Cinco notas con MMM → MA, primero suave.','Five notes on MMM → MA, starting softly.'],['Repite a intensidad media sin cambiar afinación.','Repeat at medium intensity without changing pitch.'],['En una nota cómoda: suave → medio → firme → medio → suave.','On a comfortable note: soft → medium → firm → medium → soft.']],ministry:['Toma verso, pre-coro y coro. Planifica un crecimiento aproximado de 40–55%, 55–70% y 65–80% como referencias musicales, no físicas.','Take a verse, pre-chorus and chorus. Plan an approximate growth of 40–55%, 55–70% and 65–80% as musical, not physical, references.'],check:[['¿Mi afinación cambió al cantar más suave?','Did my pitch change when I sang more softly?'],['¿Subí intensidad sin levantar la barbilla?','Did I increase intensity without lifting my chin?']],target:{type:'category',id:'resonance'}},
{id:'voice-advanced-04-intervals',icon:'🎯',title:['Afinación avanzada e intervalos','Advanced pitch and intervals'],minutes:'20 min',objective:['Mejorar precisión en saltos, entradas difíciles y líneas que no siguen la melodía principal.','Improve accuracy in leaps, difficult entrances and lines that do not follow the main melody.'],concept:['Afinar no es solo dar la nota: hay que escuchar la referencia, anticipar la distancia y llegar sin arrastrarse desde otra nota.','Pitch accuracy is more than hitting the note: hear the reference, anticipate the distance and arrive without sliding from another note.'],feel:[['Entrada limpia y directa.','A clean, direct entrance.'],['Capacidad de imaginar la siguiente nota antes de cantarla.','Ability to imagine the next note before singing it.']],avoid:[['Deslizarte hasta encontrar la nota.','Sliding until you find the note.'],['Cantar más fuerte cuando no estás seguro.','Singing louder when unsure.'],['Depender visualmente del afinador durante toda la frase.','Watching the tuner through the whole phrase.']],practice:[['Eco de tres notas.','Three-note echo.'],['Arpegio mayor 1–3–5–8–5–3–1.','Major arpeggio 1–3–5–8–5–3–1.'],['Aísla 1→3, 1→5, 3→5 y 5→8; escucha el piano antes de cantar.','Isolate 1→3, 1→5, 3→5 and 5→8; hear the piano before singing.']],ministry:['Busca una entrada después de silencio o un salto grande. Practica solo las dos notas implicadas y después vuelve a la frase completa.','Find an entrance after silence or a large leap. Practice only the two involved notes, then return to the full phrase.'],check:[['¿Puedo oír mentalmente la siguiente nota antes de cantarla?','Can I hear the next note mentally before singing it?'],['¿Mi ataque llega directo o necesita corrección?','Does my attack arrive directly or need correction?']],target:{type:'category',id:'pitch'}},
{id:'voice-advanced-05-harmony',icon:'🎶',title:['Armonías para ministerios de alabanza','Harmony for worship ministries'],minutes:'25 min',objective:['Sostener una segunda voz sin regresar automáticamente a la melodía principal.','Hold a harmony part without automatically returning to the main melody.'],concept:['Una armonía útil pertenece al acorde y cumple una función dentro del arreglo. Para empezar, trabaja raíz, tercera y quinta de tríadas mayores.','A useful harmony belongs to the chord and serves a function in the arrangement. Start with root, third and fifth of major triads.'],feel:[['Escuchas el acorde completo además de tu propia voz.','You hear the whole chord as well as your own voice.'],['Puedes mantener una nota distinta mientras otro canta la melodía.','You can hold a different note while someone else sings the melody.']],avoid:[['Improvisar terceras paralelas durante toda la canción.','Improvising parallel thirds through the entire song.'],['Llenar cada frase con voces secundarias.','Filling every phrase with backing vocals.'],['Subir volumen cuando pierdes tu armonía.','Getting louder when you lose your harmony.']],practice:[['Piano toca 1–3–5; repite cada nota individual.','Piano plays 1–3–5; repeat each note individually.'],['Sostén la tercera mientras el piano repite la tríada.','Hold the third while the piano repeats the triad.'],['Alterna raíz y tercera sin deslizar.','Alternate root and third without sliding.']],ministry:['En un coro sencillo define por escrito dónde entra la armonía, dónde sale, qué queda al unísono y quién sostiene cada voz.','In a simple chorus, write down where harmony enters, exits, what stays in unison and who holds each part.'],check:[['¿Puedo mantener mi nota aunque otro cante la melodía?','Can I hold my note while someone else sings the melody?'],['¿Sé cuándo debo dejar de armonizar?','Do I know when to stop harmonizing?']],target:{type:'category',id:'pitch'}},
{id:'voice-advanced-06-endurance',icon:'⏳',title:['Resistencia vocal en ensayos y cultos','Vocal endurance in rehearsals and services'],minutes:'20 min',objective:['Administrar la voz en sesiones largas sin confundir resistencia con cantar fuerte por más tiempo.','Manage the voice through long sessions without confusing endurance with singing loudly for longer.'],concept:['La resistencia se construye con eficiencia, pausas, repertorio bien ubicado e intensidad sostenible; no aguantando dolor.','Endurance is built with efficiency, rests, smart repertoire placement and sustainable intensity; not by enduring pain.'],feel:[['Terminas el ensayo con una voz parecida a como empezaste.','You finish rehearsal with a voice similar to how you started.'],['Puedes alternar trabajo y descanso sin perder coordinación.','You can alternate work and rest without losing coordination.']],avoid:[['Cantar todas las canciones a máxima intensidad.','Singing every song at maximum intensity.'],['Competir con el monitoreo por volumen.','Competing with monitors for volume.'],['Continuar con dolor, ardor o ronquera que empeora.','Continuing through pain, burning or worsening hoarseness.']],practice:[['1 min respiración tranquila.','1 min relaxed breathing.'],['2 min trino de labios + 2 min humming.','2 min lip trills + 2 min humming.'],['2 min afinación media + 3 min frase real + 2 min humming descendente.','2 min middle-range pitch + 3 min real phrase + 2 min descending humming.']],ministry:['Antes revisa tonos y canciones exigentes; durante aprovecha partes instrumentales y otras voces; después baja intensidad y descansa si hubo mucha carga.','Beforehand review keys and demanding songs; during the service use instrumental sections and other voices; afterward reduce intensity and rest if the load was high.'],check:[['¿Las canciones difíciles están todas seguidas?','Are all the difficult songs back-to-back?'],['¿Puedo delegar líneas a otros cantantes?','Can I delegate lines to other singers?']],target:{type:'routine',id:'worship'}},
{id:'voice-advanced-07-agility',icon:'⚡',title:['Agilidad y melismas controlados','Agility and controlled melismas'],minutes:'18 min',objective:['Hacer adornos rápidos solo cuando mantienen ritmo, afinación y claridad.','Use fast ornaments only when rhythm, pitch and clarity remain intact.'],concept:['Un melisma útil debe poder cantarse lentamente y con notas identificables antes de acelerarlo.','A useful melisma should be singable slowly with identifiable notes before it is sped up.'],feel:[['Cada nota del adorno tiene lugar claro en el pulso.','Each ornament note has a clear place in the pulse.'],['La mandíbula no marca cada nota.','The jaw does not mark every note.']],avoid:[['Adornar cada final de frase.','Ornamenting every phrase ending.'],['Esconder desafinación detrás de velocidad.','Hiding poor pitch behind speed.'],['Copiar un melisma sin entender sus notas.','Copying a melisma without understanding its notes.']],practice:[['Cinco notas rápidas a 80 BPM.','Fast five-note pattern at 80 BPM.'],['Sube a 96 BPM solo después de tres repeticiones limpias.','Move to 96 BPM only after three clean repetitions.'],['Crea un adorno de 3–5 notas sobre una vocal y practícalo con pulso.','Create a 3–5 note ornament on one vowel and practice it in time.']],ministry:['Elige una sola frase donde el adorno tenga sentido y prepara también una versión simple para poder escoger según el contexto congregacional.','Choose one phrase where the ornament makes sense and also prepare a simple version so you can choose according to the congregational context.'],check:[['¿Puedo cantar el adorno a mitad de velocidad?','Can I sing the ornament at half speed?'],['¿El adorno sirve a la canción o solo demuestra habilidad?','Does the ornament serve the song or only show skill?']],target:{type:'category',id:'agility'}},
{id:'voice-advanced-08-setlist',icon:'📋',title:['Preparación vocal de un repertorio real','Preparing a real setlist vocally'],minutes:'25 min',objective:['Convertir las herramientas anteriores en una rutina concreta para preparar un setlist.','Turn the previous tools into a concrete routine for preparing a setlist.'],concept:['La preparación avanzada comienza antes de cantar: tono, frases exigentes, duración, armonías y distribución de carga deben revisarse como un conjunto.','Advanced preparation begins before singing: key, demanding phrases, duration, harmonies and workload distribution should be reviewed as a whole.'],feel:[['Sabes dónde están los puntos exigentes antes del ensayo.','You know where the demanding points are before rehearsal.'],['Puedes reservar energía para los momentos que realmente la necesitan.','You can save energy for the moments that truly need it.']],avoid:[['Descubrir en vivo que un tono queda demasiado alto.','Discovering live that a key is too high.'],['Practicar el set completo siempre a intensidad de escenario.','Always practicing the full set at stage intensity.'],['Dejar las armonías sin asignación previa.','Leaving harmonies unassigned.']],practice:[['Marca por canción: tono oficial, frase más exigente, canto continuo y armonías.','For each song mark: official key, hardest phrase, continuous singing and harmonies.'],['Calienta según lo que el set necesita, no por costumbre.','Warm up according to what the set requires, not by habit.'],['Ensaya las frases críticas primero aisladas y luego dentro del orden real.','Rehearse critical phrases first in isolation and then within the real order.']],ministry:['Ordena el set para distribuir demanda, define voces principales/secundarias y deja claro qué partes pueden descansar unos cantantes mientras otros sostienen la canción.','Order the set to distribute demand, assign lead/backing parts and make clear where some singers can rest while others carry the song.'],check:[['¿Sé cuál es la frase más exigente de cada canción?','Do I know the hardest phrase in each song?'],['¿El orden del set distribuye o acumula la carga?','Does the set order distribute or pile up vocal load?']],target:{type:'routine',id:'full'}}
];
const academyInteractive={
 'voice-advanced-01-mix':[
  {name:['Sirena coordinada · 1–3–5–8–5–3–1','Coordinated siren · 1–3–5–8–5–3–1'],pattern:[0,4,7,12,7,4,0],syllables:['NG','Woo','UU'],tempo:72,tip:['Mantén el sonido pequeño al subir; no aumentes volumen para alcanzar la octava.','Keep the sound small as you ascend; do not increase volume to reach the octave.']},
  {name:['MUM ligero · 1–2–3–4–5–4–3–2–1','Light MUM · 1–2–3–4–5–4–3–2–1'],pattern:[0,2,4,5,7,5,4,2,0],syllables:['MUM','MOM','NO'],tempo:82,tip:['Busca continuidad. Si la quinta se pone dura, baja intensidad o nota inicial.','Look for continuity. If the fifth gets hard, reduce intensity or starting note.']}
 ],
 'voice-advanced-02-passaggio':[
  {name:['NG → vocal · transición corta','NG → vowel · short transition'],pattern:[0,2,4,2,0],syllables:['NG-A','NG-E','NG-O'],tempo:74,tip:['Mantén NG pequeño y abre la vocal sin aumentar volumen. Si aparece presión, baja la nota inicial.','Keep NG small and open the vowel without increasing volume. If pressure appears, lower the starting note.']},
  {name:['MUM / NO · 1–3–5–3–1','MUM / NO · 1–3–5–3–1'],pattern:[0,4,7,4,0],syllables:['MUM','NO','NAY'],tempo:78,tip:['Piensa en facilidad y claridad. No conviertas la quinta en un grito.','Think ease and clarity. Do not turn the fifth into a shout.']}
 ],
 'voice-advanced-03-dynamics':[
  {name:['Frase estable · suave → medio','Stable phrase · soft → medium'],pattern:[0,2,4,5,7,5,4,2,0],syllables:['MMM-MA','NO','NU'],tempo:76,tip:['Haz la primera repetición suave y la segunda media sin cambiar afinación ni endurecer la mandíbula.','Do the first repetition softly and the second at medium intensity without changing pitch or hardening the jaw.']},
  {name:['Centro de voz · control de intensidad','Voice center · intensity control'],pattern:[0,0,0,0],syllables:['MA','OO','EH'],tempo:68,tip:['Usa las cuatro notas iguales como referencia: suave, medio, firme, suave. Nunca busques máximo volumen.','Use the four repeated notes as reference: soft, medium, firm, soft. Never chase maximum volume.']}
 ],
 'voice-advanced-04-intervals':[
  {name:['Saltos 1 → 3 → 1','Leaps 1 → 3 → 1'],pattern:[0,4,0],syllables:['MA','NO','DI'],tempo:72,tip:['Escucha la distancia antes de cantarla. Llega directo, sin deslizar.','Hear the distance before singing it. Arrive directly, without sliding.']},
  {name:['Saltos 1 → 5 → 1','Leaps 1 → 5 → 1'],pattern:[0,7,0],syllables:['MA','NO','YA'],tempo:68,tip:['No subas volumen para asegurar la quinta. Mantén el ataque pequeño y preciso.','Do not get louder to secure the fifth. Keep the onset small and accurate.']},
  {name:['Arpegio 1–3–5–8–5–3–1','Arpeggio 1–3–5–8–5–3–1'],pattern:[0,4,7,12,7,4,0],syllables:['NO','YA','GO'],tempo:76,tip:['Imagina cada destino antes de cantarlo y evita arrastrarte entre notas.','Imagine each destination before singing it and avoid sliding between notes.']}
 ],
 'voice-advanced-05-harmony':[
  {name:['Tríada mayor · raíz, tercera, quinta','Major triad · root, third, fifth'],pattern:[0,4,7,4,0],syllables:['AH','OO','MM'],tempo:66,tip:['Escucha cada función. Luego intenta volver a la tercera sin seguir automáticamente la raíz.','Hear each function. Then try returning to the third without automatically following the root.']},
  {name:['Tercera estable sobre acorde','Stable third over the chord'],pattern:[4,4,4,4],syllables:['AH','EH','OO'],tempo:62,tip:['Mantén una tercera estable sin subir volumen aunque escuches otras notas alrededor.','Hold a stable third without getting louder even while hearing other notes around it.']}
 ],
 'voice-advanced-07-agility':[
  {name:['Cinco notas limpias','Clean five-note run'],pattern:[0,2,4,5,7,5,4,2,0],syllables:['DA','GI','NE'],tempo:80,tip:['Completa tres repeticiones limpias antes de aumentar tempo.','Complete three clean repetitions before increasing tempo.']},
  {name:['Melisma corto · 1–3–5–3–2–1','Short melisma · 1–3–5–3–2–1'],pattern:[0,4,7,4,2,0],syllables:['AH','EH','OO'],tempo:84,tip:['Practícalo lento y con notas identificables. La mandíbula no debe marcar cada nota.','Practice it slowly with identifiable notes. Your jaw should not mark every note.']}
 ]
};
const academyVideos={
 'voice-advanced-01-mix':{src:'./academy-videos/voice-advanced-01-mix.mp4?v=passaggio-voice-v1',title:['Video IA · Mezcla vocal','AI video · Vocal mix'],duration:'4–5 min',scenes:[['Qué es la mezcla y qué no es','What mix is and what it is not'],['Cómo aligerar al subir sin perder continuidad','How to lighten as you ascend without losing continuity'],['Demostración NG/Woo y MUM','NG/Woo and MUM demonstration'],['Aplicación a una frase de coro','Application to a chorus phrase']]},
 'voice-advanced-02-passaggio':{src:'./academy-videos/voice-advanced-02-passaggio.mp4',title:['Video IA · Passaggio sin tensión','AI video · Passaggio without tension'],duration:'3:57',scenes:[['Reconocer la zona de transición','Recognizing the transition zone'],['Errores: empujar, repetir y perseguir la nota','Mistakes: pushing, repeating and chasing the note'],['NG-A y MUM paso a paso','NG-A and MUM step by step'],['Cuándo detener la práctica','When to stop practicing']]},
 'voice-advanced-03-dynamics':{src:'./academy-videos/voice-advanced-03-dynamics.mp4',title:['Video IA · Control dinámico','AI video · Dynamic control'],duration:'3–4 min',scenes:[['Suave no significa sin apoyo','Soft does not mean unsupported'],['Firme no significa gritar','Firm does not mean shouting'],['Micrófono, monitores y volumen útil','Microphone, monitors and useful volume'],['Verso, pre-coro y coro','Verse, pre-chorus and chorus']]},
 'voice-advanced-04-intervals':{src:'./academy-videos/voice-advanced-04-intervals.mp4',title:['Video IA · Afinación e intervalos','AI video · Pitch and intervals'],duration:'4–5 min',scenes:[['Escuchar la nota antes de cantarla','Hearing the note before singing it'],['Saltos 1→3 y 1→5','Leaps 1→3 and 1→5'],['Entrada directa sin deslizar','Direct entrance without sliding'],['Aplicación a entradas reales','Application to real entrances']]},
 'voice-advanced-05-harmony':{src:'./academy-videos/voice-advanced-05-harmony.mp4',title:['Video IA · Armonías','AI video · Harmony'],duration:'5–6 min',scenes:[['Raíz, tercera y quinta','Root, third and fifth'],['Cómo no volver a la melodía principal','How not to fall back to the main melody'],['Dónde entra y sale una segunda voz','Where a harmony part enters and exits'],['Arreglo vocal para un coro','Vocal arrangement for a chorus']]},
 'voice-advanced-06-endurance':{src:'./academy-videos/voice-advanced-06-endurance.mp4',title:['Video IA · Resistencia vocal','AI video · Vocal endurance'],duration:'4–5 min',scenes:[['Resistencia no es aguantar dolor','Endurance is not enduring pain'],['Distribución de carga durante el set','Distributing load through the set'],['Descansos, micrófono y monitoreo','Rests, microphone and monitoring'],['Señales para detenerse','Signals to stop']]},
 'voice-advanced-07-agility':{src:'./academy-videos/voice-advanced-07-agility.mp4',title:['Video IA · Agilidad y melismas','AI video · Agility and melismas'],duration:'4–5 min',scenes:[['Primero lento, luego rápido','Slow first, then fast'],['Notas identificables dentro del melisma','Identifiable notes inside the melisma'],['Tres repeticiones limpias','Three clean repetitions'],['Cuándo un adorno sirve a la canción','When an ornament serves the song']]},
 'voice-advanced-08-setlist':{src:'./academy-videos/voice-advanced-08-setlist.mp4',title:['Video IA · Preparar un setlist','AI video · Preparing a setlist'],duration:'5–6 min',scenes:[['Detectar frases exigentes','Finding demanding phrases'],['Revisar tonos oficiales','Reviewing official keys'],['Distribuir voces y descansos','Distributing voices and rests'],['Calentamiento según el repertorio','Warm-up based on repertoire']]}
};
const ACADEMY_PROGRESS_KEY='lagrey_academy_voice_progress_v1';
function loadAcademyProgress(){try{const raw=JSON.parse(localStorage.getItem(ACADEMY_PROGRESS_KEY)||'{}');return{completed:Array.isArray(raw.completed)?raw.completed:[],lastOpened:raw.lastOpened||null}}catch{return{completed:[],lastOpened:null}}}
function saveAcademyProgress(data){localStorage.setItem(ACADEMY_PROGRESS_KEY,JSON.stringify({completed:[...new Set(data.completed||[])],lastOpened:data.lastOpened||null}))}
function academyIsComplete(id){return loadAcademyProgress().completed.includes(id)}
function academyProgressCount(){return academyLessons.filter(l=>academyIsComplete(l.id)).length}
function academyProgressHtml(){const done=academyProgressCount(),pct=Math.round(done/academyLessons.length*100);return `<div class="academy-progress-card"><div class="academy-progress-copy"><b>${vtx('Tu progreso','Your progress')}</b><span>${done}/${academyLessons.length} ${vtx('clases completadas','lessons completed')}</span></div><div class="academy-progress-track"><span style="width:${pct}%"></span></div><strong>${pct}%</strong></div>`}
function rememberAcademyOpen(id){const p=loadAcademyProgress();p.lastOpened=id;saveAcademyProgress(p)}
function toggleAcademyComplete(id){const p=loadAcademyProgress(),set=new Set(p.completed);if(set.has(id))set.delete(id);else set.add(id);p.completed=[...set];p.lastOpened=id;saveAcademyProgress(p);translateVoiceShell();renderAcademyLesson(id,false)}
let ctx=null,stopToken=0,routineState=null,activeVoicePanel=null,academySceneTimer=0;
function translatedExercise(cat,i,e=exercises[cat]?.[i]){if(!e||voiceLang()!=='en')return e;const t=exerciseEN[cat]?.[i];return t?{...e,name:t[0],tip:t[1],why:t[2],example:t[3]}:e}
function categoryText(id){const c=categories.find(x=>x.id===id),t=shellCategories[id],en=voiceLang()==='en';return c&&t?{...c,title:t[en?1:0],desc:t[en?3:2]}:c}
function routineTitle(id){const pair=shellRoutines[id];return pair?pair[voiceLang()==='en'?1:0]:routines[id]?.title||''}
function localText(pair){return Array.isArray(pair)?pair[voiceLang()==='en'?1:0]:pair||''}
function academyLesson(id){return academyLessons.find(x=>x.id===id)}
function academyList(items){return `<ul>${(items||[]).map(x=>`<li>${localText(x)}</li>`).join('')}</ul>`}
function academyCardHtml(l,i){const done=academyIsComplete(l.id);return `<button class="voice-academy-card${done?' completed':''}" data-academy-lesson="${l.id}"><span class="voice-academy-number">${done?'✓':String(i+1).padStart(2,'0')}</span><span class="voice-academy-icon">${l.icon}</span><b>${localText(l.title)}</b><small>${localText(l.objective)}</small><em>${done?vtx('Completada','Completed'):l.minutes}</em></button>`}
function academyInteractiveHtml(id){const drills=academyInteractive[id];if(!drills?.length)return'';return `<section class="voice-academy-interactive"><h3>🎹 ${vtx('Práctica interactiva','Interactive practice')}</h3><p>${vtx('El piano toca primero y luego te deja espacio para repetir. Empieza en una nota cómoda y detente antes de sentir presión.','The piano plays first, then leaves space for you to repeat. Start on a comfortable note and stop before you feel pressure.')}</p><div class="voice-exercise-list">${drills.map((d,i)=>`<article class="voice-exercise voice-academy-drill"><h3>${localText(d.name)}</h3><div class="voice-pattern">${d.pattern.map(degreeLabel).join(' – ')}</div><p>${localText(d.tip)}</p><div class="voice-controls"><label>${vtx('Sílaba','Syllable')}<select data-ap-syllable>${d.syllables.map(s=>`<option>${s}</option>`).join('')}</select></label><label>${vtx('Nota inicial','Starting note')}<select data-ap-start><option value="48">C3 · Do3</option><option value="50">D3 · Re3</option><option value="52">E3 · Mi3</option><option value="53">F3 · Fa3</option><option value="55">G3 · Sol3</option><option value="57">A3 · La3</option><option value="60" selected>C4 · Do4</option></select></label><label>Tempo<input data-ap-tempo type="range" min="60" max="100" value="${d.tempo}"><span data-ap-tempo-label>${d.tempo} BPM</span></label><label>${vtx('Repeticiones','Repetitions')}<select data-ap-repeats><option>1</option><option selected>3</option><option>5</option></select></label><label>${vtx('Movimiento','Movement')}<select data-ap-shift><option value="0">${vtx('No mover','Do not move')}</option><option value="1" selected>+½ ${vtx('tono','step')}</option><option value="-1">−½ ${vtx('tono','step')}</option></select></label></div><div class="voice-play-row"><button class="btn primary" data-academy-play="${id}|${i}">▶ ${vtx('Escuchar y practicar','Listen and practice')}</button><button class="btn" data-academy-demo="${id}|${i}">🎹 ${vtx('Solo ejemplo','Example only')}</button><button class="btn" data-academy-stop>■ ${vtx('Detener','Stop')}</button></div><div class="voice-status" data-academy-status>${vtx('Listo. El piano tocará el patrón y después tendrás espacio para repetirlo.','Ready. The piano will play the pattern, then leave space for you to repeat it.')}</div></article>`).join('')}</div></section>`}
function academyVideoHtml(id){const v=academyVideos[id];if(!v)return'';const eager=id==='voice-advanced-02-passaggio',preload=eager?'auto':'metadata',poster=eager?' poster="./academy-videos/passaggio/scene-01.svg"':'';return `<section class="voice-academy-video"><div class="voice-academy-video-head"><div><span class="voice-badge">🎬 ${vtx('Video de la clase','Lesson video')}</span><h3>${localText(v.title)}</h3></div><span class="voice-academy-duration">${v.duration}</span></div><p>${vtx('El video se reproduce aquí mismo dentro de la clase. Puedes verlo en línea o cambiarlo a pantalla completa.','The video plays right here inside the lesson. You can watch it inline or switch to full screen.')}</p><div class="academy-video-player${eager?' has-video academy-video-eager':''}" data-academy-video-box="${id}"><video controls playsinline preload="${preload}"${poster} data-academy-video="${id}"><source src="${v.src}" type="video/mp4"></video><div class="academy-video-fallback"><div class="academy-video-icon">🎥</div><b>${vtx('Video todavía no disponible','Video not available yet')}</b><small>${vtx('Esta clase conservará su guía visual hasta que tenga su video final.','This lesson keeps its visual guide until its final video is available.')}</small><button class="btn primary" data-academy-story="${id}">▶ ${vtx('Ver guía audiovisual','View audiovisual guide')}</button></div></div><div class="academy-video-actions${eager?'':' hidden'}" data-academy-video-actions="${id}"><button class="btn" type="button" data-academy-fullscreen="${id}">⛶ ${vtx('Pantalla completa','Full screen')}</button></div><div class="academy-story hidden" data-academy-story-box="${id}"><div class="academy-story-progress"><span data-academy-story-progress></span></div><div class="academy-story-count" data-academy-story-count></div><div class="academy-story-scene" data-academy-story-scene></div><div class="voice-play-row"><button class="btn" data-story-prev="${id}">← ${vtx('Anterior','Previous')}</button><button class="btn primary" data-story-play="${id}">▶ ${vtx('Reproducir','Play')}</button><button class="btn" data-story-next="${id}">${vtx('Siguiente','Next')} →</button></div></div></section>`}
function shellTitle(el,value){if(!el)return;const icon=el.querySelector('.lg-section-icon');if(icon){const label=[...el.children].find(n=>n!==icon);if(label)label.textContent=value;else el.append(document.createTextNode(value));return}el.textContent=`🎤 ${value}`}
function translateVoiceShell(){const v=$('#voiceView');if(!v)return;const en=voiceLang()==='en';const back=v.querySelector('[data-voice-home]');if(back)back.textContent=vtx('← Volver','← Back');shellTitle(v.querySelector('.voice-hero h1'),vtx('Voz','Voice'));const hero=v.querySelector('.voice-hero p');if(hero)hero.textContent=vtx('Rutinas guiadas, ejemplos, sílabas variadas y patrones de piano.','Guided routines, examples, varied syllables and piano patterns.');const warning=v.querySelector(':scope > .voice-warning');if(warning)warning.innerHTML=en?'<b>Take care of your voice:</b> work in a comfortable range, without pain or pressure. If pain, significant voice loss or persistent discomfort appears, stop the exercise.':'<b>Cuida tu voz:</b> trabaja en una zona cómoda, sin dolor ni presión. Si aparece dolor, pérdida marcada de voz o molestia persistente, detén el ejercicio.';const headings=v.querySelectorAll(':scope > h2');if(headings[0])headings[0].textContent=vtx('Rutinas guiadas','Guided routines');if(headings[1])headings[1].textContent=vtx('Entrena por objetivo','Train by goal');const at=v.querySelector('[data-academy-title]'),ai=v.querySelector('[data-academy-intro]');if(at)at.textContent=vtx('🎓 Academia La Grey · Voz avanzada','🎓 La Grey Academy · Advanced voice');if(ai)ai.textContent=vtx('8 clases para llevar la técnica vocal al ensayo, el culto, las armonías y el repertorio real.','8 lessons that bring vocal technique into rehearsals, services, harmony and real repertoire.');const prog=v.querySelector('[data-academy-progress]');if(prog)prog.innerHTML=academyProgressHtml();const grid=v.querySelector('[data-academy-grid]');if(grid)grid.innerHTML=academyLessons.map(academyCardHtml).join('');Object.entries(shellRoutines).forEach(([id,pair])=>{const b=v.querySelector(`[data-routine="${id}"]`);if(!b)return;const title=b.querySelector('b'),small=b.querySelector('small');if(title)title.textContent=pair[en?1:0];if(small)small.textContent=vtx('La Grey te lleva paso a paso y toca los ejercicios en orden.','La Grey guides you step by step and plays the exercises in order.')});Object.entries(shellCategories).forEach(([id,t])=>{const b=v.querySelector(`[data-voice-cat="${id}"]`);if(!b)return;const title=b.querySelector('b'),small=b.querySelector('small');if(title)title.textContent=t[en?1:0];if(small)small.textContent=t[en?3:2]})}
function injectStyle(){if($('#voiceCss'))return;const l=document.createElement('link');l.id='voiceCss';l.rel='stylesheet';l.href='voice.css';document.head.appendChild(l)}
function build(){injectStyle();const homeGrid=$('#home .home-grid');if(homeGrid&&!homeGrid.querySelector('[data-open="voice"]')){const b=document.createElement('button');b.className='card';b.dataset.open='voice';b.innerHTML=`<div class="icon">🎤✨</div><h2>${vtx('Voz','Voice')}</h2><div class="muted">${vtx('Calentamiento y entrenamiento vocal','Warm-ups and vocal training')}</div><div class="count">${vtx('Rutinas guiadas + piano','Guided routines + piano')}</div>`;homeGrid.appendChild(b)}if($('#voiceView')){translateVoiceShell();return}const s=document.createElement('section');s.id='voiceView';s.className='view hidden';s.innerHTML=`<button class="back" data-voice-home>← Volver</button><div class="voice-hero"><h1>🎤 Voz</h1><p>Rutinas guiadas, ejemplos, sílabas variadas y patrones de piano.</p></div><div class="voice-warning"><b>Cuida tu voz:</b> trabaja en una zona cómoda, sin dolor ni presión. Si aparece dolor, pérdida marcada de voz o molestia persistente, detén el ejercicio.</div><h2>Rutinas guiadas</h2><div class="voice-routines">${Object.entries(routines).map(([id,r])=>`<button class="voice-routine" data-routine="${id}"><b>${r.title}</b><br><small>La Grey te lleva paso a paso y toca los ejercicios en orden.</small></button>`).join('')}</div><h2>Entrena por objetivo</h2><div class="voice-grid">${categories.map(c=>`<button class="voice-card" data-voice-cat="${c.id}"><span class="voice-icon">${c.icon}</span><b>${c.title}</b><small>${c.desc}</small></button>`).join('')}</div><h2 data-academy-title>🎓 Academia La Grey · Voz avanzada</h2><p class="voice-academy-intro" data-academy-intro>8 clases para llevar la técnica vocal al ensayo, el culto, las armonías y el repertorio real.</p><div data-academy-progress>${academyProgressHtml()}</div><div class="voice-academy-grid" data-academy-grid>${academyLessons.map(academyCardHtml).join('')}</div><div id="voicePanel" class="voice-panel hidden"></div>`;document.querySelector('main').appendChild(s);translateVoiceShell()}
function showVoice(){build();translateVoiceShell();$$('.view').forEach(v=>v.classList.add('hidden'));$('#voiceView').classList.remove('hidden');$$('nav button').forEach(b=>b.classList.remove('active'));window.scrollTo(0,0)}
function goHome(){stopPlayback();$('#voiceView')?.classList.add('hidden');$('#home')?.classList.remove('hidden');window.scrollTo(0,0)}
function degreeLabel(n){const map={0:'1',2:'2',4:'3',5:'4',7:'5',9:'6',11:'7',12:'8',16:'10'};return map[n]||'•'}
function exerciseHtml(cat,i,source){const e=translatedExercise(cat,i,source);if(e.timed)return `<article class="voice-exercise"><h3>${e.name}</h3><p><b>${vtx('Para qué sirve:','What it does:')}</b> ${e.why}</p><p><b>${vtx('Cómo hacerlo:','How to do it:')}</b> ${e.tip}</p><p><b>${vtx('Ejemplo:','Example:')}</b> ${e.example}</p><div class="voice-syllable-chip">${e.syllables.join(' · ')}</div><div class="voice-play-row"><button class="btn primary" data-timer="${cat}:${i}">▶ ${vtx('Iniciar','Start')} ${e.duration||30}s</button><button class="btn" data-stop>■ ${vtx('Detener','Stop')}</button></div><div class="voice-status" id="status-${cat}-${i}">${vtx('Listo para comenzar.','Ready to begin.')}</div></article>`;return `<article class="voice-exercise"><h3>${e.name}</h3><div class="voice-pattern">${e.pattern.map(degreeLabel).join(' – ')}</div><p><b>${vtx('Para qué sirve:','What it does:')}</b> ${e.why}</p><p><b>${vtx('Cómo hacerlo:','How to do it:')}</b> ${e.tip}</p><p><b>${vtx('Ejemplo:','Example:')}</b> ${e.example}</p><div class="voice-controls"><label>${vtx('Sílaba','Syllable')}<select data-syllable>${e.syllables.map(s=>`<option>${s}</option>`).join('')}</select></label><label>${vtx('Nota inicial','Starting note')}<select data-start><option value="48">C3 · Do3</option><option value="50">D3 · Re3</option><option value="52">E3 · Mi3</option><option value="53">F3 · Fa3</option><option value="55">G3 · Sol3</option><option value="57">A3 · La3</option><option value="60" selected>C4 · Do4</option></select></label><label>Tempo<input data-tempo type="range" min="55" max="150" value="${e.tempo||90}"><span data-tempo-label>${e.tempo||90} BPM</span></label><label>${vtx('Repeticiones','Repetitions')}<select data-repeats><option>1</option><option selected>3</option><option>5</option><option>8</option></select></label><label>${vtx('Movimiento','Movement')}<select data-shift><option value="0">${vtx('No mover','Do not move')}</option><option value="1" selected>+½ ${vtx('tono','step')}</option><option value="-1">−½ ${vtx('tono','step')}</option></select></label></div><div class="voice-play-row"><button class="btn primary" data-play="${cat}:${i}">▶ ${vtx('Escuchar y practicar','Listen and practice')}</button><button class="btn" data-demo="${cat}:${i}">🎹 ${vtx('Solo ejemplo','Example only')}</button><button class="btn" data-stop>■ ${vtx('Detener','Stop')}</button></div><div class="voice-status" id="status-${cat}-${i}">${vtx('Listo. El piano tocará el patrón y te indicará la sílaba elegida.','Ready. The piano will play the pattern and show the selected syllable.')}</div></article>`}
function renderCategory(id,scroll=true){const c=categoryText(id),p=$('#voicePanel');if(!c||!p)return;activeVoicePanel={type:'category',id};p.classList.remove('hidden');p.innerHTML=`<span class="voice-badge">${c.icon} ${c.title}</span><h2>${c.title}</h2><p>${c.desc}</p><div class="voice-exercise-list">${(exercises[id]||[]).map((e,i)=>exerciseHtml(id,i,e)).join('')}</div>`;wireExercises();if(scroll)p.scrollIntoView({behavior:'smooth',block:'start'})}
function renderAcademyLesson(id,scroll=true){const l=academyLesson(id),p=$('#voicePanel');if(!l||!p)return;stopPlayback();rememberAcademyOpen(id);activeVoicePanel={type:'academy',id};const index=academyLessons.indexOf(l),targetLabel=l.target.type==='routine'?routineTitle(l.target.id):categoryText(l.target.id)?.title||'';p.classList.remove('hidden');p.innerHTML=`<article class="voice-academy-lesson"><div class="voice-academy-head"><span class="voice-badge">🎓 ${vtx('Clase avanzada','Advanced lesson')} ${index+1}/8</span><span class="voice-academy-duration">${l.minutes}</span></div><h2>${l.icon} ${localText(l.title)}</h2>${academyVideoHtml(id)}<section><h3>${vtx('Objetivo','Goal')}</h3><p>${localText(l.objective)}</p></section><section><h3>${vtx('Concepto clave','Key concept')}</h3><p>${localText(l.concept)}</p></section><div class="voice-academy-columns"><section><h3>${vtx('Qué escuchar o sentir','What to listen or feel for')}</h3>${academyList(l.feel)}</section><section class="academy-caution"><h3>${vtx('Qué evitar','What to avoid')}</h3>${academyList(l.avoid)}</section></div><section><h3>${vtx('Práctica guiada','Guided practice')}</h3>${academyList(l.practice)}</section>${academyInteractiveHtml(id)}<section class="academy-ministry"><h3>${vtx('Aplicación al ministerio','Ministry application')}</h3><p>${localText(l.ministry)}</p></section><section><h3>${vtx('Autoevaluación','Self-check')}</h3>${academyList(l.check)}</section><div class="voice-warning"><b>${vtx('Seguridad vocal:','Vocal safety:')}</b> ${vtx('si aparece dolor, ardor, pérdida marcada de voz o ronquera que empeora, detén la práctica.','if pain, burning, significant voice loss or worsening hoarseness appears, stop practicing.')}</div><div class="voice-play-row"><button class="btn ${academyIsComplete(id)?'academy-complete-on':'primary'}" data-academy-complete="${id}">${academyIsComplete(id)?'✓ '+vtx('Clase completada','Lesson completed'):'○ '+vtx('Marcar como completada','Mark as completed')}</button><button class="btn primary" data-academy-practice="${l.target.type}:${l.target.id}">🎹 ${vtx('Practicar en','Practice in')} ${targetLabel}</button>${index>0?`<button class="btn" data-academy-prev="${academyLessons[index-1].id}">← ${vtx('Clase anterior','Previous lesson')}</button>`:''}${index<academyLessons.length-1?`<button class="btn" data-academy-next="${academyLessons[index+1].id}">${vtx('Siguiente clase','Next lesson')} →</button>`:''}</div><p class="voice-academy-foot">${vtx('Contenido preparado con ayuda de IA y entregado como lección fija dentro de La Grey; no se genera una técnica improvisada en tiempo real.','Content prepared with AI assistance and delivered as a fixed lesson inside La Grey; vocal technique is not improvised in real time.')}</p></article>`;wireAcademyInteractive();wireAcademyVideo(id);if(scroll)p.scrollIntoView({behavior:'smooth',block:'start'})}
function wireAcademyInteractive(){$$('#voicePanel [data-ap-tempo]').forEach(r=>r.oninput=()=>{const label=r.parentElement.querySelector('[data-ap-tempo-label]');if(label)label.textContent=r.value+' BPM'})}
function wireExercises(){$$('#voicePanel [data-tempo]').forEach(r=>r.oninput=()=>r.parentElement.querySelector('[data-tempo-label]').textContent=r.value+' BPM');$$('[data-play]').forEach(b=>b.onclick=()=>playExercise(b,false));$$('[data-demo]').forEach(b=>b.onclick=()=>playExercise(b,true));$$('[data-stop]').forEach(b=>b.onclick=stopPlayback);$$('[data-timer]').forEach(b=>b.onclick=()=>startTimer(b))}
function midiFreq(m){return 440*Math.pow(2,(m-69)/12)}
function noteLabel(m){const n=NOTE_NAMES[((m%12)+12)%12],o=Math.floor(m/12)-1;return `${LATIN[n]||n}${o}`}
function audio(){if(!ctx)ctx=new (window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}
function pianoNote(midi,when,dur=.32){const a=audio(),gain=a.createGain(),o1=a.createOscillator(),o2=a.createOscillator();o1.type='triangle';o2.type='sine';o1.frequency.value=midiFreq(midi);o2.frequency.value=midiFreq(midi)*2;gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(.16,when+.015);gain.gain.exponentialRampToValueAtTime(.0001,when+dur);o1.connect(gain);o2.connect(gain);gain.connect(a.destination);o1.start(when);o2.start(when);o1.stop(when+dur+.03);o2.stop(when+dur+.03)}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function playPattern(e,root,tempo,token,status,syllable){const beat=60/tempo;let t=ctx.currentTime+.08;e.pattern.forEach(step=>{pianoNote(root+step,t,Math.max(.18,beat*.72));t+=beat});if(status)status.textContent=`🎹 ${noteLabel(root)} · ${tempo} BPM · ${vtx('canta','sing')} “${syllable}”`;await wait(e.pattern.length*beat*1000+250);return token===stopToken}
async function playAcademyInteractive(btn,demoOnly){const [lessonId,indexText]=btn.dataset[demoOnly?'academyDemo':'academyPlay'].split('|'),drill=academyInteractive[lessonId]?.[Number(indexText)],box=btn.closest('.voice-academy-drill');if(!drill||!box)return;stopPlayback();const token=++stopToken,start=Number(box.querySelector('[data-ap-start]').value),tempo=Number(box.querySelector('[data-ap-tempo]').value),reps=demoOnly?1:Number(box.querySelector('[data-ap-repeats]').value),shift=demoOnly?0:Number(box.querySelector('[data-ap-shift]').value),syllable=box.querySelector('[data-ap-syllable]').value,status=box.querySelector('[data-academy-status]');audio();for(let r=0;r<reps;r++){if(token!==stopToken)return;const root=start+(r*shift);status.textContent=`${vtx('Repetición','Repetition')} ${r+1}/${reps} · ${noteLabel(root)} · “${syllable}”`;if(!(await playPattern(drill,root,tempo,token,status,syllable)))return;if(!demoOnly){status.textContent=`🎤 ${vtx('Ahora repítelo tú con','Now repeat it with')} “${syllable}” · ${vtx('sin empujar','without pushing')}`;await wait(Math.max(1100,drill.pattern.length*(60/tempo)*720))}}status.textContent=demoOnly?vtx('✅ Ejemplo terminado.','✅ Example finished.'):vtx('✅ Serie terminada. Si siguió cómoda, puedes repetir o subir solo un semitono.','✅ Set finished. If it stayed comfortable, repeat it or move up only one semitone.')}
async function playExercise(btn,demoOnly){stopPlayback();const token=++stopToken,[cat,idx]=btn.dataset[demoOnly?'demo':'play'].split(':'),e=exercises[cat][Number(idx)],box=btn.closest('.voice-exercise'),start=Number(box.querySelector('[data-start]').value),tempo=Number(box.querySelector('[data-tempo]').value),reps=demoOnly?1:Number(box.querySelector('[data-repeats]').value),shift=demoOnly?0:Number(box.querySelector('[data-shift]').value),syllable=box.querySelector('[data-syllable]').value,status=$(`#status-${cat}-${idx}`);audio();for(let r=0;r<reps;r++){if(token!==stopToken)return;const root=start+r*shift;status.textContent=`${vtx('Repetición','Repetition')} ${r+1}/${reps} · ${noteLabel(root)} · “${syllable}”`;if(!(await playPattern(e,root,tempo,token,status,syllable)))return;if(!demoOnly){status.textContent=`🎤 ${vtx('Ahora repítelo tú con','Now repeat it with')} “${syllable}”`;await wait(Math.max(900,e.pattern.length*(60/tempo)*700));}}status.textContent=demoOnly?vtx('✅ Ejemplo terminado.','✅ Example finished.'):vtx('✅ Ejercicio terminado. Si se sintió cómodo, puedes repetirlo.','✅ Exercise finished. If it felt comfortable, you can repeat it.')}
function stopPlayback(){stopToken++;routineState=null;clearTimeout(academySceneTimer);academySceneTimer=0;$$('.voice-status').forEach(s=>{if(!s.textContent.startsWith('✅'))s.textContent=vtx('Detenido.','Stopped.')})}
function startTimer(btn){const [cat,idx]=btn.dataset.timer.split(':'),source=exercises[cat][Number(idx)],e=translatedExercise(cat,Number(idx),source),status=$(`#status-${cat}-${idx}`);stopPlayback();const token=++stopToken;let left=e.duration||30;status.textContent=`⏱️ ${left}s · ${e.example}`;const id=setInterval(()=>{if(token!==stopToken){clearInterval(id);return}left--;status.textContent=left>0?`⏱️ ${left}s · ${e.example}`:vtx('✅ Terminado. Respira normalmente.','✅ Finished. Breathe normally.');if(left<=0)clearInterval(id)},1000)}
function showRoutine(id,scroll=true){const r=routines[id],p=$('#voicePanel');if(!r||!p)return;activeVoicePanel={type:'routine',id};p.classList.remove('hidden');p.innerHTML=`<span class="voice-badge">${vtx('Rutina guiada','Guided routine')}</span><h2>${routineTitle(id)}</h2><p>${vtx('No es una lista para leer: pulsa iniciar y La Grey irá avanzando ejercicio por ejercicio.','This is not a list to read: press start and La Grey will advance exercise by exercise.')}</p><div id="routineProgress" class="routine-progress"><div class="routine-bar"><span></span></div><div id="routineStepLabel">${vtx('Preparado para comenzar.','Ready to begin.')}</div></div><div class="voice-play-row"><button class="btn primary" data-start-routine="${id}">▶ ${vtx('Iniciar rutina completa','Start full routine')}</button><button class="btn" data-routine-stop>■ ${vtx('Detener','Stop')}</button></div><div id="routineCurrent" class="routine-current">${vtx('Aquí aparecerá el ejercicio actual, la sílaba y lo que debes hacer.','The current exercise, syllable and instructions will appear here.')}</div><div class="routine-list">${r.steps.map((s,i)=>{const e=translatedExercise(s[0],s[1]);return `<div class="routine-item" data-routine-item="${i}"><b>${i+1}. ${e.name}</b><small>${e.timed?e.example:`${e.syllables[0]} · ${e.tip}`}</small></div>`}).join('')}</div>`;p.querySelector('[data-start-routine]').onclick=()=>runRoutine(id);p.querySelector('[data-routine-stop]').onclick=stopPlayback;if(scroll)p.scrollIntoView({behavior:'smooth',block:'start'})}
async function runRoutine(id){stopPlayback();audio();const token=++stopToken,r=routines[id],current=$('#routineCurrent'),label=$('#routineStepLabel'),bar=$('#routineProgress .routine-bar span');for(let i=0;i<r.steps.length;i++){if(token!==stopToken)return;$$('[data-routine-item]').forEach((x,j)=>x.classList.toggle('active',j===i));bar.style.width=((i/r.steps.length)*100)+'%';const [cat,idx,duration]=r.steps[i],e=exercises[cat][idx],te=translatedExercise(cat,idx,e);label.textContent=`${vtx('Paso','Step')} ${i+1} ${vtx('de','of')} ${r.steps.length}`;if(e.timed){current.innerHTML=`<b>${te.name}</b><br>${te.example}<br><span class="voice-syllable-chip">${e.syllables[0]}</span>`;let left=Math.min(duration,e.duration||duration);while(left>0){if(token!==stopToken)return;label.textContent=`${vtx('Paso','Step')} ${i+1}/${r.steps.length} · ${left}s`;await wait(1000);left--;}}else{const syll=e.syllables[0],tempo=e.tempo||90,start=60,reps=Math.max(2,Math.min(5,Math.round(duration/25)));current.innerHTML=`<b>${te.name}</b><br>${vtx('Canta con','Sing with')} <b>${syll}</b>. ${te.tip}<br><small>${vtx('El piano tocará y luego tendrás tiempo para repetir.','The piano will play and then you will have time to repeat.')}</small>`;for(let rep=0;rep<reps;rep++){if(token!==stopToken)return;const root=start+rep;label.textContent=`${vtx('Paso','Step')} ${i+1}/${r.steps.length} · ${vtx('repetición','repetition')} ${rep+1}/${reps} · ${noteLabel(root)}`;if(!(await playPattern(e,root,tempo,token,null,syll)))return;await wait(Math.max(900,e.pattern.length*(60/tempo)*650));}}}bar.style.width='100%';label.textContent=vtx('✅ Rutina completada','✅ Routine completed');current.innerHTML=vtx('<b>Muy bien.</b><br>La rutina terminó. Si vas a cantar ahora, mantente hidratado y evita forzar la voz.','<b>Well done.</b><br>The routine is finished. If you are going to sing now, stay hydrated and avoid forcing your voice.');$$('[data-routine-item]').forEach(x=>x.classList.remove('active'))}
function wireAcademyVideo(id){const video=$(`[data-academy-video="${id}"]`),box=$(`[data-academy-video-box="${id}"]`),actions=$(`[data-academy-video-actions="${id}"]`),eager=id==='voice-advanced-02-passaggio';if(video&&box){const showVideo=()=>{box.classList.add('has-video');actions?.classList.remove('hidden')},showFallback=()=>{box.classList.remove('has-video');actions?.classList.add('hidden')};if(eager||video.readyState>=1)showVideo();video.addEventListener('loadedmetadata',showVideo,{once:true});video.addEventListener('canplay',showVideo,{once:true});video.addEventListener('error',showFallback,{once:true});try{video.load()}catch(_){}const fullBtn=$(`[data-academy-fullscreen="${id}"]`);if(fullBtn)fullBtn.onclick=async()=>{try{if(document.fullscreenElement&&document.exitFullscreen){await document.exitFullscreen();return}if(video.requestFullscreen){await video.requestFullscreen();return}if(video.webkitEnterFullscreen){video.webkitEnterFullscreen();return}if(video.webkitRequestFullscreen){video.webkitRequestFullscreen();return}}catch(error){console.warn('[La Grey Academia] No se pudo activar pantalla completa',error)}}}renderAcademyStory(id,0)}
function renderAcademyStory(id,index){const v=academyVideos[id],box=$(`[data-academy-story-box="${id}"]`);if(!v||!box)return;const scenes=v.scenes||[],safe=Math.max(0,Math.min(scenes.length-1,index));box.dataset.scene=String(safe);const scene=box.querySelector('[data-academy-story-scene]'),count=box.querySelector('[data-academy-story-count]'),bar=box.querySelector('[data-academy-story-progress]');if(scene)scene.textContent=localText(scenes[safe]);if(count)count.textContent=`${vtx('Escena','Scene')} ${safe+1}/${scenes.length}`;if(bar)bar.style.width=((safe+1)/scenes.length*100)+'%'}
function openAcademyStory(id){const box=$(`[data-academy-story-box="${id}"]`);if(!box)return;box.classList.remove('hidden');renderAcademyStory(id,Number(box.dataset.scene||0));box.scrollIntoView({behavior:'smooth',block:'nearest'})}
function moveAcademyStory(id,delta){clearTimeout(academySceneTimer);const v=academyVideos[id],box=$(`[data-academy-story-box="${id}"]`);if(!v||!box)return;renderAcademyStory(id,Math.max(0,Math.min(v.scenes.length-1,Number(box.dataset.scene||0)+delta)))}
function playAcademyStory(id){clearTimeout(academySceneTimer);openAcademyStory(id);const v=academyVideos[id],box=$(`[data-academy-story-box="${id}"]`);if(!v||!box)return;const step=()=>{const i=Number(box.dataset.scene||0);if(i>=v.scenes.length-1){academySceneTimer=0;return}renderAcademyStory(id,i+1);academySceneTimer=setTimeout(step,3200)};academySceneTimer=setTimeout(step,3200)}
function refreshVoiceLanguage(){translateVoiceShell();if(!activeVoicePanel)return;stopPlayback();if(activeVoicePanel.type==='category')renderCategory(activeVoicePanel.id,false);else if(activeVoicePanel.type==='routine')showRoutine(activeVoicePanel.id,false);else if(activeVoicePanel.type==='academy')renderAcademyLesson(activeVoicePanel.id,false)}
function onCapture(ev){const voice=ev.target.closest('[data-open="voice"]');if(voice){ev.preventDefault();ev.stopPropagation();showVoice();return}const back=ev.target.closest('[data-voice-home]');if(back){ev.preventDefault();ev.stopPropagation();goHome();return}const cat=ev.target.closest('[data-voice-cat]');if(cat){ev.preventDefault();renderCategory(cat.dataset.voiceCat);return}const routine=ev.target.closest('[data-routine]');if(routine){ev.preventDefault();showRoutine(routine.dataset.routine);return}const lesson=ev.target.closest('[data-academy-lesson]');if(lesson){ev.preventDefault();renderAcademyLesson(lesson.dataset.academyLesson);return}const complete=ev.target.closest('[data-academy-complete]');if(complete){ev.preventDefault();toggleAcademyComplete(complete.dataset.academyComplete);return}const ap=ev.target.closest('[data-academy-play]');if(ap){ev.preventDefault();playAcademyInteractive(ap,false);return}const ad=ev.target.closest('[data-academy-demo]');if(ad){ev.preventDefault();playAcademyInteractive(ad,true);return}const astop=ev.target.closest('[data-academy-stop]');if(astop){ev.preventDefault();stopPlayback();return}const story=ev.target.closest('[data-academy-story]');if(story){ev.preventDefault();openAcademyStory(story.dataset.academyStory);return}const sp=ev.target.closest('[data-story-play]');if(sp){ev.preventDefault();playAcademyStory(sp.dataset.storyPlay);return}const sprev=ev.target.closest('[data-story-prev]');if(sprev){ev.preventDefault();moveAcademyStory(sprev.dataset.storyPrev,-1);return}const snext=ev.target.closest('[data-story-next]');if(snext){ev.preventDefault();moveAcademyStory(snext.dataset.storyNext,1);return}const prev=ev.target.closest('[data-academy-prev]');if(prev){ev.preventDefault();renderAcademyLesson(prev.dataset.academyPrev);return}const next=ev.target.closest('[data-academy-next]');if(next){ev.preventDefault();renderAcademyLesson(next.dataset.academyNext);return}const practice=ev.target.closest('[data-academy-practice]');if(practice){ev.preventDefault();const [type,id]=practice.dataset.academyPractice.split(':');if(type==='routine')showRoutine(id);else renderCategory(id);return}if(!$('#voiceView')?.classList.contains('hidden')&&ev.target.closest('nav button,[data-home],[data-nav]'))stopPlayback()}
window.LAGREY_REFRESH_VOICE_BASE_I18N=refreshVoiceLanguage;
new MutationObserver(muts=>{if(muts.some(m=>m.attributeName==='lang'))refreshVoiceLanguage()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
document.addEventListener('click',onCapture,true);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();