(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const lang=()=>localStorage.getItem('lagrey_language')==='en'?'en':'es',tx=(es,en)=>lang()==='en'?en:es;
const NAMES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const LATIN={'C':'Do','C#':'Do#','D':'Re','D#':'Re#','E':'Mi','F':'Fa','F#':'Fa#','G':'Sol','G#':'Sol#','A':'La','A#':'La#','B':'Si'};
const RANGE_KEY='lagrey_voice_range_v1',PRESET_KEY='lagrey_voice_preset_v1';
let micCtx=null,micStream=null,analyser=null,micRaf=0,buf=null,currentMidi=null,currentCents=0,stableMidi=null,lastNotes=[];
let rangeScan=null,groupToken=0,refCtx=null,currentTool=null;
const presets={
 neutral:{label:['Sin perfil · zona media','No profile · middle range'],start:60,desc:['La Grey comienza en Do4 y tú ajustas según comodidad.','La Grey starts at C4 and you adjust according to comfort.']},
 soprano:{label:['Soprano · inicio orientativo','Soprano · suggested start'],start:60,desc:['Empieza en una zona media y sube solo mientras siga fácil.','Start in a middle range and move up only while it remains easy.']},
 alto:{label:['Alto / mezzo · inicio orientativo','Alto / mezzo · suggested start'],start:57,desc:['Empieza un poco más abajo para trabajar cómodamente.','Start a little lower so you can work comfortably.']},
 tenor:{label:['Tenor · inicio orientativo','Tenor · suggested start'],start:52,desc:['Comienza en Mi3 y ajusta según tu voz real.','Start at E3 and adjust according to your actual voice.']},
 baritone:{label:['Barítono · inicio orientativo','Baritone · suggested start'],start:48,desc:['Comienza en Do3 y sube progresivamente.','Start at C3 and move up gradually.']},
 bass:{label:['Bajo · inicio orientativo','Bass · suggested start'],start:45,desc:['Comienza en La2 y evita fabricar graves.','Start at A2 and avoid forcing artificial low notes.']}
};
const groupSteps=[
 {title:['1. Preparar cuerpo y aire','1. Prepare body and breath'],seconds:45,kind:'timer',instruction:['Postura libre. Inhalen 4 tiempos y suelten en SSS sin empujar.','Relaxed posture. Inhale for 4 counts and release on SSS without pushing.']},
 {title:['2. Trino de labios','2. Lip trill'],seconds:70,kind:'pattern',root:52,pattern:[0,2,4,5,7,5,4,2,0],syllable:'Brrr',instruction:['Todos suaves. El piano subirá por semitonos.','Keep everyone light. The piano will move up by semitones.']},
 {title:['3. Resonancia','3. Resonance'],seconds:70,kind:'pattern',root:53,pattern:[0,2,4,2,0],syllable:'MMM → MA',instruction:['Conserven la facilidad del MMM al abrir a MA.','Keep the ease of MMM when opening to MA.']},
 {title:['4. Afinación en grupo','4. Group tuning'],seconds:75,kind:'pattern',root:55,pattern:[0,4,7,4,0],syllable:'NO',instruction:['Escuchen primero y repitan juntos sin arrastrar las notas.','Listen first, then repeat together without sliding between notes.']},
 {title:['5. Rango medio','5. Middle range'],seconds:85,kind:'pattern',root:52,pattern:[0,2,4,5,7,9,7,5,4,2,0],syllable:'NU',instruction:['No compitan por subir. Cada persona se detiene donde sigue cómoda.','Do not compete to sing higher. Each person stops where the voice remains comfortable.']},
 {title:['6. Agilidad','6. Agility'],seconds:70,kind:'pattern',root:53,pattern:[0,2,4,5,7,5,4,2,0],syllable:'DA-GA',instruction:['Ligero y rítmico; claridad antes que velocidad.','Keep it light and rhythmic; clarity before speed.']},
 {title:['7. Dicción','7. Diction'],seconds:70,kind:'pattern',root:55,pattern:[0,2,4,5,7,5,4,2,0],syllable:'MA-ME-MI-MO-MU',instruction:['Vocales claras, mandíbula libre.','Clear vowels, relaxed jaw.']},
 {title:['8. Listos para cantar','8. Ready to sing'],seconds:35,kind:'timer',instruction:['Respiren normal, hablen una frase del repertorio y mantengan la voz natural.','Breathe normally, speak a line from the setlist and keep the voice natural.']}
];
const pick=a=>Array.isArray(a)?a[lang()==='en'?1:0]:a;
function midiFreq(m){return 440*Math.pow(2,(m-69)/12)}
function freqMidi(f){return 69+12*Math.log2(f/440)}
function noteLabel(m){if(m==null)return'--';const r=Math.round(m),n=NAMES[(r%12+12)%12],o=Math.floor(r/12)-1;return `${LATIN[n]||n}${o} · ${n}${o}`}
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function inject(){const view=$('#voiceView');if(!view||$('#voiceProTools'))return false;const panel=document.createElement('div');panel.id='voiceProTools';panel.className='voice-pro-tools';panel.innerHTML=`
<h2 data-vpro-title></h2><p class="voice-pro-intro" data-vpro-intro></p>
<div class="voice-pro-grid">
 <button class="voice-pro-card" data-vpro="pitch"><span>🎯</span><b></b><small></small></button>
 <button class="voice-pro-card" data-vpro="range"><span>↕️</span><b></b><small></small></button>
 <button class="voice-pro-card" data-vpro="preset"><span>👤</span><b></b><small></small></button>
 <button class="voice-pro-card" data-vpro="group"><span>👥</span><b></b><small></small></button>
</div><div id="voiceProPanel" class="voice-pro-panel hidden"></div>`;
 const routines=view.querySelector('.voice-routines');if(routines)routines.parentNode.insertBefore(panel,routines);else view.appendChild(panel);
 panel.addEventListener('click',e=>{const b=e.target.closest('[data-vpro]');if(b)showTool(b.dataset.vpro)});
 refreshToolCards();observeExercisePanel();return true}
function refreshToolCards(){const root=$('#voiceProTools');if(!root)return;const cards={
 pitch:[tx('Detector y afinación','Pitch detector and tuning'),tx('Ve tu nota y qué tan cerca estás del objetivo.','See your note and how close you are to the target.')],
 range:[tx('Mi rango cómodo','My comfortable range'),tx('Prueba, guarda y reutiliza tu zona de trabajo.','Test, save and reuse your working range.')],
 preset:[tx('Perfil vocal','Vocal profile'),tx('Soprano, alto, tenor, barítono o bajo como punto de partida.','Use soprano, alto, tenor, baritone or bass as a starting point.')],
 group:[tx('Calentamiento grupal','Group warm-up'),tx('Una sesión guiada para ensayo o culto.','A guided session for rehearsal or worship.')]
 };const title=root.querySelector('[data-vpro-title]'),intro=root.querySelector('[data-vpro-intro]');if(title)title.textContent=tx('🎙️ Herramientas de voz','🎙️ Voice tools');if(intro)intro.textContent=tx('Usa el micrófono para ver tu nota, practicar afinación, guardar tu rango cómodo y preparar a todo el grupo.','Use the microphone to see your note, practice tuning, save your comfortable range and prepare the whole group.');Object.entries(cards).forEach(([id,v])=>{const b=root.querySelector(`[data-vpro="${id}"]`);if(!b)return;b.querySelector('b').textContent=v[0];b.querySelector('small').textContent=v[1]})}
function showTool(id){stopGroup();currentTool=id;const p=$('#voiceProPanel');p.classList.remove('hidden');if(id==='pitch')renderPitch(p);if(id==='range')renderRange(p);if(id==='preset')renderPreset(p);if(id==='group')renderGroup(p);p.scrollIntoView({behavior:'smooth',block:'start'})}
function renderPitch(p){p.innerHTML=`<span class="voice-badge">🎯 ${tx('Micrófono','Microphone')}</span><h2>${tx('Detector de nota y afinación','Pitch detector and tuning')}</h2><p>${tx('Canta una nota cómoda. La Grey muestra la nota más cercana y los cents de diferencia.','Sing a comfortable note. La Grey shows the nearest note and the difference in cents.')}</p><div class="pitch-live"><div id="vproNote" class="pitch-note">--</div><div id="vproHz" class="pitch-hz">${tx('Micrófono apagado','Microphone off')}</div><div class="pitch-meter"><div class="pitch-center"></div><div id="vproNeedle" class="pitch-needle"></div></div><div class="pitch-labels"><span>♭ ${tx('bajo','low')}</span><span id="vproCents">0 cents</span><span>${tx('alto','high')} ♯</span></div></div><div class="voice-controls"><label>${tx('Nota objetivo','Target note')}<select id="vproTarget">${[48,50,52,53,55,57,59,60,62,64,65,67,69,71,72].map(m=>`<option value="${m}" ${m===60?'selected':''}>${noteLabel(m)}</option>`).join('')}</select></label></div><div class="voice-play-row"><button class="btn primary" id="vproMic">🎙️ ${tx('Activar micrófono','Activate microphone')}</button><button class="btn" id="vproReference">🎹 ${tx('Oír objetivo','Hear target')}</button><button class="btn" id="vproMicStop">■ ${tx('Detener','Stop')}</button></div><div id="vproAdvice" class="voice-status">${tx('Activa el micrófono y canta sin gritar.','Activate the microphone and sing without shouting.')}</div>`;$('#vproMic').onclick=startMic;$('#vproMicStop').onclick=stopMic;$('#vproReference').onclick=()=>playReference(Number($('#vproTarget').value));}
function renderRange(p){const saved=loadRange();p.innerHTML=`<span class="voice-badge">↕️ ${tx('Personal','Personal')}</span><h2>${tx('Mi rango cómodo','My comfortable range')}</h2><p>${tx('Esto no clasifica tu voz. Guarda solo notas que puedas producir con comodidad, sin presión.','This does not classify your voice. Save only notes you can produce comfortably, without pressure.')}</p><div class="range-summary"><div><small>${tx('Grave cómodo','Comfortable low')}</small><b id="rangeLow">${saved?.low!=null?noteLabel(saved.low):'—'}</b></div><div><small>${tx('Agudo cómodo','Comfortable high')}</small><b id="rangeHigh">${saved?.high!=null?noteLabel(saved.high):'—'}</b></div><div><small>${tx('Extensión guardada','Saved range')}</small><b id="rangeSpan">${saved?rangeSpan(saved):'—'}</b></div></div><div class="pitch-live compact"><div id="vproNote" class="pitch-note">--</div><div id="vproHz" class="pitch-hz">${tx('Activa el micrófono','Activate the microphone')}</div></div><div class="voice-play-row"><button class="btn primary" id="rangeMic">🎙️ ${tx('Activar micrófono','Activate microphone')}</button><button class="btn" id="rangeAuto">▶ ${tx('Prueba guiada 20 s','Guided test 20 s')}</button><button class="btn" id="rangeLowBtn">↓ ${tx('Guardar como grave','Save as low')}</button><button class="btn" id="rangeHighBtn">↑ ${tx('Guardar como agudo','Save as high')}</button></div><div id="rangeGuide" class="voice-status">${tx('Canta primero en una zona muy cómoda. No busques extremos.','Start by singing in a very comfortable range. Do not chase extremes.')}</div>`;$('#rangeMic').onclick=startMic;$('#rangeLowBtn').onclick=()=>saveCurrentRange('low');$('#rangeHighBtn').onclick=()=>saveCurrentRange('high');$('#rangeAuto').onclick=startRangeScan;}
function renderPreset(p){const current=localStorage.getItem(PRESET_KEY)||'neutral';p.innerHTML=`<span class="voice-badge">👤 ${tx('Inicio adaptado','Adapted start')}</span><h2>${tx('Perfil vocal orientativo','Suggested vocal profile')}</h2><p>${tx('Elige una zona habitual para que los ejercicios nuevos comiencen más cerca de tu comodidad. No es un diagnóstico ni determina tu tipo de voz.','Choose a usual range so new exercises start closer to your comfort zone. This is not a diagnosis and does not determine your voice type.')}</p><div class="preset-list">${Object.entries(presets).map(([id,x])=>`<button class="preset-card ${id===current?'active':''}" data-preset="${id}"><b>${esc(pick(x.label))}</b><small>${esc(pick(x.desc))}</small><span>${tx('Inicio','Start')}: ${noteLabel(x.start)}</span></button>`).join('')}</div><div class="voice-warning">${tx('El rango real de una persona no se define solo por la nota más grave o aguda. Ajusta siempre por sensación y contexto.','A person’s actual range is not defined only by the lowest or highest note. Always adjust by feel and context.')}</div>`;p.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{localStorage.setItem(PRESET_KEY,b.dataset.preset);p.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('active',x===b));applyPresetToExercises();});}
function renderGroup(p){p.innerHTML=`<span class="voice-badge">👥 ${tx('Ministerio','Ministry')}</span><h2>${tx('Calentamiento grupal','Group warm-up')}</h2><p>${tx('Sesión guiada para poner La Grey junto al piano o frente al grupo. Puedes dejarla avanzar sola o usar “Siguiente”.','A guided session to use La Grey beside the piano or in front of the group. You can let it advance automatically or use “Next”.')}</p><div class="group-session"><div class="group-progress"><div id="groupBar"></div></div><div id="groupStep" class="group-step"><b>${tx('Listos para comenzar','Ready to begin')}</b><span>${tx('8 pasos · aproximadamente 8–9 minutos','8 steps · approximately 8–9 minutes')}</span></div><div id="groupCountdown" class="group-countdown">—</div><div class="voice-play-row"><button class="btn primary" id="groupStart">▶ ${tx('Iniciar grupo','Start group')}</button><button class="btn" id="groupNext">${tx('Siguiente','Next')} ›</button><button class="btn" id="groupStop">■ ${tx('Detener','Stop')}</button></div></div><div class="group-plan">${groupSteps.map(s=>`<div><b>${pick(s.title)}</b><small>${pick(s.instruction)}</small></div>`).join('')}</div>`;$('#groupStart').onclick=()=>startGroup(0);$('#groupNext').onclick=nextGroup;$('#groupStop').onclick=stopGroup;}
async function startMic(){if(micStream)return;try{micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});micCtx=new (window.AudioContext||window.webkitAudioContext)();analyser=micCtx.createAnalyser();analyser.fftSize=2048;buf=new Float32Array(analyser.fftSize);const src=micCtx.createMediaStreamSource(micStream);src.connect(analyser);updateMicButtons(true);micLoop()}catch(e){const a=$('#vproAdvice')||$('#rangeGuide');if(a)a.textContent=tx('No pude abrir el micrófono. Revisa el permiso del navegador.','I could not open the microphone. Check your browser permission.')}}
function stopMic(){cancelAnimationFrame(micRaf);micRaf=0;if(micStream){micStream.getTracks().forEach(t=>t.stop());micStream=null}if(micCtx){micCtx.close().catch(()=>{});micCtx=null}analyser=null;currentMidi=null;stableMidi=null;lastNotes=[];updateMicButtons(false)}
function updateMicButtons(on){const hz=$('#vproHz');if(hz&&!on)hz.textContent=tx('Micrófono apagado','Microphone off');const b=$('#vproMic');if(b)b.textContent=on?`🎙️ ${tx('Escuchando…','Listening…')}`:`🎙️ ${tx('Activar micrófono','Activate microphone')}`;const r=$('#rangeMic');if(r)r.textContent=on?`🎙️ ${tx('Escuchando…','Listening…')}`:`🎙️ ${tx('Activar micrófono','Activate microphone')}`}
function autoCorrelate(buffer,sampleRate){let size=buffer.length,rms=0;for(let i=0;i<size;i++)rms+=buffer[i]*buffer[i];rms=Math.sqrt(rms/size);if(rms<0.012)return-1;let r1=0,r2=size-1,th=.2;for(let i=0;i<size/2;i++){if(Math.abs(buffer[i])<th){r1=i;break}}for(let i=1;i<size/2;i++){if(Math.abs(buffer[size-i])<th){r2=size-i;break}}const b=buffer.slice(r1,r2);size=b.length;const c=new Array(size).fill(0);for(let i=0;i<size;i++)for(let j=0;j<size-i;j++)c[i]+=b[j]*b[j+i];let d=0;while(d<size-1&&c[d]>c[d+1])d++;let max=-1,pos=-1;for(let i=d;i<size;i++)if(c[i]>max){max=c[i];pos=i}if(pos<=0)return-1;let T0=pos;const x1=c[T0-1]||c[T0],x2=c[T0],x3=c[T0+1]||c[T0],a=(x1+x3-2*x2)/2,bv=(x3-x1)/2;if(a)T0-=bv/(2*a);return sampleRate/T0}
function micLoop(){if(!analyser||!micCtx)return;analyser.getFloatTimeDomainData(buf);const f=autoCorrelate(buf,micCtx.sampleRate);if(f>55&&f<1400){const raw=freqMidi(f),nearest=Math.round(raw),cents=Math.round((raw-nearest)*100);currentMidi=raw;currentCents=cents;lastNotes.push(nearest);if(lastNotes.length>7)lastNotes.shift();if(lastNotes.length>=5&&lastNotes.filter(x=>x===nearest).length>=4)stableMidi=nearest;renderMic(f,nearest,cents);if(rangeScan){rangeScan.min=Math.min(rangeScan.min,nearest);rangeScan.max=Math.max(rangeScan.max,nearest)}}micRaf=requestAnimationFrame(micLoop)}
function renderMic(f,m,cents){const n=$('#vproNote');if(n)n.textContent=noteLabel(m);const hz=$('#vproHz');if(hz)hz.textContent=`${f.toFixed(1)} Hz`;const ce=$('#vproCents');if(ce)ce.textContent=`${cents>0?'+':''}${cents} cents`;const needle=$('#vproNeedle');if(needle)needle.style.transform=`translateX(${Math.max(-50,Math.min(50,cents))}%)`;const target=$('#vproTarget');const advice=$('#vproAdvice');if(target&&advice){const t=Number(target.value),diff=(currentMidi-t)*100;if(Math.abs(diff)<18)advice.textContent=lang()==='en'?`✅ Very close to ${noteLabel(t)}.`:`✅ Muy cerca de ${noteLabel(t)}.`;else advice.textContent=diff<0?(lang()==='en'?`⬆️ You are approximately ${Math.abs(Math.round(diff))} cents below the target.`:`⬆️ Estás aproximadamente ${Math.abs(Math.round(diff))} cents por debajo del objetivo.`):(lang()==='en'?`⬇️ You are approximately ${Math.round(diff)} cents above the target.`:`⬇️ Estás aproximadamente ${Math.round(diff)} cents por encima del objetivo.`)}}
function playReference(midi){if(!refCtx)refCtx=new (window.AudioContext||window.webkitAudioContext)();if(refCtx.state==='suspended')refCtx.resume();const t=refCtx.currentTime,g=refCtx.createGain(),o1=refCtx.createOscillator(),o2=refCtx.createOscillator();o1.type='triangle';o2.type='sine';o1.frequency.value=midiFreq(midi);o2.frequency.value=midiFreq(midi)*2;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.16,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+1.25);o1.connect(g);o2.connect(g);g.connect(refCtx.destination);o1.start(t);o2.start(t);o1.stop(t+1.3);o2.stop(t+1.3)}
function loadRange(){try{return JSON.parse(localStorage.getItem(RANGE_KEY)||'null')}catch{return null}}
function rangeSpan(r){if(r.low==null||r.high==null)return tx('Incompleto','Incomplete');const semis=Math.max(0,r.high-r.low);return lang()==='en'?`${semis} semitones · ${(semis/12).toFixed(1)} oct.`:`${semis} semitonos · ${(semis/12).toFixed(1)} oct.`}
function saveCurrentRange(side){if(stableMidi==null){const g=$('#rangeGuide');if(g)g.textContent=tx('Mantén una nota estable unos segundos antes de guardarla.','Hold a stable note for a few seconds before saving it.');return}const r=loadRange()||{};r[side]=stableMidi;if(r.low!=null&&r.high!=null&&r.low>r.high){const t=r.low;r.low=r.high;r.high=t}localStorage.setItem(RANGE_KEY,JSON.stringify(r));const l=$('#rangeLow'),h=$('#rangeHigh'),s=$('#rangeSpan');if(l)l.textContent=r.low!=null?noteLabel(r.low):'—';if(h)h.textContent=r.high!=null?noteLabel(r.high):'—';if(s)s.textContent=rangeSpan(r);const g=$('#rangeGuide');if(g)g.textContent=lang()==='en'?`✅ Saved: ${noteLabel(stableMidi)}.`:`✅ Guardado: ${noteLabel(stableMidi)}.`;applyRangeToExercises()}
async function startRangeScan(){await startMic();if(!micStream)return;rangeScan={min:999,max:-999};const g=$('#rangeGuide');let left=20;if(g)g.textContent=tx('20 s: haz una sirena MUY cómoda, sin perseguir extremos.','20 s: make a VERY comfortable siren without chasing extremes.');const timer=setInterval(()=>{left--;if(g&&left>0)g.textContent=lang()==='en'?`${left} s: move only through your comfortable range.`:`${left} s: recorre solo tu zona cómoda.`},1000);setTimeout(()=>{clearInterval(timer);const r=rangeScan;rangeScan=null;if(!r||r.max<r.min){if(g)g.textContent=tx('No detecté suficientes notas estables. Intenta otra vez.','I did not detect enough stable notes. Try again.');return}localStorage.setItem(RANGE_KEY,JSON.stringify({low:r.min,high:r.max}));if(g)g.textContent=lang()==='en'?`✅ Range detected: ${noteLabel(r.min)} to ${noteLabel(r.max)}. Repeat it another day to confirm.`:`✅ Zona detectada: ${noteLabel(r.min)} a ${noteLabel(r.max)}. Repítela otro día para confirmar.`;const l=$('#rangeLow'),h=$('#rangeHigh'),s=$('#rangeSpan');if(l)l.textContent=noteLabel(r.min);if(h)h.textContent=noteLabel(r.max);if(s)s.textContent=rangeSpan(r);applyRangeToExercises()},20000)}
function observeExercisePanel(){const root=$('#voiceView');if(!root)return;new MutationObserver(()=>{applyPresetToExercises();applyRangeToExercises()}).observe(root,{childList:true,subtree:true})}
function applyPresetToExercises(){const id=localStorage.getItem(PRESET_KEY)||'neutral',start=presets[id]?.start??60;$$('#voicePanel [data-start]').forEach(sel=>{if([...sel.options].some(o=>Number(o.value)===start))sel.value=String(start)})}
function applyRangeToExercises(){const r=loadRange();if(!r)return;$$('#voicePanel [data-start]').forEach(sel=>{const mid=Math.round((r.low+r.high)/2);const options=[...sel.options].map(o=>Number(o.value));const closest=options.reduce((a,b)=>Math.abs(b-mid)<Math.abs(a-mid)?b:a,options[0]);if(Number.isFinite(closest))sel.value=String(closest)})}
function groupPiano(midi,when,dur=.3){if(!refCtx)refCtx=new (window.AudioContext||window.webkitAudioContext)();const g=refCtx.createGain(),o=refCtx.createOscillator();o.type='triangle';o.frequency.value=midiFreq(midi);g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(.13,when+.01);g.gain.exponentialRampToValueAtTime(.0001,when+dur);o.connect(g);g.connect(refCtx.destination);o.start(when);o.stop(when+dur+.03)}
async function startGroup(index=0){stopMic();const token=++groupToken;for(let i=index;i<groupSteps.length;i++){if(token!==groupToken)return;await runGroupStep(i,token)}if(token===groupToken){const s=$('#groupStep');if(s)s.innerHTML=`<b>${tx('✅ Calentamiento terminado','✅ Warm-up complete')}</b><span>${tx('El grupo está listo para pasar al repertorio.','The group is ready to move on to the setlist.')}</span>`;const c=$('#groupCountdown');if(c)c.textContent=tx('¡Listos!','Ready!');const bar=$('#groupBar');if(bar)bar.style.width='100%'}}
async function runGroupStep(i,token){const step=groupSteps[i],box=$('#groupStep'),count=$('#groupCountdown'),bar=$('#groupBar');if(box)box.innerHTML=`<b>${pick(step.title)}</b><span>${pick(step.instruction)}${step.syllable?` · ${tx('Sílaba','Syllable')}: ${step.syllable}`:''}</span>`;if(bar)bar.style.width=`${(i/groupSteps.length)*100}%`;if(step.kind==='pattern'){if(!refCtx)refCtx=new (window.AudioContext||window.webkitAudioContext)();if(refCtx.state==='suspended')await refCtx.resume();for(let rep=0;rep<5;rep++){if(token!==groupToken)return;const root=step.root+rep,beat=.42,t=refCtx.currentTime+.05;step.pattern.forEach((n,j)=>groupPiano(root+n,t+j*beat,.28));await delay(step.pattern.length*beat*1000+700)}}let left=Math.max(8,step.seconds-(step.kind==='pattern'?28:0));while(left>0&&token===groupToken){if(count)count.textContent=`${left} s`;await delay(1000);left--}if(bar)bar.style.width=`${((i+1)/groupSteps.length)*100}%`}
function nextGroup(){groupToken++;const text=$('#groupStep b')?.textContent||'';const m=text.match(/^(\d+)/),cur=m?Number(m[1])-1:-1;startGroup(Math.min(groupSteps.length-1,cur+1))}
function stopGroup(){groupToken++;const c=$('#groupCountdown');if(c)c.textContent=tx('Detenido','Stopped');}
function delay(ms){return new Promise(r=>setTimeout(r,ms))}
function refreshLanguage(){refreshToolCards();const p=$('#voiceProPanel');if(currentTool&&p&&!p.classList.contains('hidden')){if(currentTool==='pitch')renderPitch(p);if(currentTool==='range')renderRange(p);if(currentTool==='preset')renderPreset(p);if(currentTool==='group')renderGroup(p)}}
function cleanupOnLeave(e){if(!$('#voiceView')||$('#voiceView').classList.contains('hidden'))return;const t=e.target.closest('nav button,[data-voice-home],[data-home],[data-nav]');if(t){stopMic();stopGroup()}}
document.addEventListener('click',cleanupOnLeave,true);
window.LAGREY_REFRESH_VOICE_PRO_I18N=refreshLanguage;
new MutationObserver(muts=>{if(muts.some(m=>m.attributeName==='lang'))refreshLanguage()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
function boot(){if(inject())return;let tries=0;const id=setInterval(()=>{tries++;if(inject()||tries>50)clearInterval(id)},100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();