(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const NAMES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const LATIN={'C':'Do','C#':'Do#','D':'Re','D#':'Re#','E':'Mi','F':'Fa','F#':'Fa#','G':'Sol','G#':'Sol#','A':'La','A#':'La#','B':'Si'};
const RANGE_KEY='lagrey_voice_range_v1',PRESET_KEY='lagrey_voice_preset_v1';
let micCtx=null,micStream=null,analyser=null,micRaf=0,buf=null,currentMidi=null,currentCents=0,stableMidi=null,lastNotes=[];
let rangeScan=null,groupToken=0,refCtx=null;
const presets={
 neutral:{label:'Sin perfil · zona media',start:60,desc:'La Grey comienza en Do4 y tú ajustas según comodidad.'},
 soprano:{label:'Soprano · inicio orientativo',start:60,desc:'Empieza en una zona media y sube solo mientras siga fácil.'},
 alto:{label:'Alto / mezzo · inicio orientativo',start:57,desc:'Empieza un poco más abajo para trabajar cómodamente.'},
 tenor:{label:'Tenor · inicio orientativo',start:52,desc:'Comienza en Mi3 y ajusta según tu voz real.'},
 baritone:{label:'Barítono · inicio orientativo',start:48,desc:'Comienza en Do3 y sube progresivamente.'},
 bass:{label:'Bajo · inicio orientativo',start:45,desc:'Comienza en La2 y evita fabricar graves.'}
};
const groupSteps=[
 {title:'1. Preparar cuerpo y aire',seconds:45,kind:'timer',instruction:'Postura libre. Inhalen 4 tiempos y suelten en SSS sin empujar.'},
 {title:'2. Trino de labios',seconds:70,kind:'pattern',root:52,pattern:[0,2,4,5,7,5,4,2,0],syllable:'Brrr',instruction:'Todos suaves. El piano subirá por semitonos.'},
 {title:'3. Resonancia',seconds:70,kind:'pattern',root:53,pattern:[0,2,4,2,0],syllable:'MMM → MA',instruction:'Conserven la facilidad del MMM al abrir a MA.'},
 {title:'4. Afinación en grupo',seconds:75,kind:'pattern',root:55,pattern:[0,4,7,4,0],syllable:'NO',instruction:'Escuchen primero y repitan juntos sin arrastrar las notas.'},
 {title:'5. Rango medio',seconds:85,kind:'pattern',root:52,pattern:[0,2,4,5,7,9,7,5,4,2,0],syllable:'NU',instruction:'No compitan por subir. Cada persona se detiene donde sigue cómoda.'},
 {title:'6. Agilidad',seconds:70,kind:'pattern',root:53,pattern:[0,2,4,5,7,5,4,2,0],syllable:'DA-GA',instruction:'Ligero y rítmico; claridad antes que velocidad.'},
 {title:'7. Dicción',seconds:70,kind:'pattern',root:55,pattern:[0,2,4,5,7,5,4,2,0],syllable:'MA-ME-MI-MO-MU',instruction:'Vocales claras, mandíbula libre.'},
 {title:'8. Listos para cantar',seconds:35,kind:'timer',instruction:'Respiren normal, hablen una frase del repertorio y mantengan la voz natural.'}
];
function midiFreq(m){return 440*Math.pow(2,(m-69)/12)}
function freqMidi(f){return 69+12*Math.log2(f/440)}
function noteLabel(m){if(m==null)return'--';const r=Math.round(m),n=NAMES[(r%12+12)%12],o=Math.floor(r/12)-1;return `${LATIN[n]||n}${o} · ${n}${o}`}
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function inject(){const view=$('#voiceView');if(!view||$('#voiceProTools'))return false;const panel=document.createElement('div');panel.id='voiceProTools';panel.className='voice-pro-tools';panel.innerHTML=`
<h2>🎙️ Herramientas de voz</h2><p class="voice-pro-intro">Usa el micrófono para ver tu nota, practicar afinación, guardar tu rango cómodo y preparar a todo el grupo.</p>
<div class="voice-pro-grid">
 <button class="voice-pro-card" data-vpro="pitch"><span>🎯</span><b>Detector y afinación</b><small>Ve tu nota y qué tan cerca estás del objetivo.</small></button>
 <button class="voice-pro-card" data-vpro="range"><span>↕️</span><b>Mi rango cómodo</b><small>Prueba, guarda y reutiliza tu zona de trabajo.</small></button>
 <button class="voice-pro-card" data-vpro="preset"><span>👤</span><b>Perfil vocal</b><small>Soprano, alto, tenor, barítono o bajo como punto de partida.</small></button>
 <button class="voice-pro-card" data-vpro="group"><span>👥</span><b>Calentamiento grupal</b><small>Una sesión guiada para ensayo o culto.</small></button>
</div><div id="voiceProPanel" class="voice-pro-panel hidden"></div>`;
 const routines=view.querySelector('.voice-routines');if(routines)routines.parentNode.insertBefore(panel,routines);else view.appendChild(panel);
 panel.addEventListener('click',e=>{const b=e.target.closest('[data-vpro]');if(b)showTool(b.dataset.vpro)});
 observeExercisePanel();return true}
function showTool(id){stopGroup();const p=$('#voiceProPanel');p.classList.remove('hidden');if(id==='pitch')renderPitch(p);if(id==='range')renderRange(p);if(id==='preset')renderPreset(p);if(id==='group')renderGroup(p);p.scrollIntoView({behavior:'smooth',block:'start'})}
function renderPitch(p){p.innerHTML=`<span class="voice-badge">🎯 Micrófono</span><h2>Detector de nota y afinación</h2><p>Canta una nota cómoda. La Grey muestra la nota más cercana y los cents de diferencia.</p><div class="pitch-live"><div id="vproNote" class="pitch-note">--</div><div id="vproHz" class="pitch-hz">Micrófono apagado</div><div class="pitch-meter"><div class="pitch-center"></div><div id="vproNeedle" class="pitch-needle"></div></div><div class="pitch-labels"><span>♭ bajo</span><span id="vproCents">0 cents</span><span>alto ♯</span></div></div><div class="voice-controls"><label>Nota objetivo<select id="vproTarget">${[48,50,52,53,55,57,59,60,62,64,65,67,69,71,72].map(m=>`<option value="${m}" ${m===60?'selected':''}>${noteLabel(m)}</option>`).join('')}</select></label></div><div class="voice-play-row"><button class="btn primary" id="vproMic">🎙️ Activar micrófono</button><button class="btn" id="vproReference">🎹 Oír objetivo</button><button class="btn" id="vproMicStop">■ Detener</button></div><div id="vproAdvice" class="voice-status">Activa el micrófono y canta sin gritar.</div>`;$('#vproMic').onclick=startMic;$('#vproMicStop').onclick=stopMic;$('#vproReference').onclick=()=>playReference(Number($('#vproTarget').value));}
function renderRange(p){const saved=loadRange();p.innerHTML=`<span class="voice-badge">↕️ Personal</span><h2>Mi rango cómodo</h2><p>Esto no clasifica tu voz. Guarda solo notas que puedas producir con comodidad, sin presión.</p><div class="range-summary"><div><small>Grave cómodo</small><b id="rangeLow">${saved?.low!=null?noteLabel(saved.low):'—'}</b></div><div><small>Agudo cómodo</small><b id="rangeHigh">${saved?.high!=null?noteLabel(saved.high):'—'}</b></div><div><small>Extensión guardada</small><b id="rangeSpan">${saved?rangeSpan(saved):'—'}</b></div></div><div class="pitch-live compact"><div id="vproNote" class="pitch-note">--</div><div id="vproHz" class="pitch-hz">Activa el micrófono</div></div><div class="voice-play-row"><button class="btn primary" id="rangeMic">🎙️ Activar micrófono</button><button class="btn" id="rangeAuto">▶ Prueba guiada 20 s</button><button class="btn" id="rangeLowBtn">↓ Guardar como grave</button><button class="btn" id="rangeHighBtn">↑ Guardar como agudo</button></div><div id="rangeGuide" class="voice-status">Canta primero en una zona muy cómoda. No busques extremos.</div>`;$('#rangeMic').onclick=startMic;$('#rangeLowBtn').onclick=()=>saveCurrentRange('low');$('#rangeHighBtn').onclick=()=>saveCurrentRange('high');$('#rangeAuto').onclick=startRangeScan;}
function renderPreset(p){const current=localStorage.getItem(PRESET_KEY)||'neutral';p.innerHTML=`<span class="voice-badge">👤 Inicio adaptado</span><h2>Perfil vocal orientativo</h2><p>Elige una zona habitual para que los ejercicios nuevos comiencen más cerca de tu comodidad. No es un diagnóstico ni determina tu tipo de voz.</p><div class="preset-list">${Object.entries(presets).map(([id,x])=>`<button class="preset-card ${id===current?'active':''}" data-preset="${id}"><b>${esc(x.label)}</b><small>${esc(x.desc)}</small><span>Inicio: ${noteLabel(x.start)}</span></button>`).join('')}</div><div class="voice-warning">El rango real de una persona no se define solo por la nota más grave o aguda. Ajusta siempre por sensación y contexto.</div>`;p.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{localStorage.setItem(PRESET_KEY,b.dataset.preset);p.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('active',x===b));applyPresetToExercises();});}
function renderGroup(p){p.innerHTML=`<span class="voice-badge">👥 Ministerio</span><h2>Calentamiento grupal</h2><p>Sesión guiada para poner La Grey junto al piano o frente al grupo. Puedes dejarla avanzar sola o usar “Siguiente”.</p><div class="group-session"><div class="group-progress"><div id="groupBar"></div></div><div id="groupStep" class="group-step"><b>Listos para comenzar</b><span>8 pasos · aproximadamente 8–9 minutos</span></div><div id="groupCountdown" class="group-countdown">—</div><div class="voice-play-row"><button class="btn primary" id="groupStart">▶ Iniciar grupo</button><button class="btn" id="groupNext">Siguiente ›</button><button class="btn" id="groupStop">■ Detener</button></div></div><div class="group-plan">${groupSteps.map(s=>`<div><b>${s.title}</b><small>${s.instruction}</small></div>`).join('')}</div>`;$('#groupStart').onclick=()=>startGroup(0);$('#groupNext').onclick=nextGroup;$('#groupStop').onclick=stopGroup;}
async function startMic(){if(micStream)return;try{micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});micCtx=new (window.AudioContext||window.webkitAudioContext)();analyser=micCtx.createAnalyser();analyser.fftSize=2048;buf=new Float32Array(analyser.fftSize);const src=micCtx.createMediaStreamSource(micStream);src.connect(analyser);updateMicButtons(true);micLoop()}catch(e){const a=$('#vproAdvice')||$('#rangeGuide');if(a)a.textContent='No pude abrir el micrófono. Revisa el permiso del navegador.'}}
function stopMic(){cancelAnimationFrame(micRaf);micRaf=0;if(micStream){micStream.getTracks().forEach(t=>t.stop());micStream=null}if(micCtx){micCtx.close().catch(()=>{});micCtx=null}analyser=null;currentMidi=null;stableMidi=null;lastNotes=[];updateMicButtons(false)}
function updateMicButtons(on){const hz=$('#vproHz');if(hz&&!on)hz.textContent='Micrófono apagado';const b=$('#vproMic');if(b)b.textContent=on?'🎙️ Escuchando…':'🎙️ Activar micrófono'}
function autoCorrelate(buffer,sampleRate){let size=buffer.length,rms=0;for(let i=0;i<size;i++)rms+=buffer[i]*buffer[i];rms=Math.sqrt(rms/size);if(rms<0.012)return-1;let r1=0,r2=size-1,th=.2;for(let i=0;i<size/2;i++){if(Math.abs(buffer[i])<th){r1=i;break}}for(let i=1;i<size/2;i++){if(Math.abs(buffer[size-i])<th){r2=size-i;break}}const b=buffer.slice(r1,r2);size=b.length;const c=new Array(size).fill(0);for(let i=0;i<size;i++)for(let j=0;j<size-i;j++)c[i]+=b[j]*b[j+i];let d=0;while(d<size-1&&c[d]>c[d+1])d++;let max=-1,pos=-1;for(let i=d;i<size;i++)if(c[i]>max){max=c[i];pos=i}if(pos<=0)return-1;let T0=pos;const x1=c[T0-1]||c[T0],x2=c[T0],x3=c[T0+1]||c[T0],a=(x1+x3-2*x2)/2,bv=(x3-x1)/2;if(a)T0-=bv/(2*a);return sampleRate/T0}
function micLoop(){if(!analyser||!micCtx)return;analyser.getFloatTimeDomainData(buf);const f=autoCorrelate(buf,micCtx.sampleRate);if(f>55&&f<1400){const raw=freqMidi(f),nearest=Math.round(raw),cents=Math.round((raw-nearest)*100);currentMidi=raw;currentCents=cents;lastNotes.push(nearest);if(lastNotes.length>7)lastNotes.shift();if(lastNotes.length>=5&&lastNotes.filter(x=>x===nearest).length>=4)stableMidi=nearest;renderMic(f,nearest,cents);if(rangeScan){rangeScan.min=Math.min(rangeScan.min,nearest);rangeScan.max=Math.max(rangeScan.max,nearest)}}micRaf=requestAnimationFrame(micLoop)}
function renderMic(f,m,cents){const n=$('#vproNote');if(n)n.textContent=noteLabel(m);const hz=$('#vproHz');if(hz)hz.textContent=`${f.toFixed(1)} Hz`;const ce=$('#vproCents');if(ce)ce.textContent=`${cents>0?'+':''}${cents} cents`;const needle=$('#vproNeedle');if(needle)needle.style.transform=`translateX(${Math.max(-50,Math.min(50,cents))}%)`;const target=$('#vproTarget');const advice=$('#vproAdvice');if(target&&advice){const t=Number(target.value),diff=(currentMidi-t)*100;if(Math.abs(diff)<18)advice.textContent=`✅ Muy cerca de ${noteLabel(t)}.`;else advice.textContent=diff<0?`⬆️ Estás aproximadamente ${Math.abs(Math.round(diff))} cents por debajo del objetivo.`:`⬇️ Estás aproximadamente ${Math.round(diff)} cents por encima del objetivo.`}}
function playReference(midi){if(!refCtx)refCtx=new (window.AudioContext||window.webkitAudioContext)();if(refCtx.state==='suspended')refCtx.resume();const t=refCtx.currentTime,g=refCtx.createGain(),o1=refCtx.createOscillator(),o2=refCtx.createOscillator();o1.type='triangle';o2.type='sine';o1.frequency.value=midiFreq(midi);o2.frequency.value=midiFreq(midi)*2;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.16,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+1.25);o1.connect(g);o2.connect(g);g.connect(refCtx.destination);o1.start(t);o2.start(t);o1.stop(t+1.3);o2.stop(t+1.3)}
function loadRange(){try{return JSON.parse(localStorage.getItem(RANGE_KEY)||'null')}catch{return null}}
function rangeSpan(r){if(r.low==null||r.high==null)return'Incompleto';const semis=Math.max(0,r.high-r.low);return `${semis} semitonos · ${(semis/12).toFixed(1)} oct.`}
function saveCurrentRange(side){if(stableMidi==null){const g=$('#rangeGuide');if(g)g.textContent='Mantén una nota estable unos segundos antes de guardarla.';return}const r=loadRange()||{};r[side]=stableMidi;if(r.low!=null&&r.high!=null&&r.low>r.high){const t=r.low;r.low=r.high;r.high=t}localStorage.setItem(RANGE_KEY,JSON.stringify(r));const l=$('#rangeLow'),h=$('#rangeHigh'),s=$('#rangeSpan');if(l)l.textContent=r.low!=null?noteLabel(r.low):'—';if(h)h.textContent=r.high!=null?noteLabel(r.high):'—';if(s)s.textContent=rangeSpan(r);const g=$('#rangeGuide');if(g)g.textContent=`✅ Guardado: ${noteLabel(stableMidi)}.`;applyRangeToExercises()}
async function startRangeScan(){await startMic();if(!micStream)return;rangeScan={min:999,max:-999};const g=$('#rangeGuide');let left=20;if(g)g.textContent='20 s: haz una sirena MUY cómoda, sin perseguir extremos.';const timer=setInterval(()=>{left--;if(g&&left>0)g.textContent=`${left} s: recorre solo tu zona cómoda.`},1000);setTimeout(()=>{clearInterval(timer);const r=rangeScan;rangeScan=null;if(!r||r.max<r.min){if(g)g.textContent='No detecté suficientes notas estables. Intenta otra vez.';return}localStorage.setItem(RANGE_KEY,JSON.stringify({low:r.min,high:r.max}));if(g)g.textContent=`✅ Zona detectada: ${noteLabel(r.min)} a ${noteLabel(r.max)}. Repítela otro día para confirmar.`;const l=$('#rangeLow'),h=$('#rangeHigh'),s=$('#rangeSpan');if(l)l.textContent=noteLabel(r.min);if(h)h.textContent=noteLabel(r.max);if(s)s.textContent=rangeSpan(r);applyRangeToExercises()},20000)}
function observeExercisePanel(){const root=$('#voiceView');if(!root)return;new MutationObserver(()=>{applyPresetToExercises();applyRangeToExercises()}).observe(root,{childList:true,subtree:true})}
function applyPresetToExercises(){const id=localStorage.getItem(PRESET_KEY)||'neutral',start=presets[id]?.start??60;$$('#voicePanel [data-start]').forEach(sel=>{if([...sel.options].some(o=>Number(o.value)===start))sel.value=String(start)})}
function applyRangeToExercises(){const r=loadRange();if(!r)return;$$('#voicePanel [data-start]').forEach(sel=>{const mid=Math.round((r.low+r.high)/2);const options=[...sel.options].map(o=>Number(o.value));const closest=options.reduce((a,b)=>Math.abs(b-mid)<Math.abs(a-mid)?b:a,options[0]);if(Number.isFinite(closest))sel.value=String(closest)})}
function groupPiano(midi,when,dur=.3){if(!refCtx)refCtx=new (window.AudioContext||window.webkitAudioContext)();const g=refCtx.createGain(),o=refCtx.createOscillator();o.type='triangle';o.frequency.value=midiFreq(midi);g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(.13,when+.01);g.gain.exponentialRampToValueAtTime(.0001,when+dur);o.connect(g);g.connect(refCtx.destination);o.start(when);o.stop(when+dur+.03)}
async function startGroup(index=0){stopMic();const token=++groupToken;for(let i=index;i<groupSteps.length;i++){if(token!==groupToken)return;await runGroupStep(i,token)}if(token===groupToken){const s=$('#groupStep');if(s)s.innerHTML='<b>✅ Calentamiento terminado</b><span>El grupo está listo para pasar al repertorio.</span>';const c=$('#groupCountdown');if(c)c.textContent='¡Listos!';const bar=$('#groupBar');if(bar)bar.style.width='100%'}}
async function runGroupStep(i,token){const step=groupSteps[i],box=$('#groupStep'),count=$('#groupCountdown'),bar=$('#groupBar');if(box)box.innerHTML=`<b>${step.title}</b><span>${step.instruction}${step.syllable?` · Sílaba: ${step.syllable}`:''}</span>`;if(bar)bar.style.width=`${(i/groupSteps.length)*100}%`;if(step.kind==='pattern'){if(!refCtx)refCtx=new (window.AudioContext||window.webkitAudioContext)();if(refCtx.state==='suspended')await refCtx.resume();for(let rep=0;rep<5;rep++){if(token!==groupToken)return;const root=step.root+rep,beat=.42,t=refCtx.currentTime+.05;step.pattern.forEach((n,j)=>groupPiano(root+n,t+j*beat,.28));await delay(step.pattern.length*beat*1000+700)}}let left=Math.max(8,step.seconds-(step.kind==='pattern'?28:0));while(left>0&&token===groupToken){if(count)count.textContent=`${left} s`;await delay(1000);left--}if(bar)bar.style.width=`${((i+1)/groupSteps.length)*100}%`}
function nextGroup(){groupToken++;const text=$('#groupStep b')?.textContent||'';const m=text.match(/^(\d+)/),cur=m?Number(m[1])-1:-1;startGroup(Math.min(groupSteps.length-1,cur+1))}
function stopGroup(){groupToken++;const c=$('#groupCountdown');if(c)c.textContent='Detenido';}
function delay(ms){return new Promise(r=>setTimeout(r,ms))}
function cleanupOnLeave(e){if(!$('#voiceView')||$('#voiceView').classList.contains('hidden'))return;const t=e.target.closest('nav button,[data-voice-home],[data-home],[data-nav]');if(t){stopMic();stopGroup()}}
document.addEventListener('click',cleanupOnLeave,true);
function boot(){if(inject())return;let tries=0;const id=setInterval(()=>{tries++;if(inject()||tries>50)clearInterval(id)},100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();